import type {Lang} from '@/lib/kb';
// Translations of the existing registry, not new eligibility requirements.
const translations:Record<string,[string,string]>={
'आधार कार्ड व आधार-लिंक बँक खातं':['Aadhaar card and Aadhaar-linked bank account','आधार कार्ड और आधार से जुड़ा बैंक खाता'],
'वडिलांचा/पतीचा आधार (e-KYC साठी)':['Father’s/husband’s Aadhaar (for e-KYC)','पिता/पति का आधार (ई-केवाईसी के लिए)'],
'रहिवासाचा पुरावा':['Proof of residence','निवास का प्रमाण'],
'उत्पन्नाचा पुरावा / रेशन कार्ड':['Income proof / ration card','आय का प्रमाण / राशन कार्ड'],
'मुलीचा जन्म दाखला':['Girl’s birth certificate','बेटी का जन्म प्रमाण पत्र'],
'तहसीलदारांचा उत्पन्न दाखला':['Income certificate from the Tahsildar','तहसीलदार का आय प्रमाण पत्र'],
'आधार (मुलगी, आई, वडील)':['Aadhaar (girl, mother, father)','आधार (बेटी, माँ, पिता)'],
'बँक पासबुक':['Bank passbook','बैंक पासबुक'],
'पिवळे/केशरी रेशन कार्ड':['Yellow/orange ration card','पीला/नारंगी राशन कार्ड'],
'शाळेचा बोनाफाईड (पुढच्या हप्त्यांसाठी)':['School bonafide certificate (later instalments)','स्कूल का बोनाफाइड प्रमाण पत्र (अगली किस्तों के लिए)'],
'कुटुंब नियोजन प्रमाणपत्र (लागू असल्यास)':['Family planning certificate (if applicable)','परिवार नियोजन प्रमाण पत्र (यदि लागू हो)'],
'आधार':['Aadhaar','आधार'],
'आधार-लिंक बँक/पोस्ट खातं':['Aadhaar-linked bank/post office account','आधार से जुड़ा बैंक/डाकघर खाता'],
'मोबाइल नंबर':['Mobile number','मोबाइल नंबर'],
'माता-बाल संरक्षण (MCP) कार्ड':['Mother and Child Protection (MCP) card','मातृ एवं शिशु सुरक्षा (MCP) कार्ड'],
'पात्रतेचा पुरावा':['Proof of eligibility','पात्रता का प्रमाण'],
'जन्म दाखला व लसीकरण नोंद (दुसऱ्या हप्त्यासाठी)':['Birth certificate and vaccination record (second instalment)','जन्म प्रमाण पत्र और टीकाकरण रिकॉर्ड (दूसरी किस्त के लिए)'],
'पालकांचं ओळखपत्र व पत्ता पुरावा':['Parent’s identity and address proof','अभिभावक का पहचान और पते का प्रमाण'],
'रहिवासी दाखला':['Residence certificate','निवास प्रमाण पत्र'],
'वयाचा पुरावा':['Proof of age','उम्र का प्रमाण'],
'रेशन कार्ड':['Ration card','राशन कार्ड'],
'उत्पन्न दाखला':['Income certificate','आय प्रमाण पत्र'],
'दिव्यांग प्रमाणपत्र (लागू असल्यास)':['Disability certificate (if applicable)','दिव्यांगता प्रमाण पत्र (यदि लागू हो)'],
'फोटो':['Photograph','फोटो'],
'बँक खातं':['Bank account','बैंक खाता'],
'आधार, पॅन':['Aadhaar and PAN','आधार और पैन'],
'व्यवसायाची माहिती / अंदाजपत्रक':['Business details / estimate','व्यवसाय का विवरण / अनुमान'],
'बँक स्टेटमेंट':['Bank statement','बैंक स्टेटमेंट'],
'प्रकल्प अहवाल':['Project report','परियोजना रिपोर्ट'],
'शैक्षणिक दाखला':['Education certificate','शैक्षणिक प्रमाण पत्र'],
'मोबाइल':['Mobile phone','मोबाइल'],
'प्रकल्प माहिती':['Project details','परियोजना का विवरण'],
'ओळखपत्र':['Identity proof','पहचान पत्र'],
'व्यवसाय नोंदणी':['Business registration','व्यवसाय पंजीकरण'],
'₹100 स्टॅम्प पेपरवर प्रतिज्ञापत्र':['Affidavit on ₹100 stamp paper','₹100 के स्टाम्प पेपर पर शपथ पत्र'],
'पॅन':['PAN','पैन'],
'अन्न व्यवसायासाठी FDA परवाना':['FDA licence for food business','खाद्य व्यवसाय के लिए FDA लाइसेंस'],
'500 शब्दांचा प्रकल्प आराखडा':['500-word project outline','500 शब्दों की परियोजना रूपरेखा'],
'₹50 शुल्क (gras.mahakosh.gov.in)':['₹50 fee (gras.mahakosh.gov.in)','₹50 शुल्क (gras.mahakosh.gov.in)'],
'प्रवर्ग दाखला':['Category certificate','वर्ग प्रमाण पत्र'],
'CAP प्रवेश पत्र':['CAP admission letter','CAP प्रवेश पत्र'],
'आधार, बँक खातं':['Aadhaar and bank account','आधार और बैंक खाता'],
'DPIIT मान्यता':['DPIIT recognition','DPIIT मान्यता'],
'कंपनी नोंदणी':['Company registration','कंपनी पंजीकरण'],
'आर्थिक विवरण':['Financial statement','वित्तीय विवरण'],
'आधार-लिंक मोबाइल':['Aadhaar-linked mobile','आधार से जुड़ा मोबाइल'],
'माता-बाल संरक्षण (MCP) कार्ड (असल्यास)':['MCP card (if available)','MCP कार्ड (यदि उपलब्ध हो)'],
'आधार कार्ड (असल्यास)':['Aadhaar card (if available)','आधार कार्ड (यदि उपलब्ध हो)'],
'आधीचे तपासणी रिपोर्ट (असल्यास)':['Earlier examination reports (if available)','पुरानी जाँच रिपोर्ट (यदि उपलब्ध हों)'],
'माता-बाल संरक्षण (MCP) कार्ड (गरोदर असल्यास)':['MCP card (if pregnant)','MCP कार्ड (यदि गर्भवती हों)'],
'शाळेत मुलाचं नाव दाखल':['Child enrolled at school','स्कूल में बच्चे का नाम दर्ज'],
};
export function documentLabel(text:string,lang:Lang){return lang==='mr'?text:translations[text]?.[lang==='en'?0:1]??text;}
