// GIRL CHILD & ADOLESCENT pathway (ages ~10–18).
// Friendly "ताई" tone, short sentences, trusted adult first, 1098 for safety, 112 for danger.

import type { Topic } from "./types";

export const girlTopics: Topic[] = [
  // ───────────────────────── GROWING UP ─────────────────────────
  {
    id: "g_first_period",
    intent: "learn",
    ages: ["girl"],
    title: {
      mr: "माझी पहिली पाळी",
      en: "My first period",
      hi: "मेरा पहला पीरियड",
    },
    keywords: [
      "first period",
      "periods first time",
      "what is period",
      "पाळी",
      "पाळी पहिल्यांदा",
      "पहिली पाळी",
      "मासिक पाळी",
      "रक्त आलं",
      "पीरियड",
      "पहला पीरियड",
      "माहवारी",
      "महीना आया",
      "period aaya",
      "pahili pali",
      "pali aali",
      "mc",
      "menstruation",
      "blood in underwear",
    ],
    understand: {
      mr: "पहिली पाळी आली की थोडी भीती किंवा गोंधळ वाटू शकतो. हे अगदी नैसर्गिक आहे — तुझं शरीर मोठं होतंय.",
      en: "Getting your first period can feel scary or confusing. It is completely normal — your body is growing up.",
      hi: "पहला पीरियड आने पर डर या उलझन हो सकती है। यह बिल्कुल सामान्य है — तुम्हारा शरीर बड़ा हो रहा है।",
    },
    answer: [
      {
        mr: "पाळी साधारण 10 ते 15 वर्षांच्या वयात सुरू होते. दर महिन्याला 3 ते 7 दिवस रक्त येतं.",
        en: "Periods usually start between 10 and 15. Bleeding lasts about 3 to 7 days each month.",
        hi: "पीरियड आमतौर पर 10 से 15 साल में शुरू होते हैं। हर महीने 3 से 7 दिन खून आता है।",
      },
      {
        mr: "सुरुवातीला पाळी अनियमित असू शकते. पहिल्या 1–2 वर्षांत हे नॉर्मल आहे.",
        en: "At first your periods may not come on time. That is normal for the first 1–2 years.",
        hi: "शुरू में पीरियड समय पर न आएं तो भी चलता है। पहले 1–2 साल यह सामान्य है।",
      },
      {
        mr: "Pad किंवा स्वच्छ सुती कापड वापर. आई, ताई किंवा शाळेतल्या बाईंना सांग.",
        en: "Use a pad or a clean cotton cloth. Tell your mother, an elder sister or a teacher.",
        hi: "Pad या साफ़ सूती कपड़ा इस्तेमाल करो। माँ, दीदी या टीचर को बताओ।",
      },
      {
        mr: "पाळीत तू शाळेत जाऊ शकतेस, खेळू शकतेस, अंघोळ करू शकतेस. तू अपवित्र नाहीस.",
        en: "You can go to school, play and bathe during your period. You are not impure.",
        hi: "पीरियड में तुम स्कूल जा सकती हो, खेल सकती हो, नहा सकती हो। तुम अपवित्र नहीं हो।",
      },
      {
        mr: "Bag मध्ये नेहमी एक pad आणि एक जास्तीचा underwear ठेव.",
        en: "Keep one spare pad and underwear in your school bag.",
        hi: "School bag में हमेशा एक pad और एक extra underwear रखो।",
      },
    ],
    next: {
      mr: "तुला कोणाशी बोलायला सोपं वाटेल — आई, ताई की शाळेतल्या बाई?",
      en: "Who would you feel easy talking to — your mother, an elder sister or a teacher?",
      hi: "तुम्हें किससे बात करना आसान लगेगा — माँ, दीदी या टीचर?",
    },
    actions: [
      {
        label: { mr: "स्वच्छतेबद्दल वाच", en: "Read about hygiene", hi: "सफ़ाई के बारे में पढ़ो" },
        href: "/everyday",
      },
    ],
  },
  {
    id: "g_period_pain",
    intent: "check",
    ages: ["girl"],
    sensitive: "medical",
    title: {
      mr: "पाळीत पोट दुखतं",
      en: "Period pain",
      hi: "पीरियड में दर्द",
    },
    keywords: [
      "period pain",
      "stomach pain periods",
      "cramps",
      "पाळीत पोट दुखतं",
      "पोट दुखतं",
      "कंबर दुखते",
      "पाळीत त्रास",
      "पीरियड में दर्द",
      "पेट दर्द",
      "कमर दर्द",
      "pet dard",
      "pot dukhta",
      "bahut khoon",
      "जास्त रक्त",
      "ज़्यादा खून",
      "chakkar",
      "चक्कर",
    ],
    understand: {
      mr: "पाळीत थोडं पोट किंवा कंबर दुखणं अनेक मुलींना होतं. पण खूप त्रास होत असेल तर सांगायला हवं.",
      en: "Many girls get some stomach or back pain during periods. But if it hurts a lot, you should tell someone.",
      hi: "पीरियड में थोड़ा पेट या कमर दर्द कई लड़कियों को होता है। पर बहुत दर्द हो तो बताना चाहिए।",
    },
    answer: [
      {
        mr: "गरम पाण्याची पिशवी पोटावर ठेव. कोमट पाणी पी आणि थोडी विश्रांती घे.",
        en: "Put a warm water bag on your tummy. Drink warm water and rest a little.",
        hi: "पेट पर गरम पानी की थैली रखो। गुनगुना पानी पियो और थोड़ा आराम करो।",
      },
      {
        mr: "हलकं चालणं किंवा हलके stretching केल्याने बरं वाटू शकतं.",
        en: "Gentle walking or light stretching can help.",
        hi: "हल्का चलना या हल्की stretching करने से आराम मिल सकता है।",
      },
      {
        mr: "स्वतःहून गोळी घेऊ नकोस. आई किंवा मोठ्या माणसाला विचार.",
        en: "Don't take any tablet on your own. Ask your mother or an adult first.",
        hi: "खुद से कोई गोली मत लो। पहले माँ या किसी बड़े से पूछो।",
      },
      {
        mr: "शाळा चुकेल इतकं दुखणं, 7 दिवसांपेक्षा जास्त रक्त, किंवा चक्कर येत असेल तर डॉक्टरकडे जा.",
        en: "See a doctor if pain makes you miss school, bleeding lasts over 7 days, or you feel dizzy.",
        hi: "दर्द से स्कूल छूटे, 7 दिन से ज़्यादा खून आए, या चक्कर आए तो डॉक्टर को दिखाओ।",
      },
      {
        mr: "1–2 तासांत pad पूर्ण भिजत असेल तर मोठ्या माणसाला लगेच सांग.",
        en: "If a pad soaks through in 1–2 hours, tell an adult right away.",
        hi: "अगर 1–2 घंटे में pad पूरा भीग जाए तो तुरंत किसी बड़े को बताओ।",
      },
    ],
    next: {
      mr: "आज घरी आईला किंवा ताईला तुझा त्रास सांगशील का?",
      en: "Can you tell your mother or an elder sister about the pain today?",
      hi: "क्या आज घर पर माँ या दीदी को अपना दर्द बताओगी?",
    },
    actions: [
      {
        label: { mr: "खूप त्रास — 108 ambulance", en: "Severe — call 108 ambulance", hi: "बहुत तकलीफ़ — 108 ambulance" },
        href: "tel:108",
      },
    ],
    girlNote: {
      mr: "Anganwadi ताई किंवा PHC मधली नर्स पण मदत करू शकते.",
      en: "Your Anganwadi tai or the PHC nurse can also help.",
      hi: "आंगनवाड़ी दीदी या PHC की नर्स भी मदद कर सकती हैं।",
    },
  },
  {
    id: "g_puberty",
    intent: "learn",
    ages: ["girl"],
    title: {
      mr: "शरीरात होणारे बदल",
      en: "Puberty & body changes",
      hi: "शरीर में बदलाव",
    },
    keywords: [
      "puberty",
      "body changes",
      "breast growing",
      "hair under arms",
      "शरीरात बदल",
      "छाती वाढते",
      "केस येतात",
      "पिंपल्स",
      "मुरुम",
      "शरीर में बदलाव",
      "किशोरावस्था",
      "मुंहासे",
      "body change ho raha",
      "sharir badal raha",
      "pimples",
      "height badhna",
      "white discharge",
      "पांढरं पाणी",
      "सफ़ेद पानी",
    ],
    understand: {
      mr: "10–15 वर्षांच्या वयात शरीरात खूप बदल होतात. याला किशोरावस्था म्हणतात, आणि सगळ्या मुलींना हे होतं.",
      en: "Between 10 and 15, your body changes a lot. This is called puberty, and every girl goes through it.",
      hi: "10–15 साल की उम्र में शरीर में बहुत बदलाव होते हैं। इसे किशोरावस्था कहते हैं, हर लड़की के साथ होता है।",
    },
    answer: [
      {
        mr: "उंची वाढते, छाती वाढते, काखेत आणि खाली केस येतात. हे नॉर्मल आहे.",
        en: "You grow taller, breasts develop, and hair grows under arms and below. This is normal.",
        hi: "लंबाई बढ़ती है, छाती बढ़ती है, बगल और नीचे बाल आते हैं। यह सामान्य है।",
      },
      {
        mr: "पिंपल्स, घाम आणि वास येणं वाढू शकतं. रोज अंघोळ आणि चेहरा धुणं मदत करतं.",
        en: "Pimples, sweat and body smell may increase. Daily bathing and face washing help.",
        hi: "मुंहासे, पसीना और बदबू बढ़ सकती है। रोज़ नहाना और चेहरा धोना मदद करता है।",
      },
      {
        mr: "थोडं पांढरं पाणी जाणं नॉर्मल आहे. खाज, वास किंवा रंग बदलला तर सांग.",
        en: "A little white discharge is normal. Tell an adult if there is itching, smell or colour change.",
        hi: "थोड़ा सफ़ेद पानी आना सामान्य है। खुजली, बदबू या रंग बदले तो बताओ।",
      },
      {
        mr: "प्रत्येकीचं शरीर वेगळ्या वेळी बदलतं. मैत्रिणीशी तुलना करू नकोस.",
        en: "Every body changes at its own time. Don't compare yourself with friends.",
        hi: "हर शरीर अपने समय पर बदलता है। सहेलियों से तुलना मत करो।",
      },
    ],
    next: {
      mr: "तुला कोणत्या बदलाबद्दल जास्त प्रश्न आहे?",
      en: "Which change do you have the most questions about?",
      hi: "तुम्हें किस बदलाव के बारे में सबसे ज़्यादा सवाल है?",
    },
  },
  {
    id: "g_hygiene",
    intent: "learn",
    ages: ["girl"],
    title: {
      mr: "पाळीत स्वच्छता",
      en: "Period hygiene",
      hi: "पीरियड में सफ़ाई",
    },
    keywords: [
      "hygiene",
      "pad change",
      "how often change pad",
      "pad kab badle",
      "pad disposal",
      "स्वच्छता",
      "pad बदलणं",
      "pad कुठे टाकायचा",
      "कापड धुणं",
      "सफ़ाई",
      "pad कब बदलें",
      "pad कहाँ फेंके",
      "कपड़ा धोना",
      "safai",
      "swachata",
      "itching",
      "खाज",
      "खुजली",
    ],
    understand: {
      mr: "पाळीत स्वच्छता ठेवली की infection होत नाही आणि तू fresh राहतेस.",
      en: "Keeping clean during periods prevents infections and keeps you feeling fresh.",
      hi: "पीरियड में सफ़ाई रखने से infection नहीं होता और तुम fresh रहती हो।",
    },
    answer: [
      {
        mr: "दर 4 ते 6 तासांनी pad बदल, रक्त कमी असलं तरी.",
        en: "Change your pad every 4 to 6 hours, even if bleeding is light.",
        hi: "हर 4 से 6 घंटे में pad बदलो, खून कम हो तब भी।",
      },
      {
        mr: "रोज अंघोळ कर. खालचा भाग फक्त साध्या पाण्याने पुढून मागे धू.",
        en: "Bathe daily. Wash your private area with plain water, from front to back.",
        hi: "रोज़ नहाओ। निजी अंग सिर्फ़ सादे पानी से, आगे से पीछे की ओर धोओ।",
      },
      {
        mr: "वापरलेला pad कागदात गुंडाळून कचरापेटीत टाक. Toilet मध्ये टाकू नकोस.",
        en: "Wrap the used pad in paper and put it in the dustbin. Never flush it.",
        hi: "इस्तेमाल किया pad कागज़ में लपेटकर कूड़ेदान में डालो। Toilet में मत डालो।",
      },
      {
        mr: "कापड वापरत असशील तर साबणाने धू आणि उन्हात पूर्ण वाळव.",
        en: "If you use cloth, wash it with soap and dry it fully in the sun.",
        hi: "कपड़ा इस्तेमाल करो तो साबुन से धोकर धूप में पूरा सुखाओ।",
      },
      {
        mr: "Pad बदलण्याआधी आणि नंतर हात साबणाने धू.",
        en: "Wash your hands with soap before and after changing a pad.",
        hi: "Pad बदलने से पहले और बाद में साबुन से हाथ धोओ।",
      },
    ],
    next: {
      mr: "शाळेत pad बदलायला जागा नसेल तर बाईंना सांगशील का?",
      en: "If there is no place to change at school, can you tell your teacher?",
      hi: "स्कूल में pad बदलने की जगह न हो तो क्या टीचर को बताओगी?",
    },
    actions: [
      {
        label: { mr: "सरकारी योजना बघ", en: "See government schemes", hi: "सरकारी योजनाएँ देखो" },
        href: "/schemes",
      },
    ],
  },
  {
    id: "g_nutrition",
    intent: "learn",
    ages: ["girl"],
    title: {
      mr: "मोठं होताना आहार",
      en: "Food for growing girls",
      hi: "बढ़ती लड़कियों का खाना",
    },
    keywords: [
      "nutrition",
      "what to eat",
      "iron",
      "calcium",
      "ifa tablet",
      "blue tablet",
      "anaemia",
      "anemia",
      "थकवा येतो",
      "काय खावं",
      "लोहाची गोळी",
      "निळी गोळी",
      "खून की कमी",
      "क्या खाएं",
      "आयरन की गोली",
      "thakan",
      "kamzori",
      "kay khau",
      "weakness",
    ],
    understand: {
      mr: "या वयात शरीर पटकन वाढतं, म्हणून चांगला आहार खूप गरजेचा आहे. खास करून लोह (iron) आणि calcium.",
      en: "Your body grows fast at this age, so good food matters a lot — especially iron and calcium.",
      hi: "इस उम्र में शरीर तेज़ी से बढ़ता है, इसलिए अच्छा खाना बहुत ज़रूरी है — ख़ासकर iron और calcium.",
    },
    answer: [
      {
        mr: "शाळेत मिळणारी निळी IFA गोळी आठवड्यातून एकदा, जेवणानंतर घे.",
        en: "Take the blue IFA tablet given at school once a week, after a meal.",
        hi: "स्कूल में मिलने वाली नीली IFA गोली हफ़्ते में एक बार, खाने के बाद लो।",
      },
      {
        mr: "लोहासाठी: पालेभाज्या, शेवगा, नाचणी, गूळ-शेंगदाणे, डाळी, मासे, अंडी.",
        en: "For iron: leafy greens, drumstick, nachni, jaggery-peanuts, dal, fish, eggs.",
        hi: "Iron के लिए: हरी सब्ज़ियाँ, सहजन, रागी, गुड़-मूंगफली, दाल, मछली, अंडे।",
      },
      {
        mr: "Calcium साठी: दूध, दही, ताक, नाचणी, तीळ, छोटे मासे.",
        en: "For calcium: milk, curd, buttermilk, nachni, sesame, small fish.",
        hi: "Calcium के लिए: दूध, दही, छाछ, रागी, तिल, छोटी मछली।",
      },
      {
        mr: "लिंबू, आवळा, पेरू खाल्ल्याने लोह चांगलं शोषलं जातं. जेवणासोबत चहा टाळ.",
        en: "Lemon, amla and guava help absorb iron. Avoid tea with meals.",
        hi: "नींबू, आंवला, अमरूद से iron अच्छे से मिलता है। खाने के साथ चाय मत पियो।",
      },
      {
        mr: "नेहमी थकवा, चक्कर किंवा चेहरा पांढरा दिसत असेल तर Anganwadi ताई किंवा डॉक्टरला सांग.",
        en: "If you always feel tired, dizzy or look pale, tell your Anganwadi tai or a doctor.",
        hi: "हमेशा थकान, चक्कर या चेहरा पीला लगे तो आंगनवाड़ी दीदी या डॉक्टर को बताओ।",
      },
    ],
    next: {
      mr: "या आठवड्यात शाळेतली IFA गोळी घेतलीस का?",
      en: "Did you take your school IFA tablet this week?",
      hi: "क्या इस हफ़्ते स्कूल की IFA गोली ली?",
    },
    actions: [
      {
        label: { mr: "मुलींसाठी योजना", en: "Schemes for girls", hi: "लड़कियों के लिए योजनाएँ" },
        href: "/schemes",
      },
    ],
  },
  {
    id: "g_body_image",
    intent: "learn",
    ages: ["girl"],
    title: {
      mr: "मला माझं रूप आवडत नाही",
      en: "I don't like how I look",
      hi: "मुझे अपना रूप पसंद नहीं",
    },
    keywords: [
      "i don't like how i look",
      "i am ugly",
      "fat",
      "too thin",
      "dark skin",
      "मी सुंदर नाही",
      "मी काळी आहे",
      "मी जाड आहे",
      "मी बारीक आहे",
      "मैं सुंदर नहीं",
      "मैं मोटी हूँ",
      "मैं काली हूँ",
      "main moti hoon",
      "mi jaad aahe",
      "body shaming",
      "रंग",
      "looks",
      "fair skin",
    ],
    understand: {
      mr: "कधी कधी आरशात पाहून वाईट वाटतं. असं वाटणं खूप मुलींना होतं — तू एकटी नाहीस.",
      en: "Sometimes looking in the mirror makes you feel bad. Many girls feel this — you are not alone.",
      hi: "कभी-कभी आईने में देखकर बुरा लगता है। बहुत लड़कियों को ऐसा लगता है — तुम अकेली नहीं हो।",
    },
    answer: [
      {
        mr: "सुंदरता एकाच रंगात किंवा आकारात नसते. प्रत्येक शरीर वेगळं आणि छान असतं.",
        en: "Beauty is not one colour or one size. Every body is different and good.",
        hi: "सुंदरता एक रंग या एक साइज़ में नहीं होती। हर शरीर अलग और अच्छा है।",
      },
      {
        mr: "Instagram वरचे फोटो filter केलेले असतात. ते खरे नसतात.",
        en: "Photos on Instagram are often filtered. They are not real life.",
        hi: "Instagram की photos अक्सर filter की होती हैं। वो असली नहीं होतीं।",
      },
      {
        mr: "जेवण टाळू नकोस किंवा गोरेपणाची cream लावू नकोस. शरीराला पोषण हवं.",
        en: "Don't skip meals or use fairness creams. Your growing body needs food.",
        hi: "खाना मत छोड़ो, गोरेपन की cream मत लगाओ। बढ़ते शरीर को पोषण चाहिए।",
      },
      {
        mr: "तुझ्यात काय छान आहे — हसू, हुशारी, दयाळूपणा — याची यादी कर.",
        en: "Make a list of what's great about you — your smile, your mind, your kindness.",
        hi: "तुम्हारे अंदर क्या अच्छा है — मुस्कान, समझ, दयालुता — उसकी list बनाओ।",
      },
      {
        mr: "कोणी तुझ्या रूपावरून चिडवत असेल तर मोठ्या माणसाला सांग.",
        en: "If someone teases you about your looks, tell a trusted adult.",
        hi: "कोई तुम्हारे रूप पर चिढ़ाए तो किसी भरोसेमंद बड़े को बताओ।",
      },
    ],
    next: {
      mr: "तुझ्याबद्दल तुला आवडणारी एक गोष्ट सांगशील?",
      en: "Can you tell me one thing you like about yourself?",
      hi: "क्या अपने बारे में एक अच्छी बात बताओगी?",
    },
  },
  {
    id: "g_emotions",
    intent: "learn",
    ages: ["girl"],
    title: {
      mr: "मूड पटकन बदलतो",
      en: "Mood swings",
      hi: "मूड जल्दी बदलता है",
    },
    keywords: [
      "mood swings",
      "angry all the time",
      "crying for no reason",
      "irritated",
      "राग येतो",
      "रडू येतं",
      "चिडचिड",
      "मूड बदलतो",
      "गुस्सा आता है",
      "रोना आता है",
      "चिड़चिड़ापन",
      "mood kharab",
      "gussa aata hai",
      "rag yeto",
      "radu yeta",
      "emotional",
    ],
    understand: {
      mr: "या वयात शरीरातले hormones बदलतात, त्यामुळे पटकन राग, रडू किंवा चिडचिड होऊ शकते. हे नॉर्मल आहे.",
      en: "Hormones change at this age, so you may feel angry, weepy or irritated quickly. This is normal.",
      hi: "इस उम्र में hormones बदलते हैं, इसलिए जल्दी गुस्सा, रोना या चिड़चिड़ापन हो सकता है। यह सामान्य है।",
    },
    answer: [
      {
        mr: "राग आल्यावर 5 मोठे श्वास घे आणि मग बोल.",
        en: "When angry, take 5 slow deep breaths before you speak.",
        hi: "गुस्सा आए तो बोलने से पहले 5 गहरी साँसें लो।",
      },
      {
        mr: "मनातलं वहीत लिही, चित्र काढ किंवा बाहेर फिरून ये.",
        en: "Write your feelings in a notebook, draw, or go for a short walk.",
        hi: "मन की बात डायरी में लिखो, चित्र बनाओ या थोड़ा घूम आओ।",
      },
      {
        mr: "पुरेशी झोप (8–9 तास) आणि वेळेवर जेवण मूड चांगला ठेवतं.",
        en: "Enough sleep (8–9 hours) and regular meals help your mood.",
        hi: "पूरी नींद (8–9 घंटे) और समय पर खाना मूड ठीक रखते हैं।",
      },
      {
        mr: "विश्वासाच्या माणसाशी बोल. मन हलकं होतं.",
        en: "Talk to someone you trust. It makes your heart lighter.",
        hi: "किसी भरोसेमंद से बात करो। मन हल्का होता है।",
      },
      {
        mr: "खूप दिवस सतत उदास वाटत असेल तर मदत घेणं गरजेचं आहे.",
        en: "If you feel sad for many days in a row, it's important to get help.",
        hi: "अगर कई दिनों तक लगातार उदासी रहे तो मदद लेना ज़रूरी है।",
      },
    ],
    next: {
      mr: "आज तुला कसं वाटतंय — राग, दुःख की गोंधळ?",
      en: "How are you feeling today — angry, sad or confused?",
      hi: "आज कैसा लग रहा है — गुस्सा, उदासी या उलझन?",
    },
  },

  // ───────────────────── PERSONAL BOUNDARIES ─────────────────────
  {
    id: "g_touch",
    intent: "learn",
    ages: ["girl"],
    sensitive: "child",
    title: {
      mr: "चांगला स्पर्श, वाईट स्पर्श",
      en: "Safe and unsafe touch",
      hi: "अच्छा और बुरा स्पर्श",
    },
    keywords: [
      "good touch bad touch",
      "safe touch",
      "unsafe touch",
      "private parts",
      "चांगला स्पर्श",
      "वाईट स्पर्श",
      "गुड टच बॅड टच",
      "अच्छा स्पर्श",
      "बुरा स्पर्श",
      "गुड टच बैड टच",
      "गंदा स्पर्श",
      "good touch",
      "bad touch",
      "ganda touch",
      "chuna",
      "sparsh",
      "body safety",
    ],
    understand: {
      mr: "तुझं शरीर फक्त तुझं आहे. कोणता स्पर्श ठीक आहे आणि कोणता नाही, हे ओळखणं महत्त्वाचं आहे.",
      en: "Your body belongs to you. It's important to know which touch is okay and which is not.",
      hi: "तुम्हारा शरीर सिर्फ़ तुम्हारा है। कौन-सा स्पर्श ठीक है और कौन-सा नहीं, यह समझना ज़रूरी है।",
    },
    answer: [
      {
        mr: "चांगला स्पर्श सुरक्षित वाटतो — आईची मिठी, मैत्रिणीचा high-five.",
        en: "A safe touch feels good and safe — a hug from mum, a high-five from a friend.",
        hi: "अच्छा स्पर्श सुरक्षित लगता है — माँ की झप्पी, सहेली का high-five.",
      },
      {
        mr: "Swimsuit ने झाकलेले भाग खाजगी आहेत. कोणीही त्यांना हात लावू नये, पाहू नये.",
        en: "Parts covered by a swimsuit are private. No one should touch or look at them.",
        hi: "Swimsuit से ढके अंग निजी हैं। कोई उन्हें छू या देख नहीं सकता।",
      },
      {
        mr: "डॉक्टर तपासताना आई किंवा विश्वासाचं माणूस सोबत असावं.",
        en: "A doctor may check you only with your parent or trusted adult present.",
        hi: "डॉक्टर जाँच करे तो माँ या कोई भरोसेमंद बड़ा साथ होना चाहिए।",
      },
      {
        mr: "जो स्पर्श विचित्र, घाबरवणारा किंवा वाईट वाटतो तो ठीक नाही — ओळखीच्या माणसाचा असला तरी.",
        en: "Any touch that feels strange, scary or bad is not okay — even from someone you know.",
        hi: "जो स्पर्श अजीब, डरावना या बुरा लगे वो ठीक नहीं — चाहे जान-पहचान वाला हो।",
      },
      {
        mr: "असं झालं तर ती तुझी चूक नाही. लगेच विश्वासाच्या मोठ्या माणसाला सांग.",
        en: "If it happens, it is never your fault. Tell a trusted adult right away.",
        hi: "ऐसा हो तो यह कभी तुम्हारी गलती नहीं। तुरंत भरोसेमंद बड़े को बताओ।",
      },
    ],
    next: {
      mr: "कोणी तुला असा स्पर्श केलाय का? तू मला सांगू शकतेस.",
      en: "Has anyone touched you in a way that felt bad? You can tell me.",
      hi: "क्या किसी ने तुम्हें ऐसे छुआ जो बुरा लगा? तुम मुझे बता सकती हो।",
    },
    actions: [
      {
        label: { mr: "1098 — मुलांची मदत", en: "Call 1098 Childline", hi: "1098 — Childline" },
        href: "tel:1098",
      },
    ],
    girlNote: {
      mr: "विश्वासाच्या मोठ्या माणसाला सांग. 1098 वर फोन कर — मोफत, 24 तास.",
      en: "Tell a trusted adult. Call 1098 — free, 24 hours.",
      hi: "किसी भरोसेमंद बड़े को बताओ। 1098 पर फ़ोन करो — मुफ़्त, 24 घंटे।",
    },
  },
  {
    id: "g_say_no",
    intent: "learn",
    ages: ["girl"],
    sensitive: "child",
    title: {
      mr: "नाही कसं म्हणायचं",
      en: "How to say no",
      hi: "ना कैसे कहें",
    },
    keywords: [
      "how to say no",
      "say no",
      "refuse",
      "नाही म्हणायचं",
      "नाही कसं म्हणू",
      "मला नको",
      "ना कैसे कहूँ",
      "मना करना",
      "मुझे नहीं चाहिए",
      "na kaise kahu",
      "nahi kasa mhanu",
      "scared to say no",
      "भीती वाटते",
      "डर लगता है",
      "no go tell",
    ],
    understand: {
      mr: "कोणी तुला नको असलेलं काही करायला लावत असेल, तर नाही म्हणण्याचा तुला पूर्ण हक्क आहे — मोठ्या माणसाला सुद्धा.",
      en: "If someone wants you to do something you don't want, you have every right to say no — even to an adult.",
      hi: "अगर कोई तुमसे ऐसा कुछ करवाना चाहे जो तुम्हें नहीं चाहिए, तो ना कहने का पूरा हक़ है — बड़ों को भी।",
    },
    answer: [
      {
        mr: "मोठ्याने आणि स्पष्ट बोल: नाही! मला हे नको!",
        en: "Say it loud and clear: NO! I don't want this!",
        hi: "ज़ोर से और साफ़ बोलो: नहीं! मुझे यह नहीं चाहिए!",
      },
      {
        mr: "लगेच तिथून निघून जा. लोक असलेल्या जागी जा.",
        en: "Walk away quickly. Go to a place where there are people.",
        hi: "तुरंत वहाँ से चली जाओ। जहाँ लोग हों वहाँ जाओ।",
      },
      {
        mr: "विश्वासाच्या मोठ्या माणसाला सांग — आजच.",
        en: "Tell a trusted adult — today.",
        hi: "किसी भरोसेमंद बड़े को बताओ — आज ही।",
      },
      {
        mr: "नाही म्हटल्याने तू वाईट किंवा उद्धट होत नाहीस. तू स्वतःला सुरक्षित ठेवतेस.",
        en: "Saying no does not make you rude or bad. It keeps you safe.",
        hi: "ना कहने से तुम बुरी या बदतमीज़ नहीं बनती। तुम खुद को सुरक्षित रखती हो।",
      },
      {
        mr: "घाबरून नाही म्हणता आलं नाही तरी ती तुझी चूक नाही.",
        en: "If you froze and couldn't say no, it's still not your fault.",
        hi: "डर से ना न कह पाई, तब भी यह तुम्हारी गलती नहीं।",
      },
    ],
    next: {
      mr: "आरशासमोर एकदा मोठ्याने नाही! म्हणून सराव करशील?",
      en: "Will you practise saying NO! loudly once in front of a mirror?",
      hi: "क्या आईने के सामने एक बार ज़ोर से नहीं! बोलकर practice करोगी?",
    },
    actions: [
      {
        label: { mr: "1098 — मुलांची मदत", en: "Call 1098 Childline", hi: "1098 — Childline" },
        href: "tel:1098",
      },
    ],
  },
  {
    id: "g_trusted_adults",
    intent: "connect",
    ages: ["girl"],
    sensitive: "child",
    title: {
      mr: "माझी विश्वासाची माणसं",
      en: "My trusted adults",
      hi: "मेरे भरोसेमंद लोग",
    },
    keywords: [
      "trusted adult",
      "who to tell",
      "who can i talk to",
      "कोणाला सांगू",
      "कोणाशी बोलू",
      "विश्वासाचं माणूस",
      "किसको बताऊँ",
      "किससे बात करूँ",
      "भरोसेमंद",
      "kisko batau",
      "konala sangu",
      "no one to talk",
      "safe adult",
      "anganwadi tai",
      "teacher ko batau",
    ],
    understand: {
      mr: "अडचण आली की लगेच कोणाला सांगायचं हे आधीच ठरवलेलं असलं की खूप सोपं जातं.",
      en: "It's much easier in a tough moment if you already know who you can tell.",
      hi: "मुश्किल में किसे बताना है, यह पहले से पता हो तो बहुत आसान हो जाता है।",
    },
    answer: [
      {
        mr: "5 विश्वासाच्या मोठ्या माणसांची यादी कर: आई/बाबा, बाई, मावशी/आत्या, Anganwadi ताई, शेजारची काकू.",
        en: "List 5 trusted adults: parent, teacher, aunt, Anganwadi tai, a kind neighbour.",
        hi: "5 भरोसेमंद बड़ों की list बनाओ: माँ/पापा, टीचर, मौसी/बुआ, आंगनवाड़ी दीदी, पड़ोसन।",
      },
      {
        mr: "विश्वासाचं माणूस म्हणजे जे ऐकतं, रागावत नाही आणि मदत करतं.",
        en: "A trusted adult listens, doesn't get angry at you, and helps.",
        hi: "भरोसेमंद वो है जो सुने, तुम पर गुस्सा न करे और मदद करे।",
      },
      {
        mr: "एकाने ऐकलं नाही तर यादीतल्या पुढच्या माणसाला सांग. थांबू नकोस.",
        en: "If one person doesn't listen, tell the next person on your list. Don't stop.",
        hi: "एक न सुने तो list में अगले को बताओ। रुको मत।",
      },
      {
        mr: "यादी आणि 1098 नंबर वहीत किंवा bag मध्ये लिहून ठेव.",
        en: "Write the list and the number 1098 in your notebook or bag.",
        hi: "List और 1098 नंबर अपनी कॉपी या bag में लिखकर रखो।",
      },
    ],
    next: {
      mr: "तुझ्या यादीतलं पहिलं नाव कोणाचं असेल?",
      en: "Whose name will be first on your list?",
      hi: "तुम्हारी list में पहला नाम किसका होगा?",
    },
    actions: [
      {
        label: { mr: "1098 — मुलांची मदत", en: "Call 1098 Childline", hi: "1098 — Childline" },
        href: "tel:1098",
      },
    ],
  },
  {
    id: "g_uncomfortable",
    intent: "act",
    ages: ["girl"],
    sensitive: "child",
    emergency: true,
    title: {
      mr: "कोणी मला अस्वस्थ करतं",
      en: "Someone makes me uncomfortable",
      hi: "कोई मुझे असहज करता है",
    },
    keywords: [
      "someone touched me",
      "uncomfortable",
      "keep a secret",
      "कोणी मला हात लावला",
      "secret ठेव म्हणतो",
      "कोणाला सांगू नको म्हणतो",
      "काका",
      "मामा",
      "uncle",
      "koi chhuta hai",
      "kisi ne chhua",
      "किसी ने छुआ",
      "गलत जगह छुआ",
      "किसी को मत बताना बोला",
      "मुझे डर लगता है",
      "मला भीती वाटते",
      "teacher touches",
      "sir touches",
      "cousin",
      "bad touch",
    ],
    understand: {
      mr: "तू मला हे सांगितलंस, हे खूप धाडसाचं आहे. जे झालं ती तुझी चूक नाही, आणि सांगितल्याबद्दल तुला ओरडा बसणार नाही.",
      en: "You were very brave to tell me. What happened is not your fault, and you won't get into trouble for telling.",
      hi: "तुमने बताया, यह बहुत हिम्मत की बात है। जो हुआ वो तुम्हारी गलती नहीं, और बताने पर तुम्हें डाँट नहीं पड़ेगी।",
    },
    answer: [
      {
        mr: "आत्ता धोका असेल तर लगेच 112 ला फोन कर किंवा मोठ्याने ओरडून लोकांकडे पळ.",
        en: "If you are in danger right now, call 112 or shout and run to people.",
        hi: "अभी ख़तरा हो तो तुरंत 112 पर फ़ोन करो या चिल्लाकर लोगों के पास भागो।",
      },
      {
        mr: "आजच विश्वासाच्या मोठ्या माणसाला सांग — आई, बाई, Anganwadi ताई.",
        en: "Tell a trusted adult today — your mother, a teacher, your Anganwadi tai.",
        hi: "आज ही किसी भरोसेमंद बड़े को बताओ — माँ, टीचर, आंगनवाड़ी दीदी।",
      },
      {
        mr: "1098 वर फोन कर. हा फोन मोफत आहे, 24 तास चालू असतो.",
        en: "Call 1098. It is free and works 24 hours, every day.",
        hi: "1098 पर फ़ोन करो। यह मुफ़्त है और 24 घंटे चालू रहता है।",
      },
      {
        mr: "स्पर्शाबद्दलचं सिक्रेट कधीच ठेवायचं नसतं — कोणीही सांगितलं तरी.",
        en: "Secrets about touching must never be kept — no matter who asks.",
        hi: "छूने से जुड़ा secret कभी नहीं रखना — चाहे कोई भी कहे।",
      },
      {
        mr: "त्या माणसासोबत एकटी राहू नकोस. तो ओळखीचा, नातेवाईक असला तरी.",
        en: "Don't stay alone with that person, even if they are family or someone you know.",
        hi: "उस इंसान के साथ अकेली मत रहो, चाहे वो रिश्तेदार या जान-पहचान वाला हो।",
      },
    ],
    next: {
      mr: "आज तू कोणाला सांगशील? नाही जमलं तर आत्ता 1098 ला फोन करूया.",
      en: "Who will you tell today? If you can't, let's call 1098 now.",
      hi: "आज तुम किसे बताओगी? न बता पाओ तो अभी 1098 पर फ़ोन करें।",
    },
    actions: [
      {
        label: { mr: "1098 — मुलांची मदत", en: "Call 1098 Childline", hi: "1098 — Childline" },
        href: "tel:1098",
      },
      {
        label: { mr: "धोका आहे — 112", en: "In danger — call 112", hi: "ख़तरा है — 112" },
        href: "tel:112",
      },
    ],
    girlNote: {
      mr: "तू एकटी नाहीस. तुझ्यावर विश्वास ठेवणारे लोक आहेत.",
      en: "You are not alone. There are people who will believe you.",
      hi: "तुम अकेली नहीं हो। ऐसे लोग हैं जो तुम पर भरोसा करेंगे।",
    },
  },

  // ───────────────────── SCHOOL & SOCIAL LIFE ─────────────────────
  {
    id: "g_bullying",
    intent: "act",
    ages: ["girl"],
    title: {
      mr: "शाळेत मला चिडवतात",
      en: "Bullying at school",
      hi: "स्कूल में मुझे चिढ़ाते हैं",
    },
    keywords: [
      "bullying",
      "bully",
      "they tease me",
      "मला चिडवतात",
      "मला त्रास देतात",
      "मारतात",
      "नावं ठेवतात",
      "मुझे चिढ़ाते हैं",
      "मुझे परेशान करते हैं",
      "मारते हैं",
      "mujhe chidhate hain",
      "mala chidavtat",
      "no one plays with me",
      "कोणी खेळत नाही",
      "अकेली छोड़ देते हैं",
      "ragging",
    ],
    understand: {
      mr: "कोणी वारंवार चिडवत, मारत किंवा एकटं पाडत असेल तर त्याला bullying म्हणतात. ती तुझी चूक नाही.",
      en: "If someone keeps teasing, hitting or leaving you out, that is bullying. It is not your fault.",
      hi: "अगर कोई बार-बार चिढ़ाए, मारे या अकेला छोड़े तो यह bullying है। यह तुम्हारी गलती नहीं।",
    },
    answer: [
      {
        mr: "शांतपणे बोल: थांब, मला हे आवडत नाही. आणि तिथून निघून जा.",
        en: "Say calmly: Stop, I don't like this. Then walk away.",
        hi: "शांति से बोलो: बस करो, मुझे यह पसंद नहीं। फिर वहाँ से चली जाओ।",
      },
      {
        mr: "मैत्रिणींसोबत राहा. एकटी असताना जास्त त्रास होतो.",
        en: "Stay with friends. Bullies pick on girls who are alone.",
        hi: "सहेलियों के साथ रहो। अकेले होने पर ज़्यादा परेशान करते हैं।",
      },
      {
        mr: "वर्गशिक्षक, मुख्याध्यापक आणि घरी सांग. सांगणं म्हणजे चुगली नाही.",
        en: "Tell your class teacher, principal and family. Telling is not tattling.",
        hi: "क्लास टीचर, प्रिंसिपल और घर पर बताओ। बताना चुगली नहीं है।",
      },
      {
        mr: "काय, कधी, कोणी केलं हे वहीत लिहून ठेव.",
        en: "Write down what happened, when, and who did it.",
        hi: "क्या हुआ, कब, किसने किया — डायरी में लिखो।",
      },
    ],
    next: {
      mr: "शाळेत कोणत्या बाईंना तू हे सांगू शकतेस?",
      en: "Which teacher at school could you tell about this?",
      hi: "स्कूल में किस टीचर को यह बता सकती हो?",
    },
    actions: [
      {
        label: { mr: "1098 — मुलांची मदत", en: "Call 1098 Childline", hi: "1098 — Childline" },
        href: "tel:1098",
      },
    ],
  },
  {
    id: "g_peer_pressure",
    intent: "learn",
    ages: ["girl"],
    title: {
      mr: "मित्रमैत्रिणींचा दबाव",
      en: "Peer pressure",
      hi: "दोस्तों का दबाव",
    },
    keywords: [
      "peer pressure",
      "friends forcing me",
      "friends pressure",
      "मैत्रिणी जबरदस्ती करतात",
      "मित्र म्हणतात कर",
      "सगळे करतात",
      "दोस्त ज़बरदस्ती करते हैं",
      "सब करते हैं",
      "dost force karte",
      "sab karte hain",
      "bunk school",
      "गुटखा",
      "smoking",
      "drinks",
      "left out",
    ],
    understand: {
      mr: "मित्र-मैत्रिणींमध्ये मिसळायचं असतं, म्हणून कधी कधी नको असलेल्या गोष्टी कराव्याशा वाटतात. याला दबाव म्हणतात.",
      en: "Wanting to fit in can make you feel you must do things you don't want. That's peer pressure.",
      hi: "दोस्तों में घुलना-मिलना चाहती हो, इसलिए कभी न चाहते हुए भी कुछ करने का मन होता है। यह दबाव है।",
    },
    answer: [
      {
        mr: "खरे मित्र तुझ्या नाही चा आदर करतात.",
        en: "Real friends respect your no.",
        hi: "सच्चे दोस्त तुम्हारी ना का सम्मान करते हैं।",
      },
      {
        mr: "सोपं उत्तर तयार ठेव: नको, मला नाही जमणार. आणि विषय बदल.",
        en: "Keep an easy line ready: No, I'm not doing that. Then change the topic.",
        hi: "आसान जवाब तैयार रखो: नहीं, मुझे नहीं करना। फिर बात बदलो।",
      },
      {
        mr: "तुझ्यासारखा विचार करणारी एक मैत्रीण शोध. दोघी मिळून नाही म्हणणं सोपं.",
        en: "Find one friend who thinks like you. Saying no together is easier.",
        hi: "अपने जैसी सोच वाली एक सहेली ढूँढो। साथ में ना कहना आसान है।",
      },
      {
        mr: "नशा, शाळा बुडवणं, फोटो पाठवणं — असं काही सांगितलं तर मोठ्या माणसाला सांग.",
        en: "If pushed to try nasha, skip school or send photos, tell a trusted adult.",
        hi: "नशा, स्कूल छोड़ना, फ़ोटो भेजना — ऐसा कहा जाए तो किसी बड़े को बताओ।",
      },
    ],
    next: {
      mr: "तुझ्यावर कोणत्या गोष्टीसाठी दबाव येतोय?",
      en: "What are you being pressured to do?",
      hi: "तुम पर किस बात का दबाव है?",
    },
  },
  {
    id: "g_school_anxiety",
    intent: "learn",
    ages: ["girl"],
    title: {
      mr: "परीक्षेची भीती",
      en: "Exam & school stress",
      hi: "परीक्षा का डर",
    },
    keywords: [
      "exam stress",
      "exam fear",
      "board exam",
      "results",
      "परीक्षेची भीती",
      "अभ्यास होत नाही",
      "टेन्शन",
      "मार्क्स कमी",
      "परीक्षा का डर",
      "पढ़ाई नहीं होती",
      "नंबर कम",
      "exam ka dar",
      "tension",
      "fail honar",
      "fail ho jaungi",
      "10th",
      "12th",
    ],
    understand: {
      mr: "परीक्षेच्या आधी भीती वाटणं खूप सामान्य आहे. थोडं टेन्शन अभ्यासाला मदत करतं, पण जास्त झालं तर त्रास होतो.",
      en: "Feeling scared before exams is very common. A little stress helps, but too much can hurt.",
      hi: "परीक्षा से पहले डर लगना बहुत आम है। थोड़ा tension मदद करता है, पर ज़्यादा हो तो नुकसान करता है।",
    },
    answer: [
      {
        mr: "अभ्यास छोट्या भागांत कर: 25 मिनिटं अभ्यास, 5 मिनिटं विश्रांती.",
        en: "Study in small parts: 25 minutes study, 5 minutes break.",
        hi: "छोटे हिस्सों में पढ़ो: 25 मिनट पढ़ाई, 5 मिनट आराम।",
      },
      {
        mr: "रात्री पूर्ण झोप घे. जागरणाने लक्षात राहत नाही.",
        en: "Sleep fully at night. Staying up late makes you forget.",
        hi: "रात को पूरी नींद लो। जागने से याद नहीं रहता।",
      },
      {
        mr: "घाबरल्यावर: 4 मोजत श्वास घे, 4 मोजत सोड. असं 5 वेळा कर.",
        en: "When nervous: breathe in for 4, out for 4. Do it 5 times.",
        hi: "घबराहट हो तो: 4 गिनकर साँस लो, 4 गिनकर छोड़ो। 5 बार करो।",
      },
      {
        mr: "मार्क्स म्हणजे तुझी किंमत नाही. बाईंना किंवा घरी मदत माग.",
        en: "Your marks are not your worth. Ask your teacher or family for help.",
        hi: "नंबर तुम्हारी कीमत नहीं हैं। टीचर या घरवालों से मदद माँगो।",
      },
      {
        mr: "टेन्शनमुळे स्वतःला इजा करावीशी वाटली तर लगेच 14416 ला फोन कर.",
        en: "If stress makes you want to hurt yourself, call 14416 right away.",
        hi: "Tension से खुद को नुकसान पहुँचाने का मन हो तो तुरंत 14416 पर फ़ोन करो।",
      },
    ],
    next: {
      mr: "कोणता विषय तुला सगळ्यात जास्त टेन्शन देतो?",
      en: "Which subject worries you the most?",
      hi: "कौन-सा विषय तुम्हें सबसे ज़्यादा tension देता है?",
    },
    actions: [
      {
        label: { mr: "Tele-MANAS 14416", en: "Tele-MANAS 14416", hi: "Tele-MANAS 14416" },
        href: "tel:14416",
      },
    ],
  },
  {
    id: "g_relationships",
    intent: "learn",
    ages: ["girl"],
    title: {
      mr: "Crush आणि नाती",
      en: "Crushes & relationships",
      hi: "Crush और रिश्ते",
    },
    keywords: [
      "crush",
      "boyfriend",
      "i like a boy",
      "love",
      "मला एक मुलगा आवडतो",
      "प्रेम",
      "मुलगा मागे लागतो",
      "मुझे एक लड़का पसंद है",
      "प्यार",
      "लड़का पीछे पड़ा है",
      "bf",
      "pyaar",
      "mala aavadto",
      "photo maangta hai",
      "फोटो मागतो",
      "फ़ोटो माँगता है",
      "propose",
    ],
    understand: {
      mr: "या वयात कोणी आवडणं अगदी नैसर्गिक आहे. महत्त्वाचं म्हणजे तू सुरक्षित आणि आदराने वागवली जातेस का.",
      en: "Liking someone at this age is very natural. What matters is that you feel safe and respected.",
      hi: "इस उम्र में कोई पसंद आना बिल्कुल स्वाभाविक है। ज़रूरी यह है कि तुम सुरक्षित और सम्मानित महसूस करो।",
    },
    answer: [
      {
        mr: "चांगलं नातं: आदर, विश्वास, तुझ्या नाही चा मान, मित्र-घरच्यांपासून दूर न करणं.",
        en: "Healthy: respect, trust, accepting your no, not pulling you away from friends or family.",
        hi: "अच्छा रिश्ता: सम्मान, भरोसा, तुम्हारी ना मानना, दोस्तों-घर से दूर न करना।",
      },
      {
        mr: "वाईट नातं: धमकी, संशय, फोन तपासणं, भेटायला जबरदस्ती, सगळं सिक्रेट ठेवायला सांगणं.",
        en: "Unhealthy: threats, jealousy, checking your phone, forcing to meet, demanding secrecy.",
        hi: "बुरा रिश्ता: धमकी, शक, फ़ोन चेक करना, मिलने की ज़बरदस्ती, सब secret रखने को कहना।",
      },
      {
        mr: "कोणालाही तुझे फोटो पाठवू नकोस — कितीही विश्वास असला तरी.",
        en: "Never send your photos to anyone — no matter how much you trust them.",
        hi: "किसी को अपनी photos मत भेजो — चाहे कितना भी भरोसा हो।",
      },
      {
        mr: "कोणी दबाव आणत असेल तर नाही म्हण आणि विश्वासाच्या मोठ्या माणसाला सांग.",
        en: "If anyone pressures you, say no and tell a trusted adult.",
        hi: "कोई दबाव डाले तो ना कहो और किसी भरोसेमंद बड़े को बताओ।",
      },
    ],
    next: {
      mr: "हे नातं तुला सुरक्षित आणि आनंदी वाटतं का?",
      en: "Does this relationship make you feel safe and happy?",
      hi: "क्या यह रिश्ता तुम्हें सुरक्षित और ख़ुश महसूस कराता है?",
    },
    actions: [
      {
        label: { mr: "1098 — मुलांची मदत", en: "Call 1098 Childline", hi: "1098 — Childline" },
        href: "tel:1098",
      },
    ],
  },
  {
    id: "g_social_media_pressure",
    intent: "learn",
    ages: ["girl"],
    title: {
      mr: "Social media चा दबाव",
      en: "Social media pressure",
      hi: "Social media का दबाव",
    },
    keywords: [
      "social media pressure",
      "instagram",
      "reels",
      "likes",
      "followers",
      "comparison",
      "likes कमी",
      "सगळ्या सुंदर दिसतात",
      "फोन सोडवत नाही",
      "likes कम आते",
      "सब अच्छी दिखती हैं",
      "phone ki aadat",
      "reels addiction",
      "compare",
      "snapchat",
      "youtube",
    ],
    understand: {
      mr: "Instagram वर इतरांचं आयुष्य perfect दिसतं, आणि स्वतःबद्दल वाईट वाटू लागतं. हे खूप जणींना होतं.",
      en: "Others' lives look perfect on Instagram, and you start feeling bad about yourself. Many girls feel this.",
      hi: "Instagram पर दूसरों की ज़िंदगी perfect दिखती है, और खुद के बारे में बुरा लगने लगता है। यह बहुतों को होता है।",
    },
    answer: [
      {
        mr: "लोक फक्त चांगले क्षण टाकतात. पडद्यामागचं खरं आयुष्य दिसत नाही.",
        en: "People only post their best moments. You don't see their real life.",
        hi: "लोग सिर्फ़ अच्छे पल डालते हैं। असली ज़िंदगी दिखती नहीं।",
      },
      {
        mr: "Likes आणि followers म्हणजे तुझी किंमत नाही.",
        en: "Likes and followers do not decide your worth.",
        hi: "Likes और followers तुम्हारी कीमत तय नहीं करते।",
      },
      {
        mr: "ज्यामुळे वाईट वाटतं अशी accounts unfollow किंवा mute कर.",
        en: "Unfollow or mute accounts that make you feel bad.",
        hi: "जो accounts बुरा महसूस कराएँ उन्हें unfollow या mute करो।",
      },
      {
        mr: "झोपायच्या 1 तास आधी फोन बाजूला ठेव. मैदानी खेळ खेळ.",
        en: "Keep your phone away 1 hour before sleep. Play outdoors.",
        hi: "सोने से 1 घंटा पहले फ़ोन दूर रखो। बाहर खेलो।",
      },
      {
        mr: "तुझं account private ठेव. अनोळखी लोकांना follow request accept करू नकोस.",
        en: "Keep your account private. Don't accept requests from strangers.",
        hi: "अपना account private रखो। अनजान लोगों की request accept मत करो।",
      },
    ],
    next: {
      mr: "आज फोनशिवाय तुला आवडणारी एक गोष्ट करशील का?",
      en: "Will you do one thing you love today without your phone?",
      hi: "क्या आज फ़ोन के बिना अपनी पसंद का एक काम करोगी?",
    },
  },

  // ───────────────────────── DIGITAL SAFETY ─────────────────────────
  {
    id: "g_fake_profiles",
    intent: "check",
    ages: ["girl"],
    title: {
      mr: "Fake profile आणि अनोळखी लोक",
      en: "Fake profiles & strangers online",
      hi: "Fake profile और अनजान लोग",
    },
    keywords: [
      "fake profile",
      "fake id",
      "stranger messaging me",
      "unknown number",
      "friend request",
      "अनोळखी मेसेज करतो",
      "अनोळखी नंबर",
      "fake account",
      "अनजान मैसेज करता है",
      "अनजान नंबर",
      "unknown se message",
      "anolkhi message",
      "wants to meet",
      "भेटायला बोलावतो",
      "मिलने बुलाता है",
      "online friend",
    ],
    understand: {
      mr: "Online कोणीही खोटं नाव आणि फोटो वापरू शकतो. तुझ्या वयाचा दिसणारा माणूस खरं तर मोठा असू शकतो.",
      en: "Anyone online can use a fake name and photo. Someone who looks your age may really be an adult.",
      hi: "Online कोई भी झूठा नाम और photo लगा सकता है। तुम्हारी उम्र का दिखने वाला असल में बड़ा आदमी हो सकता है।",
    },
    answer: [
      {
        mr: "ओळखीचे नसलेल्यांची request accept करू नकोस.",
        en: "Don't accept requests from people you don't know in real life.",
        hi: "जिन्हें असल में नहीं जानती उनकी request accept मत करो।",
      },
      {
        mr: "पत्ता, शाळा, फोन नंबर, photos कधीच शेअर करू नकोस.",
        en: "Never share your address, school, phone number or photos.",
        hi: "पता, स्कूल, फ़ोन नंबर, photos कभी share मत करो।",
      },
      {
        mr: "Online भेटलेल्या माणसाला एकटी भेटायला जाऊ नकोस.",
        en: "Never go alone to meet someone you met online.",
        hi: "Online मिले किसी से अकेले मिलने मत जाओ।",
      },
      {
        mr: "Block आणि report कर. Chat चा screenshot घे आणि मोठ्या माणसाला दाखव.",
        en: "Block and report. Take a screenshot and show a trusted adult.",
        hi: "Block और report करो। Screenshot लेकर किसी बड़े को दिखाओ।",
      },
    ],
    next: {
      mr: "हा माणूस तुझ्याकडे काही मागतोय का — फोटो, भेट, पैसे?",
      en: "Is this person asking you for anything — photos, a meeting, money?",
      hi: "क्या यह इंसान तुमसे कुछ माँग रहा है — photo, मिलना, पैसे?",
    },
    actions: [
      {
        label: { mr: "सायबर मदत 1930", en: "Cyber helpline 1930", hi: "साइबर हेल्पलाइन 1930" },
        href: "tel:1930",
      },
      {
        label: { mr: "1098 — मुलांची मदत", en: "Call 1098 Childline", hi: "1098 — Childline" },
        href: "tel:1098",
      },
    ],
  },
  {
    id: "g_image_misuse",
    intent: "act",
    ages: ["girl"],
    sensitive: "child",
    emergency: true,
    title: {
      mr: "कोणाकडे माझा फोटो आहे",
      en: "Someone has my photo",
      hi: "किसी के पास मेरी photo है",
    },
    keywords: [
      "someone has my photo",
      "threatening to share my photo",
      "photo viral karega",
      "morphed photo",
      "sextortion",
      "blackmail",
      "माझा फोटो",
      "फोटो viral करेन म्हणतो",
      "फोटो पाठव नाहीतर",
      "धमकी देतो",
      "मेरी photo",
      "photo viral कर देगा",
      "धमकी दे रहा है",
      "पैसे मागतो",
      "पैसे माँग रहा है",
      "meri photo hai",
      "maza photo",
      "video call record",
      "nude",
    ],
    understand: {
      mr: "कोणी तुझ्या फोटोवरून धमकी देत असेल तर खूप भीती वाटणं साहजिक आहे. ही तुझी चूक नाही — चूक धमकी देणाऱ्याची आहे.",
      en: "It's natural to feel very scared if someone threatens you with your photo. It's not your fault — the person threatening you is wrong.",
      hi: "कोई तुम्हारी photo से धमकाए तो बहुत डर लगना स्वाभाविक है। यह तुम्हारी गलती नहीं — गलती धमकाने वाले की है।",
    },
    answer: [
      {
        mr: "आत्ताच विश्वासाच्या मोठ्या माणसाला सांग. तुला ओरडा बसणार नाही.",
        en: "Tell a trusted adult right now. You won't get into trouble.",
        hi: "अभी किसी भरोसेमंद बड़े को बताओ। तुम्हें डाँट नहीं पड़ेगी।",
      },
      {
        mr: "पैसे देऊ नकोस आणि आणखी फोटो पाठवू नकोस. त्याने धमकी थांबत नाही.",
        en: "Don't pay and don't send more photos. It won't stop the threats.",
        hi: "पैसे मत दो और और photos मत भेजो। इससे धमकी रुकती नहीं।",
      },
      {
        mr: "Chat, नंबर, profile चे screenshots घे. Chat delete करू नकोस.",
        en: "Take screenshots of the chat, number and profile. Don't delete the chat.",
        hi: "Chat, नंबर, profile के screenshots लो। Chat delete मत करो।",
      },
      {
        mr: "1930 वर फोन कर किंवा cybercrime.gov.in वर तक्रार कर. 1098 पण मदत करतं.",
        en: "Call 1930 or report at cybercrime.gov.in. 1098 can also help.",
        hi: "1930 पर फ़ोन करो या cybercrime.gov.in पर शिकायत करो। 1098 भी मदद करता है।",
      },
      {
        mr: "मग त्या माणसाला block कर. त्याच्याशी बोलत राहू नकोस.",
        en: "Then block the person. Don't keep talking to them.",
        hi: "फिर उस इंसान को block करो। उससे बात करते मत रहो।",
      },
    ],
    next: {
      mr: "आत्ता तू कोणाला सांगू शकतेस? नाही तर 1098 ला फोन करूया.",
      en: "Who can you tell right now? If no one, let's call 1098.",
      hi: "अभी किसे बता सकती हो? कोई नहीं तो 1098 पर फ़ोन करें।",
    },
    actions: [
      {
        label: { mr: "सायबर मदत 1930", en: "Cyber helpline 1930", hi: "साइबर हेल्पलाइन 1930" },
        href: "tel:1930",
      },
      {
        label: { mr: "1098 — मुलांची मदत", en: "Call 1098 Childline", hi: "1098 — Childline" },
        href: "tel:1098",
      },
      {
        label: { mr: "Online तक्रार", en: "Report online", hi: "Online शिकायत" },
        href: "https://cybercrime.gov.in",
      },
    ],
    girlNote: {
      mr: "तू एकटी नाहीस. हे खूप मुलींसोबत होतं, आणि यातून मार्ग निघतो.",
      en: "You are not alone. This happens to many girls, and it can be fixed.",
      hi: "तुम अकेली नहीं हो। यह कई लड़कियों के साथ होता है, और इसका हल निकलता है।",
    },
  },
  {
    id: "g_online_threats",
    intent: "act",
    ages: ["girl"],
    sensitive: "child",
    title: {
      mr: "Online धमकी",
      en: "Online threats",
      hi: "Online धमकी",
    },
    keywords: [
      "online threat",
      "threatening message",
      "someone threatening me",
      "धमकीचा मेसेज",
      "मारेन म्हणतो",
      "घरी येईन म्हणतो",
      "धमकी भरा मैसेज",
      "मार दूँगा बोला",
      "घर आ जाऊँगा",
      "dhamki",
      "dhamki de raha",
      "threat on whatsapp",
      "instagram threat",
      "account hack",
      "password मागतो",
    ],
    understand: {
      mr: "कोणी online धमकी देत असेल तर घाबरणं साहजिक आहे. तू एकटी याला सामोरं जायचं नाही.",
      en: "It's natural to be scared if someone threatens you online. You don't have to face it alone.",
      hi: "कोई online धमकी दे तो डरना स्वाभाविक है। तुम्हें इसका सामना अकेले नहीं करना।",
    },
    answer: [
      {
        mr: "उत्तर देऊ नकोस आणि भांडू नकोस.",
        en: "Don't reply and don't argue with them.",
        hi: "जवाब मत दो और बहस मत करो।",
      },
      {
        mr: "Screenshots घे, मग block आणि report कर.",
        en: "Take screenshots, then block and report.",
        hi: "Screenshots लो, फिर block और report करो।",
      },
      {
        mr: "आजच विश्वासाच्या मोठ्या माणसाला सांग.",
        en: "Tell a trusted adult today.",
        hi: "आज ही किसी भरोसेमंद बड़े को बताओ।",
      },
      {
        mr: "1930 वर सायबर तक्रार कर. घरी येण्याची किंवा इजा करण्याची धमकी असेल तर 112.",
        en: "Report on 1930. If they threaten to come or hurt you, call 112.",
        hi: "1930 पर साइबर शिकायत करो। घर आने या चोट पहुँचाने की धमकी हो तो 112.",
      },
      {
        mr: "Password कोणालाही देऊ नकोस, मैत्रिणीला पण नाही.",
        en: "Never share your password, not even with a friend.",
        hi: "Password किसी को मत दो, सहेली को भी नहीं।",
      },
    ],
    next: {
      mr: "धमकी देणारा तुला ओळखतो का, की अनोळखी आहे?",
      en: "Does the person know you, or is it a stranger?",
      hi: "धमकी देने वाला तुम्हें जानता है या अनजान है?",
    },
    actions: [
      {
        label: { mr: "सायबर मदत 1930", en: "Cyber helpline 1930", hi: "साइबर हेल्पलाइन 1930" },
        href: "tel:1930",
      },
      {
        label: { mr: "1098 — मुलांची मदत", en: "Call 1098 Childline", hi: "1098 — Childline" },
        href: "tel:1098",
      },
      {
        label: { mr: "धोका आहे — 112", en: "In danger — call 112", hi: "ख़तरा है — 112" },
        href: "tel:112",
      },
    ],
  },
  {
    id: "g_cyberbullying",
    intent: "act",
    ages: ["girl"],
    title: {
      mr: "Online चिडवणं",
      en: "Cyberbullying",
      hi: "Online चिढ़ाना",
    },
    keywords: [
      "cyberbullying",
      "online bullying",
      "mean comments",
      "group me chidhate",
      "whatsapp group",
      "meme about me",
      "online चिडवतात",
      "वाईट comment",
      "माझ्यावर meme",
      "online चिढ़ाते हैं",
      "गंदे comment",
      "मेरे बारे में अफ़वाह",
      "अफवा",
      "trolling",
      "fake page about me",
    ],
    understand: {
      mr: "Online वाईट comment, meme किंवा अफवा पसरवणं म्हणजे cyberbullying. याने खूप दुखावतं, आणि ती तुझी चूक नाही.",
      en: "Mean comments, memes or rumours online are cyberbullying. It hurts a lot, and it's not your fault.",
      hi: "Online बुरे comment, meme या अफ़वाह फैलाना cyberbullying है। यह बहुत दुख देता है, और यह तुम्हारी गलती नहीं।",
    },
    answer: [
      {
        mr: "उत्तर देऊ नकोस. राग आला तरी शांत राहा.",
        en: "Don't reply. Stay calm even if you're angry.",
        hi: "जवाब मत दो। गुस्सा आए तब भी शांत रहो।",
      },
      {
        mr: "Screenshots घे, मग block, report किंवा group मधून बाहेर पड.",
        en: "Take screenshots, then block, report or leave the group.",
        hi: "Screenshots लो, फिर block, report करो या group छोड़ दो।",
      },
      {
        mr: "घरी आणि शाळेत बाईंना सांग. शाळेचे विद्यार्थी असतील तर शाळा कारवाई करू शकते.",
        en: "Tell family and your teacher. If it's classmates, the school can act.",
        hi: "घर पर और टीचर को बताओ। स्कूल के बच्चे हों तो स्कूल कार्रवाई कर सकता है।",
      },
      {
        mr: "फोटो, खोटं page किंवा धमकी असेल तर 1930 वर तक्रार कर.",
        en: "If there are photos, a fake page or threats, report on 1930.",
        hi: "Photo, fake page या धमकी हो तो 1930 पर शिकायत करो।",
      },
    ],
    next: {
      mr: "हे करणारे तुझ्या शाळेतले आहेत का?",
      en: "Are the people doing this from your school?",
      hi: "क्या यह करने वाले तुम्हारे स्कूल के हैं?",
    },
    actions: [
      {
        label: { mr: "सायबर मदत 1930", en: "Cyber helpline 1930", hi: "साइबर हेल्पलाइन 1930" },
        href: "tel:1930",
      },
      {
        label: { mr: "1098 — मुलांची मदत", en: "Call 1098 Childline", hi: "1098 — Childline" },
        href: "tel:1098",
      },
    ],
  },

  // ─────────────────────────────── MIND ───────────────────────────────
  {
    id: "g_sad",
    intent: "connect",
    ages: ["girl"],
    sensitive: "crisis",
    title: {
      mr: "मला खूप उदास वाटतं",
      en: "I feel sad",
      hi: "मुझे बहुत उदासी है",
    },
    keywords: [
      "i feel sad",
      "nobody understands me",
      "lonely",
      "i want to die",
      "मला उदास वाटतं",
      "मला कोणी समजून घेत नाही",
      "एकटं वाटतं",
      "जगावंसं वाटत नाही",
      "मुझे उदासी है",
      "मुझे कोई नहीं समझता",
      "अकेलापन",
      "जीना नहीं चाहती",
      "mujhe koi nahi samajhta",
      "mala koni samjun ghet nahi",
      "udas",
      "depressed",
      "hurt myself",
      "खुद को नुकसान",
    ],
    understand: {
      mr: "कोणी समजून घेत नाही असं वाटणं खूप जड असतं. तू हे सांगितलंस हे चांगलं केलंस — तू एकटी नाहीस.",
      en: "Feeling that nobody understands you is really heavy. I'm glad you told me — you are not alone.",
      hi: "लगना कि कोई नहीं समझता, बहुत भारी होता है। अच्छा किया जो बताया — तुम अकेली नहीं हो।",
    },
    answer: [
      {
        mr: "स्वतःला इजा करण्याचा विचार येत असेल तर आत्ताच 112 किंवा 14416 ला फोन कर.",
        en: "If you are thinking of hurting yourself, call 112 or 14416 right now.",
        hi: "अगर खुद को नुकसान पहुँचाने का ख़याल आए तो अभी 112 या 14416 पर फ़ोन करो।",
      },
      {
        mr: "विश्वासाच्या एका मोठ्या माणसाशी आज बोल. फक्त इतकं सांग: मला बरं वाटत नाही.",
        en: "Talk to one trusted adult today. Just say: I'm not feeling okay.",
        hi: "आज किसी एक भरोसेमंद बड़े से बात करो। बस इतना कहो: मैं ठीक नहीं हूँ।",
      },
      {
        mr: "Tele-MANAS 14416 मोफत आहे. तिथे मराठीत बोलू शकतेस.",
        en: "Tele-MANAS 14416 is free. You can talk in Marathi or Hindi.",
        hi: "Tele-MANAS 14416 मुफ़्त है। वहाँ मराठी या हिंदी में बात कर सकती हो।",
      },
      {
        mr: "छोट्या गोष्टी मदत करतात: थोडं बाहेर फिर, पाणी पी, आवडतं गाणं ऐक.",
        en: "Small things help: step outside, drink water, listen to a song you like.",
        hi: "छोटी चीज़ें मदद करती हैं: बाहर टहलो, पानी पियो, पसंद का गाना सुनो।",
      },
      {
        mr: "ही भावना कायम राहत नाही. मदत घेतल्यावर बरं वाटतं.",
        en: "This feeling does not last forever. Getting help makes it better.",
        hi: "यह एहसास हमेशा नहीं रहता। मदद लेने से बेहतर लगता है।",
      },
    ],
    next: {
      mr: "आत्ता तू सुरक्षित आहेस का? आज कोणाशी बोलू शकतेस?",
      en: "Are you safe right now? Who can you talk to today?",
      hi: "क्या तुम अभी सुरक्षित हो? आज किससे बात कर सकती हो?",
    },
    actions: [
      {
        label: { mr: "Tele-MANAS 14416", en: "Tele-MANAS 14416", hi: "Tele-MANAS 14416" },
        href: "tel:14416",
      },
      {
        label: { mr: "आत्ता धोका — 112", en: "Danger now — call 112", hi: "अभी ख़तरा — 112" },
        href: "tel:112",
      },
      {
        label: { mr: "1098 — मुलांची मदत", en: "Call 1098 Childline", hi: "1098 — Childline" },
        href: "tel:1098",
      },
    ],
    girlNote: {
      mr: "तू महत्त्वाची आहेस. विश्वासाच्या मोठ्या माणसाला आजच सांग.",
      en: "You matter. Tell a trusted adult today.",
      hi: "तुम ज़रूरी हो। आज ही किसी भरोसेमंद बड़े को बताओ।",
    },
  },
];
