import type { Topic } from "./types";

// Rights (domestic violence, sexual harassment, legal information) and
// Mind (emotional wellbeing) topics for AADHI TI AI.
// Legal INFORMATION navigation only — not legal advice. Emotional support and referral — not counselling.

export const rightsTopics: Topic[] = [
  // ───────────── DOMESTIC VIOLENCE & RELATIONSHIP SAFETY ─────────────
  {
    id: "husband_hits",
    intent: "act",
    title: { mr: "नवरा मला मारतो", en: "My husband hits me", hi: "पति मुझे मारता है" },
    keywords: [
      "husband hits me",
      "husband beats me",
      "domestic violence",
      "नवरा मारतो",
      "नवरा मला मारतो",
      "नवरा हात उचलतो",
      "घरगुती हिंसा",
      "पति मारता है",
      "पति मुझे मारता है",
      "घरेलू हिंसा",
      "pati maarta hai",
      "pati marta hai",
      "navra marto",
      "navra maarto",
      "husband slaps me",
      "मारहाण",
      "marpit",
    ],
    understand: {
      mr: "तुम्हाला मारहाण होत असेल तर ही तुमची चूक नाही. घरगुती हिंसा हा गुन्हा आहे आणि तुम्हाला सुरक्षित राहण्याचा पूर्ण हक्क आहे.",
      en: "If you are being hit, it is not your fault. Domestic violence is a crime, and you have every right to be safe.",
      hi: "अगर आपको मारा जा रहा है, तो यह आपकी गलती नहीं है। घरेलू हिंसा अपराध है और आपको सुरक्षित रहने का पूरा हक है।",
    },
    answer: [
      {
        mr: "आत्ता धोका असेल तर लगेच 112 ला फोन करा किंवा शेजारी/सुरक्षित ठिकाणी जा.",
        en: "If you are in danger right now, call 112 immediately or go to a neighbour or safe place.",
        hi: "अगर अभी खतरा है, तो तुरंत 112 पर कॉल करें या पड़ोसी/सुरक्षित जगह जाएं।",
      },
      {
        mr: "181 (वन स्टॉप सेंटर) वर मदत, समुपदेशन, तात्पुरता निवारा आणि पोलिस मदत मिळू शकते.",
        en: "181 (One Stop Centre) can help with support, counselling, temporary shelter and police help.",
        hi: "181 (वन स्टॉप सेंटर) पर मदद, काउंसलिंग, अस्थायी आश्रय और पुलिस सहायता मिल सकती है।",
      },
      {
        mr: "घरगुती हिंसा कायदा 2005 नुसार संरक्षण आदेश, घरात राहण्याचा हक्क आणि खर्च मागता येतो.",
        en: "The Protection of Women from Domestic Violence Act 2005 allows protection orders, right to stay in the home, and money support.",
        hi: "घरेलू हिंसा से महिलाओं का संरक्षण अधिनियम 2005 के तहत सुरक्षा आदेश, घर में रहने का हक और खर्च मांगा जा सकता है।",
      },
      {
        mr: "तालुका/जिल्ह्यातील संरक्षण अधिकारी (Protection Officer) तुमची तक्रार कोर्टापर्यंत नेण्यास मदत करतात.",
        en: "The Protection Officer in your taluka/district helps you file a complaint and approach the court.",
        hi: "आपके तालुका/जिले के संरक्षण अधिकारी (Protection Officer) शिकायत करने और कोर्ट तक पहुंचने में मदद करते हैं।",
      },
      {
        mr: "जखमांचे फोटो, दवाखान्याचे कागद आणि तारखा जपून ठेवा — पुढे उपयोगी पडतात.",
        en: "Keep photos of injuries, hospital papers and dates safely — they help later.",
        hi: "चोटों की फोटो, अस्पताल के कागज़ और तारीखें संभालकर रखें — बाद में काम आती हैं।",
      },
    ],
    next: {
      mr: "तुम्ही आत्ता सुरक्षित आहात का? नसाल तर 112 ला फोन करा; असाल तर 181 शी बोलूया का?",
      en: "Are you safe right now? If not, call 112; if yes, shall we connect you to 181?",
      hi: "क्या आप अभी सुरक्षित हैं? नहीं तो 112 पर कॉल करें; हां तो क्या 181 से जोड़ें?",
    },
    actions: [
      { label: { mr: "112 ला कॉल करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
      { label: { mr: "181 महिला मदत", en: "Call 181 Women Helpline", hi: "181 महिला हेल्पलाइन" }, href: "tel:181" },
    ],
    emergency: false,
    sensitive: "legal",
    girlNote: {
      mr: "घरात कोणी तुला मारत असेल तर विश्वासू मोठ्या व्यक्तीला सांग किंवा 1098 ला फोन कर.",
      en: "If someone at home hits you, tell a trusted adult or call 1098.",
      hi: "अगर घर में कोई तुम्हें मारता है, तो किसी भरोसेमंद बड़े को बताओ या 1098 पर कॉल करो।",
    },
  },
  {
    id: "inlaws_threat",
    intent: "act",
    title: { mr: "सासरचे धमकी देतात", en: "In-laws threatening me", hi: "ससुराल वाले धमकाते हैं" },
    keywords: [
      "in-laws threatening",
      "in laws harassment",
      "mother in law torture",
      "सासरचे त्रास देतात",
      "सासू त्रास देते",
      "सासरचे धमकी देतात",
      "घरातून काढून टाकतो म्हणतात",
      "ससुराल वाले धमकाते हैं",
      "सास परेशान करती है",
      "ससुराल में प्रताड़ना",
      "sasural wale dhamki",
      "saas pareshan karti hai",
      "sasarche tras detat",
      "sasu tras dete",
      "498a",
      "cruelty by in-laws",
    ],
    understand: {
      mr: "सासरचे धमकावत किंवा छळत असतील तर तेही घरगुती हिंसेतच येते. तुम्ही एकट्या नाही.",
      en: "Threats or harassment from in-laws can also be domestic violence. You are not alone.",
      hi: "ससुराल वालों की धमकी या प्रताड़ना भी घरेलू हिंसा में आती है। आप अकेली नहीं हैं।",
    },
    answer: [
      {
        mr: "घरगुती हिंसा कायदा 2005 सासू, सासरे, दीर, नणंद यांच्या छळावरही लागू होतो.",
        en: "The Domestic Violence Act 2005 also covers abuse by mother-in-law, father-in-law and other relatives.",
        hi: "घरेलू हिंसा अधिनियम 2005 सास, ससुर और अन्य रिश्तेदारों की प्रताड़ना पर भी लागू होता है।",
      },
      {
        mr: "सासरच्या घरात राहण्याचा तुमचा हक्क आहे; तुम्हाला जबरदस्तीने बाहेर काढता येत नाही.",
        en: "You have a right to live in the shared household; you cannot be forcibly thrown out.",
        hi: "ससुराल के घर में रहने का आपका हक है; आपको जबरदस्ती निकाला नहीं जा सकता।",
      },
      {
        mr: "धमकीचे मेसेज, कॉल रेकॉर्ड, तारखा आणि साक्षीदार लिहून ठेवा.",
        en: "Save threatening messages, call records, dates and names of witnesses.",
        hi: "धमकी वाले मैसेज, कॉल रिकॉर्ड, तारीखें और गवाहों के नाम संभालकर रखें।",
      },
      {
        mr: "181 किंवा संरक्षण अधिकाऱ्यांकडे मदत मिळते; धोका असेल तर 112.",
        en: "181 or the Protection Officer can help; if in danger, call 112.",
        hi: "181 या संरक्षण अधिकारी मदद करते हैं; खतरा हो तो 112।",
      },
    ],
    next: {
      mr: "धमकी मारहाणीपर्यंत गेली आहे का? तसं असेल तर लगेच 112 किंवा 181 ला फोन करा.",
      en: "Have the threats turned physical? If so, call 112 or 181 now.",
      hi: "क्या धमकी मारपीट तक पहुंची है? तो अभी 112 या 181 पर कॉल करें।",
    },
    actions: [
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
      { label: { mr: "112 आपत्कालीन", en: "Call 112", hi: "112 आपातकाल" }, href: "tel:112" },
    ],
    sensitive: "legal",
  },
  {
    id: "financial_control",
    intent: "check",
    title: { mr: "पैशावर पूर्ण नियंत्रण", en: "Being controlled financially", hi: "पैसों पर पूरा नियंत्रण" },
    keywords: [
      "financial abuse",
      "economic abuse",
      "husband takes my salary",
      "no money given",
      "पैसे देत नाही",
      "नवरा पगार घेतो",
      "खर्चाला पैसे देत नाहीत",
      "पैसे मागितले तर ओरडतो",
      "पैसे नहीं देता",
      "पति सैलरी ले लेता है",
      "आर्थिक शोषण",
      "paise nahi deta",
      "salary le leta hai",
      "paise det nahi",
      "kharchala paise nahi",
      "atm card le liya",
    ],
    understand: {
      mr: "तुमचे पैसे काढून घेणे, खर्चाला काहीच न देणे किंवा नोकरी करू न देणे — हा आर्थिक छळ आहे, आणि तोही छळच आहे.",
      en: "Taking your money, giving you nothing for basic needs, or stopping you from working is economic abuse.",
      hi: "आपके पैसे छीनना, ज़रूरत के लिए कुछ न देना या काम करने से रोकना आर्थिक शोषण है — और यह भी हिंसा है।",
    },
    answer: [
      {
        mr: "घरगुती हिंसा कायदा 2005 मध्ये आर्थिक छळ स्पष्टपणे गुन्हा म्हणून मानला आहे.",
        en: "The Domestic Violence Act 2005 clearly includes economic abuse.",
        hi: "घरेलू हिंसा अधिनियम 2005 में आर्थिक शोषण साफ़ तौर पर शामिल है।",
      },
      {
        mr: "स्वतःच्या नावाने बँक खाते उघडा; तुमचा पगार आणि स्त्रीधन तुमचेच आहे.",
        en: "Open a bank account in your own name; your salary and streedhan belong to you.",
        hi: "अपने नाम से बैंक खाता खोलें; आपकी सैलरी और स्त्रीधन आपका ही है।",
      },
      {
        mr: "स्वतःसाठी आणि मुलांसाठी पोटगी (maintenance) मागण्याचा हक्क आहे.",
        en: "You have a right to claim maintenance for yourself and your children.",
        hi: "आपको अपने और बच्चों के लिए भरण-पोषण मांगने का हक है।",
      },
      {
        mr: "सरकारी योजनांमधून स्वतःचे उत्पन्न सुरू करता येईल — योजना पाहा.",
        en: "Government schemes can help you start your own income — check schemes.",
        hi: "सरकारी योजनाओं से अपनी आमदनी शुरू कर सकती हैं — योजनाएं देखें।",
      },
    ],
    next: {
      mr: "तुमच्यासाठी उपयोगी सरकारी योजना पाहायच्या आहेत का, की 181 शी बोलायचं आहे?",
      en: "Would you like to see useful government schemes, or talk to 181?",
      hi: "क्या आप सरकारी योजनाएं देखना चाहेंगी, या 181 से बात करना?",
    },
    actions: [
      { label: { mr: "योजना पाहा", en: "Ask about financial security", hi: "योजनाएं देखें" }, href: "/schemes" },
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
    ],
    sensitive: "legal",
  },
  {
    id: "coercive_control",
    intent: "check",
    title: { mr: "फोन तपासणे, बंधने", en: "He checks my phone, controls me", hi: "फोन चेक करना, रोक-टोक" },
    keywords: [
      "माझ्या नवऱ्याला माझा फोन सतत तपासायचा असतो",
      "नवरा फोन तपासतो",
      "pati phone check karta hai",
      "husband checks my phone",
      "controlling husband",
      "coercive control",
      "कुठे जाते विचारतो",
      "मैत्रिणींना भेटू देत नाही",
      "माहेरी जाऊ देत नाही",
      "पति फोन चेक करता है",
      "किसी से मिलने नहीं देता",
      "बाहर जाने नहीं देता",
      "navra phone tapasto",
      "bahar jane nahi deta",
      "location track karta hai",
      "shak karta hai",
      "संशय घेतो",
    ],
    understand: {
      mr: "सतत फोन तपासणे, कुठे जायचे-कोणाला भेटायचे यावर बंधन घालणे — याला नियंत्रण ठेवणारा छळ (coercive control) म्हणतात. हे 'प्रेम' नाही.",
      en: "Constantly checking your phone and controlling where you go or who you meet is called coercive control. It is not 'love'.",
      hi: "लगातार फोन चेक करना, कहां जाना-किससे मिलना इस पर रोक लगाना नियंत्रण वाली प्रताड़ना (coercive control) है। यह 'प्यार' नहीं है।",
    },
    answer: [
      {
        mr: "असे वागणे भावनिक छळात येते आणि घरगुती हिंसा कायद्यात समाविष्ट आहे.",
        en: "This behaviour is emotional abuse and is covered under the Domestic Violence Act.",
        hi: "यह व्यवहार भावनात्मक शोषण है और घरेलू हिंसा कानून में आता है।",
      },
      {
        mr: "फोनला स्वतःचा पासवर्ड ठेवा; लोकेशन शेअरिंग आणि अनोळखी apps तपासा.",
        en: "Keep your own phone password; check location sharing and unknown apps.",
        hi: "फोन पर अपना पासवर्ड रखें; लोकेशन शेयरिंग और अनजान ऐप्स जांचें।",
      },
      {
        mr: "एखाद्या विश्वासू मैत्रीण/नातेवाईकाशी संपर्क ठेवा — एकटे पडू नका.",
        en: "Stay in touch with one trusted friend or relative — don't get isolated.",
        hi: "किसी भरोसेमंद सहेली/रिश्तेदार से संपर्क बनाए रखें — अकेली न पड़ें।",
      },
      {
        mr: "हे वाढत गेले किंवा भीती वाटत असेल तर 181 वर गोपनीयपणे बोला.",
        en: "If it is getting worse or you feel afraid, talk to 181 confidentially.",
        hi: "अगर यह बढ़ रहा है या डर लगता है, तो 181 पर गोपनीय बात करें।",
      },
    ],
    next: {
      mr: "तुम्हाला भीती वाटते का? फोन सुरक्षित कसा ठेवायचा ते पाहूया का?",
      en: "Do you feel afraid? Shall we look at how to keep your phone safe?",
      hi: "क्या आपको डर लगता है? क्या फोन सुरक्षित रखने के तरीके देखें?",
    },
    actions: [
      { label: { mr: "181 गोपनीय मदत", en: "Call 181 confidentially", hi: "181 गोपनीय मदद" }, href: "tel:181" },
      { label: { mr: "सुरक्षा माहिती", en: "Safety awareness", hi: "सुरक्षा जानकारी" }, href: "/awareness" },
    ],
    sensitive: "legal",
  },
  {
    id: "partner_forcing",
    intent: "act",
    title: { mr: "जबरदस्ती केली जाते", en: "Partner forcing me", hi: "साथी ज़बरदस्ती करता है" },
    keywords: [
      "partner forcing me",
      "forced sex",
      "sexual coercion",
      "husband forces me",
      "marital rape",
      "जबरदस्ती करतो",
      "नको म्हटलं तरी ऐकत नाही",
      "इच्छेविरुद्ध",
      "ज़बरदस्ती करता है",
      "मना करने पर भी",
      "मर्ज़ी के खिलाफ",
      "zabardasti karta hai",
      "jabardasti karto",
      "mana karne par bhi",
      "naahi mhatla tari",
      "force karto",
    ],
    understand: {
      mr: "तुमची इच्छा नसताना कोणीही — नवरा किंवा साथीदार असला तरी — काहीही करायला भाग पाडू शकत नाही. 'नाही' म्हणण्याचा तुम्हाला पूर्ण हक्क आहे.",
      en: "No one — not even a husband or partner — has the right to force you into anything. You always have the right to say no.",
      hi: "कोई भी — पति या साथी भी — आपको आपकी मर्ज़ी के बिना कुछ करने को मजबूर नहीं कर सकता। 'ना' कहने का आपको पूरा हक है।",
    },
    answer: [
      {
        mr: "आत्ता धोका असेल तर 112 ला फोन करा किंवा सुरक्षित ठिकाणी जा.",
        en: "If you are in danger now, call 112 or move to a safe place.",
        hi: "अगर अभी खतरा है, तो 112 पर कॉल करें या सुरक्षित जगह जाएं।",
      },
      {
        mr: "लैंगिक जबरदस्ती हा घरगुती हिंसा कायद्यानुसार लैंगिक छळ आहे.",
        en: "Sexual coercion counts as sexual abuse under the Domestic Violence Act.",
        hi: "यौन ज़बरदस्ती घरेलू हिंसा कानून में यौन शोषण मानी जाती है।",
      },
      {
        mr: "181 वन स्टॉप सेंटरमध्ये वैद्यकीय मदत, समुपदेशन आणि कायदेशीर माहिती एकाच ठिकाणी मिळते.",
        en: "181 One Stop Centre offers medical help, counselling and legal information in one place.",
        hi: "181 वन स्टॉप सेंटर में मेडिकल मदद, काउंसलिंग और कानूनी जानकारी एक जगह मिलती है।",
      },
      {
        mr: "यात तुमची काहीच चूक नाही. कोणाशी तरी बोलणं मदतीचं ठरू शकतं.",
        en: "None of this is your fault. Talking to someone can really help.",
        hi: "इसमें आपकी कोई गलती नहीं है। किसी से बात करना मदद कर सकता है।",
      },
    ],
    next: {
      mr: "तुम्ही आत्ता सुरक्षित आहात का? 181 शी गोपनीयपणे बोलायचं आहे का?",
      en: "Are you safe right now? Would you like to talk to 181 confidentially?",
      hi: "क्या आप अभी सुरक्षित हैं? क्या 181 से गोपनीय बात करना चाहेंगी?",
    },
    actions: [
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
      { label: { mr: "112 आपत्कालीन", en: "Call 112", hi: "112 आपातकाल" }, href: "tel:112" },
    ],
    sensitive: "crisis",
    girlNote: {
      mr: "कोणी तुझ्यावर जबरदस्ती करत असेल तर विश्वासू मोठ्या व्यक्तीला सांग किंवा 1098 ला फोन कर. तुझी चूक नाही.",
      en: "If anyone is forcing you, tell a trusted adult or call 1098. It is not your fault.",
      hi: "अगर कोई तुम पर ज़बरदस्ती करता है, तो किसी भरोसेमंद बड़े को बताओ या 1098 पर कॉल करो। तुम्हारी गलती नहीं है।",
    },
  },
  {
    id: "afraid_tell_family",
    intent: "connect",
    title: { mr: "घरी सांगायला भीती", en: "Afraid to tell family", hi: "घर वालों को बताने से डर" },
    keywords: [
      "afraid to tell family",
      "speak confidentially",
      "secret help",
      "talk to someone privately",
      "घरी सांगायला भीती वाटते",
      "कोणाला सांगू",
      "गुपचूप मदत",
      "कोणाला कळू नये",
      "घरवालों को बताने से डर",
      "किसी को पता न चले",
      "गोपनीय बात",
      "ghar walon ko batane se dar",
      "kisi ko pata na chale",
      "ghari sangayla bhiti",
      "konala sangu",
      "confidential helpline",
    ],
    understand: {
      mr: "घरच्यांना सांगायला भीती वाटणं अगदी साहजिक आहे. तुम्ही कोणाला कळू न देता मदत घेऊ शकता.",
      en: "Feeling afraid to tell your family is very natural. You can get help without them knowing.",
      hi: "घरवालों को बताने से डर लगना बिल्कुल स्वाभाविक है। आप बिना किसी को बताए मदद ले सकती हैं।",
    },
    answer: [
      {
        mr: "181 महिला हेल्पलाइन मोफत, 24 तास आणि गोपनीय आहे.",
        en: "181 Women Helpline is free, 24x7 and confidential.",
        hi: "181 महिला हेल्पलाइन मुफ्त, 24 घंटे और गोपनीय है।",
      },
      {
        mr: "मन भारी असेल तर Tele-MANAS 14416 वर समुपदेशकाशी बोलता येते.",
        en: "If your mind feels heavy, you can talk to a counsellor on Tele-MANAS 14416.",
        hi: "मन भारी हो तो Tele-MANAS 14416 पर काउंसलर से बात कर सकती हैं।",
      },
      {
        mr: "फोन केल्यानंतर कॉल हिस्टरी डिलीट करू शकता, जर तुम्हाला सुरक्षित वाटत असेल.",
        en: "You can delete the call history afterwards if that feels safer.",
        hi: "कॉल के बाद कॉल हिस्ट्री डिलीट कर सकती हैं, अगर यह सुरक्षित लगे।",
      },
      {
        mr: "तुम्ही कधी आणि कोणाला सांगायचं हे तुम्हीच ठरवा — घाई नाही.",
        en: "You decide when and whom to tell — there is no rush.",
        hi: "कब और किसे बताना है यह आप तय करें — कोई जल्दी नहीं।",
      },
    ],
    next: {
      mr: "आत्ता 181 वर एखाद्या व्यक्तीशी गोपनीयपणे बोलायचं आहे का?",
      en: "Would you like to talk to someone at 181 confidentially now?",
      hi: "क्या आप अभी 181 पर किसी से गोपनीय बात करना चाहेंगी?",
    },
    actions: [
      { label: { mr: "181 गोपनीय मदत", en: "Call 181", hi: "181 गोपनीय मदद" }, href: "tel:181" },
      { label: { mr: "14416 मनाशी बोला", en: "Call Tele-MANAS 14416", hi: "14416 Tele-MANAS" }, href: "tel:14416" },
    ],
    girlNote: {
      mr: "घरी सांगता येत नसेल तर शिक्षिका किंवा विश्वासू मोठ्या व्यक्तीला सांग, किंवा 1098 ला फोन कर.",
      en: "If you can't tell family, tell a teacher or trusted adult, or call 1098.",
      hi: "घर पर नहीं बता सकती तो टीचर या भरोसेमंद बड़े को बताओ, या 1098 पर कॉल करो।",
    },
  },
  {
    id: "what_is_abuse",
    intent: "learn",
    title: { mr: "छळ म्हणजे काय?", en: "What counts as abuse?", hi: "हिंसा क्या होती है?" },
    keywords: [
      "what is abuse",
      "types of abuse",
      "is this abuse",
      "emotional abuse",
      "verbal abuse",
      "छळ म्हणजे काय",
      "हे छळ आहे का",
      "शिव्या देतो",
      "टोमणे मारतात",
      "क्या यह हिंसा है",
      "गाली देता है",
      "ताने मारते हैं",
      "kya ye abuse hai",
      "gaali deta hai",
      "shivya deto",
      "tomne martat",
      "mansik tras",
      "मानसिक त्रास",
    ],
    understand: {
      mr: "छळ फक्त मारहाणच नसतो. तुम्हाला सतत भीती, अपमान किंवा दबाव वाटत असेल तर तो छळ असू शकतो.",
      en: "Abuse is not only hitting. If you constantly feel fear, humiliation or pressure, it may be abuse.",
      hi: "हिंसा सिर्फ मारपीट नहीं है। अगर आपको लगातार डर, अपमान या दबाव महसूस होता है, तो यह हिंसा हो सकती है।",
    },
    answer: [
      {
        mr: "शारीरिक: मारणे, ढकलणे, चटके देणे. भावनिक: अपमान, धमक्या, एकटे पाडणे.",
        en: "Physical: hitting, pushing, burning. Emotional: insults, threats, isolating you.",
        hi: "शारीरिक: मारना, धक्का देना, जलाना। भावनात्मक: अपमान, धमकी, अकेला करना।",
      },
      {
        mr: "शाब्दिक: शिव्या, टोमणे, सतत ओरडणे. लैंगिक: इच्छेविरुद्ध स्पर्श किंवा संबंध.",
        en: "Verbal: abuse, taunts, constant shouting. Sexual: any touch or act without your consent.",
        hi: "मौखिक: गाली, ताने, लगातार चिल्लाना। यौन: आपकी मर्ज़ी के बिना कोई स्पर्श या संबंध।",
      },
      {
        mr: "आर्थिक: पैसे काढून घेणे, खर्च न देणे, नोकरी करू न देणे.",
        en: "Economic: taking your money, not giving for needs, stopping you from working.",
        hi: "आर्थिक: पैसे छीनना, खर्च न देना, नौकरी न करने देना।",
      },
      {
        mr: "हे सगळे प्रकार घरगुती हिंसा कायदा 2005 मध्ये येतात.",
        en: "All of these are covered under the Domestic Violence Act 2005.",
        hi: "ये सभी घरेलू हिंसा अधिनियम 2005 में आते हैं।",
      },
    ],
    next: {
      mr: "यापैकी काही तुमच्यासोबत होत आहे का? 181 वर बोलता येईल.",
      en: "Is any of this happening to you? You can talk to 181.",
      hi: "क्या इनमें से कुछ आपके साथ हो रहा है? आप 181 पर बात कर सकती हैं।",
    },
    actions: [
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
      { label: { mr: "अधिक माहिती", en: "Learn more", hi: "और जानकारी" }, href: "/awareness" },
    ],
  },
  {
    id: "document_abuse",
    intent: "learn",
    title: { mr: "छळाचे पुरावे कसे ठेवायचे", en: "How to document abuse", hi: "प्रताड़ना के सबूत कैसे रखें" },
    keywords: [
      "document abuse",
      "evidence",
      "proof of harassment",
      "how to keep proof",
      "पुरावा",
      "पुरावे कसे ठेवायचे",
      "सबूत",
      "सबूत कैसे रखें",
      "repeated harassment",
      "screenshot",
      "purava",
      "saboot kaise rakhe",
      "purave kase thevayche",
      "diary likhna",
      "रेकॉर्डिंग",
      "medical report",
    ],
    understand: {
      mr: "वारंवार त्रास होत असेल तर त्याची नोंद ठेवणे पुढे तक्रार करताना खूप मदत करते.",
      en: "If harassment keeps happening, keeping a record helps a lot if you decide to complain later.",
      hi: "अगर बार-बार परेशान किया जा रहा है, तो रिकॉर्ड रखना बाद में शिकायत करने में बहुत मदद करता है।",
    },
    answer: [
      {
        mr: "प्रत्येक घटनेची तारीख, वेळ, ठिकाण आणि काय घडलं ते वहीत लिहा.",
        en: "Write down each incident's date, time, place and what happened.",
        hi: "हर घटना की तारीख, समय, जगह और क्या हुआ, डायरी में लिखें।",
      },
      {
        mr: "मेसेजचे स्क्रीनशॉट, जखमांचे फोटो, दवाखान्याचे कागद जपा.",
        en: "Save screenshots of messages, photos of injuries and medical papers.",
        hi: "मैसेज के स्क्रीनशॉट, चोटों की फोटो और अस्पताल के कागज़ संभालें।",
      },
      {
        mr: "याची प्रत विश्वासू व्यक्तीकडे किंवा सुरक्षित ईमेलवर ठेवा.",
        en: "Keep a copy with a trusted person or in a safe email account.",
        hi: "इसकी कॉपी किसी भरोसेमंद व्यक्ति के पास या सुरक्षित ईमेल में रखें।",
      },
      {
        mr: "साक्षीदारांची नावे लिहा. पुरावे गोळा करताना तुमची सुरक्षा आधी.",
        en: "Note names of witnesses. Your safety comes before collecting evidence.",
        hi: "गवाहों के नाम लिखें। सबूत जुटाने से पहले आपकी सुरक्षा ज़रूरी है।",
      },
    ],
    next: {
      mr: "पुढे काय करायचं ते ठरवायला मोफत कायदेशीर मदत (15100) किंवा 181 शी बोलू शकता.",
      en: "To decide next steps, you can talk to free legal aid (15100) or 181.",
      hi: "आगे क्या करें यह तय करने के लिए मुफ्त कानूनी सहायता (15100) या 181 से बात करें।",
    },
    actions: [
      { label: { mr: "15100 मोफत कायदा मदत", en: "Call 15100 Legal Aid", hi: "15100 मुफ्त कानूनी मदद" }, href: "tel:15100" },
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
    ],
    sensitive: "legal",
  },

  // ───────────── SEXUAL HARASSMENT & VIOLENCE ─────────────
  {
    id: "workplace_posh",
    intent: "act",
    title: { mr: "कामाच्या ठिकाणी छळ", en: "Harassment at work", hi: "कार्यस्थल पर उत्पीड़न" },
    keywords: [
      "माझे बॉस मला रात्री personal messages करतात",
      "boss raat ko message karta hai",
      "sexual harassment at work",
      "posh",
      "posh act",
      "workplace harassment",
      "internal committee",
      "बॉस त्रास देतो",
      "ऑफिसमध्ये छेडछाड",
      "कामावर त्रास",
      "बॉस परेशान करता है",
      "ऑफिस में छेड़छाड़",
      "boss pareshan karta hai",
      "office madhye tras",
      "colleague touching",
      "manager harassing",
    ],
    understand: {
      mr: "कामाच्या ठिकाणी नको असलेले मेसेज, स्पर्श, टिप्पणी किंवा मागण्या — हा लैंगिक छळ आहे. तुमची चूक नाही.",
      en: "Unwanted messages, touching, comments or demands at work are sexual harassment. It is not your fault.",
      hi: "काम की जगह पर अनचाहे मैसेज, छूना, टिप्पणी या मांगें यौन उत्पीड़न हैं। आपकी गलती नहीं है।",
    },
    answer: [
      {
        mr: "POSH कायदा 2013 नुसार 10+ कर्मचारी असलेल्या ठिकाणी अंतर्गत समिती (IC) असावी लागते.",
        en: "Under the POSH Act 2013, workplaces with 10+ employees must have an Internal Committee.",
        hi: "POSH अधिनियम 2013 के तहत 10+ कर्मचारियों वाली जगह पर आंतरिक समिति होनी चाहिए।",
      },
      {
        mr: "IC नसेल किंवा तक्रार मालकाविरुद्ध असेल तर जिल्हा स्तरावरील स्थानिक समितीकडे जा.",
        en: "If there's no IC, or the complaint is against the employer, go to the district Local Committee.",
        hi: "IC न हो या शिकायत मालिक के खिलाफ हो, तो जिला स्तर की स्थानीय समिति में जाएं।",
      },
      {
        mr: "घटनेपासून 3 महिन्यांत लेखी तक्रार करावी; कारण असल्यास मुदत वाढू शकते.",
        en: "Complain in writing within 3 months of the incident; this can be extended for valid reasons.",
        hi: "घटना के 3 महीने के अंदर लिखित शिकायत करें; वाजिब कारण हो तो समय बढ़ सकता है।",
      },
      {
        mr: "मेसेजचे स्क्रीनशॉट, तारखा आणि साक्षीदार जपून ठेवा.",
        en: "Save screenshots of messages, dates and witness names.",
        hi: "मैसेज के स्क्रीनशॉट, तारीखें और गवाहों के नाम संभालें।",
      },
    ],
    next: {
      mr: "तुमच्या कामाच्या ठिकाणी अंतर्गत समिती आहे का? नसेल तर 181 कडून स्थानिक समितीची माहिती घ्या.",
      en: "Does your workplace have an Internal Committee? If not, ask 181 about the Local Committee.",
      hi: "क्या आपके ऑफिस में आंतरिक समिति है? नहीं तो 181 से स्थानीय समिति की जानकारी लें।",
    },
    actions: [
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
      { label: { mr: "15100 मोफत कायदा मदत", en: "Call 15100 Legal Aid", hi: "15100 मुफ्त कानूनी मदद" }, href: "tel:15100" },
    ],
    sensitive: "legal",
  },
  {
    id: "after_assault",
    intent: "act",
    title: { mr: "लैंगिक अत्याचारानंतर काय करावे", en: "After sexual assault", hi: "यौन हमले के बाद क्या करें" },
    keywords: [
      "sexual assault",
      "rape",
      "raped",
      "what to do after assault",
      "बलात्कार",
      "अत्याचार झाला",
      "माझ्यावर अत्याचार झाला",
      "जबरदस्ती झाली",
      "मेरे साथ बलात्कार हुआ",
      "यौन हमला",
      "मेरे साथ गलत हुआ",
      "mere saath galat hua",
      "majhyavar atyachar zala",
      "balatkar",
      "molested",
      "जबरदस्ती संबंध",
    ],
    understand: {
      mr: "तुमच्यासोबत जे घडलं ते अतिशय कठीण आहे आणि त्यात तुमची काहीच चूक नाही. आधी तुमची सुरक्षा आणि आरोग्य.",
      en: "What happened to you is very hard, and it is not your fault in any way. Your safety and health come first.",
      hi: "आपके साथ जो हुआ वह बहुत कठिन है, और इसमें आपकी कोई गलती नहीं है। पहले आपकी सुरक्षा और सेहत।",
    },
    answer: [
      {
        mr: "आधी सुरक्षित ठिकाणी जा. धोका असेल तर लगेच 112 ला फोन करा.",
        en: "First get to a safe place. If in danger, call 112 immediately.",
        hi: "पहले सुरक्षित जगह जाएं। खतरा हो तो तुरंत 112 पर कॉल करें।",
      },
      {
        mr: "कोणत्याही दवाखान्यात मोफत उपचार हा तुमचा हक्क आहे; वैद्यकीय तपासणी पुरावा म्हणूनही उपयोगी.",
        en: "Free treatment at any hospital is your right; a medical exam also helps as evidence.",
        hi: "किसी भी अस्पताल में मुफ्त इलाज आपका हक है; मेडिकल जांच सबूत में भी मदद करती है।",
      },
      {
        mr: "शक्य असेल तर आंघोळ करू नका, कपडे धुवू नका — पण तुमचं मन आणि आरोग्य आधी.",
        en: "If you can, avoid bathing or washing clothes — but your wellbeing comes first.",
        hi: "हो सके तो नहाएं नहीं, कपड़े न धोएं — पर आपकी भलाई सबसे पहले।",
      },
      {
        mr: "कोणत्याही पोलिस ठाण्यात Zero FIR नोंदवता येते; जबाब महिला अधिकारी घेते.",
        en: "You can file a Zero FIR at any police station; a woman officer records your statement.",
        hi: "किसी भी थाने में Zero FIR दर्ज हो सकती है; बयान महिला अधिकारी लेती है।",
      },
      {
        mr: "181 वन स्टॉप सेंटर वैद्यकीय, पोलिस, कायदेशीर आणि समुपदेशन मदत एकत्र देते.",
        en: "181 One Stop Centre gives medical, police, legal and counselling help together.",
        hi: "181 वन स्टॉप सेंटर मेडिकल, पुलिस, कानूनी और काउंसलिंग मदद एक साथ देता है।",
      },
    ],
    next: {
      mr: "तुम्ही आत्ता सुरक्षित आहात का? 181 किंवा 112 ला फोन लावूया का?",
      en: "Are you safe right now? Shall we call 181 or 112?",
      hi: "क्या आप अभी सुरक्षित हैं? क्या 181 या 112 पर कॉल करें?",
    },
    actions: [
      { label: { mr: "112 ला कॉल करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
      { label: { mr: "181 वन स्टॉप सेंटर", en: "Call 181 One Stop Centre", hi: "181 वन स्टॉप सेंटर" }, href: "tel:181" },
      { label: { mr: "108 रुग्णवाहिका", en: "Call 108 Ambulance", hi: "108 एम्बुलेंस" }, href: "tel:108" },
    ],
    sensitive: "crisis",
    emergency: true,
    girlNote: {
      mr: "तुझ्यासोबत असं काही झालं असेल तर विश्वासू मोठ्या व्यक्तीला सांग किंवा 1098 ला फोन कर. तुझी चूक नाही.",
      en: "If this happened to you, tell a trusted adult or call 1098. It is not your fault.",
      hi: "अगर तुम्हारे साथ ऐसा हुआ है, तो किसी भरोसेमंद बड़े को बताओ या 1098 पर कॉल करो। तुम्हारी गलती नहीं है।",
    },
  },
  {
    id: "stalking_offline",
    intent: "act",
    title: { mr: "कोणी पाठलाग करतो", en: "Someone is following me", hi: "कोई पीछा करता है" },
    keywords: [
      "stalking",
      "someone following me",
      "keeps calling me",
      "watching me",
      "पाठलाग करतो",
      "मागे मागे येतो",
      "सारखा फोन करतो",
      "घराबाहेर उभा राहतो",
      "पीछा करता है",
      "बार बार फोन करता है",
      "घूरता है",
      "peecha karta hai",
      "pathlag karto",
      "mage mage yeto",
      "roj follow karto",
      "stalker",
    ],
    understand: {
      mr: "कोणी सतत पाठलाग करत असेल, नजर ठेवत असेल किंवा फोन करत असेल तर तो पाठलाग (stalking) आहे — आणि तो गुन्हा आहे.",
      en: "If someone keeps following, watching or calling you, that is stalking — and stalking is a crime.",
      hi: "अगर कोई लगातार पीछा करता है, नज़र रखता है या फोन करता है, तो यह स्टॉकिंग है — और यह अपराध है।",
    },
    answer: [
      {
        mr: "आत्ता कोणी मागे येत असेल तर गर्दीच्या ठिकाणी जा आणि 112 ला फोन करा.",
        en: "If someone is following you now, go to a crowded place and call 112.",
        hi: "अगर अभी कोई पीछा कर रहा है, तो भीड़ वाली जगह जाएं और 112 पर कॉल करें।",
      },
      {
        mr: "1091 महिला हेल्पलाइन किंवा जवळच्या पोलिस ठाण्यात तक्रार देता येते.",
        en: "You can complain to 1091 Women Helpline or the nearest police station.",
        hi: "1091 महिला हेल्पलाइन या नज़दीकी थाने में शिकायत कर सकती हैं।",
      },
      {
        mr: "तारखा, वेळा, नंबर आणि कॉल लॉग लिहून ठेवा; शक्य असल्यास फोटो.",
        en: "Note dates, times, numbers and call logs; photos if safely possible.",
        hi: "तारीखें, समय, नंबर और कॉल लॉग लिखें; सुरक्षित हो तो फोटो लें।",
      },
      {
        mr: "घरच्यांना किंवा मैत्रिणींना कळवा आणि शक्यतो सोबत जा-ये करा.",
        en: "Tell family or friends and try to travel with someone.",
        hi: "घरवालों या सहेलियों को बताएं और हो सके तो किसी के साथ आएं-जाएं।",
      },
    ],
    next: {
      mr: "तो आत्ता जवळ आहे का? तसं असेल तर 112 ला फोन करा किंवा fake call वापरा.",
      en: "Is he nearby right now? If so, call 112 or use a fake call.",
      hi: "क्या वह अभी पास है? तो 112 पर कॉल करें या फेक कॉल इस्तेमाल करें।",
    },
    actions: [
      { label: { mr: "112 ला कॉल करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
      { label: { mr: "1091 महिला हेल्पलाइन", en: "Call 1091", hi: "1091 महिला हेल्पलाइन" }, href: "tel:1091" },
      { label: { mr: "खोटा कॉल", en: "Fake call", hi: "फेक कॉल" }, href: "/call?mode=fake" },
    ],
    sensitive: "legal",
    girlNote: {
      mr: "शाळेत जाता-येताना कोणी मागे येत असेल तर घरच्यांना किंवा शिक्षिकेला सांग, किंवा 1098 ला फोन कर.",
      en: "If someone follows you to or from school, tell family or a teacher, or call 1098.",
      hi: "स्कूल आते-जाते कोई पीछा करे तो घरवालों या टीचर को बताओ, या 1098 पर कॉल करो।",
    },
  },
  {
    id: "known_abuser",
    intent: "act",
    title: { mr: "ओळखीचा माणूस त्रास देतो", en: "Abuse by someone I know", hi: "जान-पहचान वाला परेशान करता है" },
    keywords: [
      "abuse by relative",
      "uncle touching",
      "neighbour harassing",
      "teacher harassment",
      "someone i know",
      "नातेवाईक त्रास देतो",
      "शेजारी त्रास देतो",
      "काका चुकीचा स्पर्श",
      "सर चुकीचा स्पर्श करतात",
      "रिश्तेदार गलत छूता है",
      "पड़ोसी परेशान करता है",
      "टीचर गलत हरकत",
      "rishtedar galat chhuta hai",
      "padosi pareshan karta hai",
      "natevaik tras deto",
      "bad touch",
      "ओळखीचा माणूस",
    ],
    understand: {
      mr: "बहुतेक वेळा छळ करणारा ओळखीचाच असतो — नातेवाईक, शेजारी किंवा शिक्षक. सांगणं कठीण असतं, पण तुमची काही चूक नाही.",
      en: "Very often the abuser is someone known — a relative, neighbour or teacher. It is hard to speak up, but it is not your fault.",
      hi: "अक्सर शोषण करने वाला कोई जान-पहचान वाला ही होता है — रिश्तेदार, पड़ोसी या टीचर। बोलना मुश्किल है, पर आपकी गलती नहीं है।",
    },
    answer: [
      {
        mr: "नातं कितीही जवळचं असलं तरी छळ हा गुन्हाच आहे.",
        en: "No matter how close the relationship, abuse is still a crime.",
        hi: "रिश्ता कितना भी करीबी हो, शोषण अपराध ही है।",
      },
      {
        mr: "शक्य तितकं त्या व्यक्तीसोबत एकटं राहणं टाळा.",
        en: "As far as possible, avoid being alone with that person.",
        hi: "जहां तक हो सके, उस व्यक्ति के साथ अकेले रहने से बचें।",
      },
      {
        mr: "एखाद्या विश्वासू व्यक्तीला सांगा; 181 वर गोपनीय मदत मिळते.",
        en: "Tell someone you trust; 181 offers confidential help.",
        hi: "किसी भरोसेमंद को बताएं; 181 पर गोपनीय मदद मिलती है।",
      },
      {
        mr: "मुलगी 18 वर्षाखालील असेल तर POCSO कायदा लागू होतो; 1098 वर कळवा.",
        en: "If the girl is under 18, the POCSO Act applies; call 1098.",
        hi: "अगर लड़की 18 से कम है, तो POCSO कानून लागू होता है; 1098 पर बताएं।",
      },
    ],
    next: {
      mr: "आत्ता तुम्ही सुरक्षित आहात का? 181 शी बोलायचं आहे का?",
      en: "Are you safe right now? Would you like to talk to 181?",
      hi: "क्या आप अभी सुरक्षित हैं? क्या 181 से बात करना चाहेंगी?",
    },
    actions: [
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
      { label: { mr: "1098 बाल मदत", en: "Call 1098 Childline", hi: "1098 चाइल्डलाइन" }, href: "tel:1098" },
    ],
    sensitive: "crisis",
    girlNote: {
      mr: "कोणी ओळखीचा तुला चुकीचा स्पर्श करत असेल तर 'नाही' म्हण, तिथून निघ आणि विश्वासू मोठ्या व्यक्तीला सांग. 1098 ला फोन कर.",
      en: "If someone you know touches you wrongly, say no, get away, and tell a trusted adult. Call 1098.",
      hi: "कोई जान-पहचान वाला गलत छुए तो 'ना' कहो, वहां से हटो और भरोसेमंद बड़े को बताओ। 1098 पर कॉल करो।",
    },
  },

  // ───────────── LEGAL INFORMATION ─────────────
  {
    id: "zero_fir",
    intent: "learn",
    title: { mr: "पोलिस तक्रार व Zero FIR", en: "Police complaint & Zero FIR", hi: "पुलिस शिकायत और Zero FIR" },
    keywords: [
      "zero fir",
      "fir",
      "police complaint",
      "how to file fir",
      "e-fir",
      "online fir",
      "police not taking complaint",
      "तक्रार कशी करायची",
      "पोलिस तक्रार घेत नाहीत",
      "एफआयआर",
      "पुलिस शिकायत नहीं लेती",
      "एफआईआर कैसे करें",
      "police complaint kaise kare",
      "takrar kashi karaychi",
      "police sunat nahi",
      "complaint dena hai",
    ],
    understand: {
      mr: "तक्रार करायची पण प्रक्रिया माहीत नाही — हे अगदी सामान्य आहे. तुमचे हक्क काय आहेत ते पाहूया.",
      en: "Wanting to complain but not knowing the process is very common. Here are your rights.",
      hi: "शिकायत करनी है पर प्रक्रिया नहीं पता — यह बिल्कुल आम है। आपके हक जानिए।",
    },
    answer: [
      {
        mr: "Zero FIR: गुन्हा कुठेही घडला असला तरी कोणत्याही पोलिस ठाण्यात FIR नोंदवता येते.",
        en: "Zero FIR: you can file an FIR at any police station, wherever the crime happened.",
        hi: "Zero FIR: अपराध कहीं भी हुआ हो, किसी भी थाने में FIR दर्ज हो सकती है।",
      },
      {
        mr: "लैंगिक गुन्ह्यांमध्ये जबाब महिला पोलिस अधिकारी घेते; तुम्ही घरी जबाब देण्याची मागणी करू शकता.",
        en: "In sexual offences, a woman officer records your statement; you may ask to give it at home.",
        hi: "यौन अपराधों में बयान महिला पुलिस अधिकारी लेती है; आप घर पर बयान की मांग कर सकती हैं।",
      },
      {
        mr: "काही तक्रारी e-FIR / ऑनलाइन करता येतात; ऑनलाइन फसवणुकीसाठी cybercrime.gov.in किंवा 1930.",
        en: "Some complaints can be filed as e-FIR online; for online crimes use cybercrime.gov.in or 1930.",
        hi: "कुछ शिकायतें e-FIR से ऑनलाइन होती हैं; ऑनलाइन अपराध के लिए cybercrime.gov.in या 1930।",
      },
      {
        mr: "FIR ची मोफत प्रत मिळणे तुमचा हक्क आहे. पोलिस तक्रार घेत नसतील तर SP कडे लेखी तक्रार करा.",
        en: "You have a right to a free FIR copy. If police refuse, send a written complaint to the SP.",
        hi: "FIR की मुफ्त कॉपी आपका हक है। पुलिस मना करे तो SP को लिखित शिकायत भेजें।",
      },
      {
        mr: "गुंतागुंतीचे प्रकरण असेल तर मोफत कायदेशीर मदत (15100) घ्या.",
        en: "For complicated cases, get free legal aid (15100).",
        hi: "जटिल मामलों में मुफ्त कानूनी सहायता (15100) लें।",
      },
    ],
    next: {
      mr: "तक्रार कशाबद्दल आहे? आत्ता धोका असेल तर 112 ला फोन करा.",
      en: "What is the complaint about? If you are in danger now, call 112.",
      hi: "शिकायत किस बारे में है? अभी खतरा हो तो 112 पर कॉल करें।",
    },
    actions: [
      { label: { mr: "112 ला कॉल करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
      { label: { mr: "सायबर तक्रार", en: "Cybercrime portal", hi: "साइबर शिकायत" }, href: "https://cybercrime.gov.in" },
      { label: { mr: "15100 मोफत कायदा मदत", en: "Call 15100 Legal Aid", hi: "15100 मुफ्त कानूनी मदद" }, href: "tel:15100" },
    ],
    sensitive: "legal",
  },
  {
    id: "legal_aid",
    intent: "find",
    title: { mr: "मोफत कायदेशीर मदत", en: "Free legal aid", hi: "मुफ्त कानूनी सहायता" },
    keywords: [
      "free legal aid",
      "free lawyer",
      "nalsa",
      "dlsa",
      "legal services authority",
      "15100",
      "मोफत वकील",
      "वकील परवडत नाही",
      "कायदेशीर मदत",
      "मुफ्त वकील",
      "वकील का खर्च नहीं",
      "कानूनी सहायता",
      "free vakil",
      "mofat vakil",
      "vakil chahiye",
      "lawyer chahiye",
    ],
    understand: {
      mr: "वकिलाचा खर्च परवडत नसेल तरी काळजी करू नका — महिलांना मोफत कायदेशीर मदतीचा हक्क आहे.",
      en: "Don't worry if you can't afford a lawyer — women have a right to free legal aid.",
      hi: "वकील का खर्च नहीं उठा सकतीं तो चिंता न करें — महिलाओं को मुफ्त कानूनी सहायता का हक है।",
    },
    answer: [
      {
        mr: "कायद्यानुसार सर्व महिला, उत्पन्न कितीही असो, मोफत कायदेशीर मदतीस पात्र आहेत.",
        en: "Under the law, all women are eligible for free legal aid, regardless of income.",
        hi: "कानून के तहत सभी महिलाएं, आमदनी चाहे जो हो, मुफ्त कानूनी सहायता की हकदार हैं।",
      },
      {
        mr: "जिल्हा विधी सेवा प्राधिकरण (DLSA) रायगड — अलिबाग जिल्हा न्यायालयात कार्यालय असते.",
        en: "District Legal Services Authority (DLSA) Raigad — office at the district court, Alibag.",
        hi: "जिला विधिक सेवा प्राधिकरण (DLSA) रायगढ़ — कार्यालय अलीबाग जिला न्यायालय में।",
      },
      {
        mr: "श्रीवर्धन तालुका न्यायालयातही तालुका विधी सेवा समिती मदत करते.",
        en: "The Taluka Legal Services Committee at the Shrivardhan court can also help.",
        hi: "श्रीवर्धन तालुका न्यायालय में तालुका विधिक सेवा समिति भी मदद करती है।",
      },
      {
        mr: "NALSA हेल्पलाइन 15100 वर फोन करून सल्ला व वकील मिळवता येतो.",
        en: "Call NALSA helpline 15100 for guidance and to get a lawyer assigned.",
        hi: "NALSA हेल्पलाइन 15100 पर कॉल करके सलाह और वकील पा सकती हैं।",
      },
    ],
    next: {
      mr: "आत्ता 15100 वर फोन करून तुमचं प्रकरण सांगायचं आहे का?",
      en: "Would you like to call 15100 now and explain your case?",
      hi: "क्या आप अभी 15100 पर कॉल करके अपना मामला बताना चाहेंगी?",
    },
    actions: [
      { label: { mr: "15100 मोफत कायदा मदत", en: "Call 15100 Legal Aid", hi: "15100 मुफ्त कानूनी मदद" }, href: "tel:15100" },
    ],
    sensitive: "legal",
  },
  {
    id: "dowry",
    intent: "act",
    title: { mr: "हुंड्यासाठी छळ", en: "Dowry demands", hi: "दहेज के लिए प्रताड़ना" },
    keywords: [
      "dowry",
      "dowry harassment",
      "dowry demand",
      "हुंडा",
      "हुंडा मागतात",
      "माहेरून पैसे आण म्हणतात",
      "दहेज",
      "दहेज मांगते हैं",
      "मायके से पैसे लाओ",
      "dahej",
      "dahej mangte hai",
      "hunda",
      "maherun paise aan",
      "gaadi mangte hai",
      "498a",
    ],
    understand: {
      mr: "लग्नाआधी किंवा नंतर हुंडा किंवा माहेरून पैसे-वस्तू मागणे बेकायदेशीर आहे. तुम्ही हे सहन करायलाच हवं असं नाही.",
      en: "Demanding dowry, money or goods from your parents, before or after marriage, is illegal. You don't have to bear it.",
      hi: "शादी से पहले या बाद में दहेज या मायके से पैसे-सामान मांगना गैरकानूनी है। आपको यह सहना ज़रूरी नहीं।",
    },
    answer: [
      {
        mr: "हुंडा प्रतिबंधक कायदा 1961 नुसार हुंडा देणे, घेणे आणि मागणे गुन्हा आहे.",
        en: "Under the Dowry Prohibition Act 1961, giving, taking or demanding dowry is a crime.",
        hi: "दहेज प्रतिषेध अधिनियम 1961 के तहत दहेज देना, लेना और मांगना अपराध है।",
      },
      {
        mr: "हुंड्यासाठी छळ झाल्यास पोलिस तक्रार आणि घरगुती हिंसा कायद्याखाली मदत मिळू शकते.",
        en: "For dowry harassment, you can file a police complaint and seek help under the Domestic Violence Act.",
        hi: "दहेज प्रताड़ना पर पुलिस शिकायत और घरेलू हिंसा कानून के तहत मदद मिल सकती है।",
      },
      {
        mr: "मागणीचे मेसेज, साक्षीदार आणि दिलेल्या वस्तूंची यादी जपून ठेवा.",
        en: "Keep demand messages, witness names and a list of items given.",
        hi: "मांग वाले मैसेज, गवाह और दिए गए सामान की सूची संभालें।",
      },
      {
        mr: "181 किंवा मोफत कायदेशीर मदत 15100 कडून पुढची दिशा मिळेल.",
        en: "181 or free legal aid 15100 can guide your next steps.",
        hi: "181 या मुफ्त कानूनी सहायता 15100 आगे का रास्ता बताएंगे।",
      },
    ],
    next: {
      mr: "मारहाण किंवा धमकी होत आहे का? धोका असेल तर 112, नाहीतर 181 शी बोला.",
      en: "Is there violence or threats? If in danger call 112, otherwise talk to 181.",
      hi: "क्या मारपीट या धमकी हो रही है? खतरा हो तो 112, नहीं तो 181 से बात करें।",
    },
    actions: [
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
      { label: { mr: "15100 मोफत कायदा मदत", en: "Call 15100 Legal Aid", hi: "15100 मुफ्त कानूनी मदद" }, href: "tel:15100" },
    ],
    sensitive: "legal",
  },
  {
    id: "maintenance",
    intent: "learn",
    title: { mr: "पोटगी (खर्च) हक्क", en: "Right to maintenance", hi: "भरण-पोषण का हक" },
    keywords: [
      "maintenance",
      "alimony",
      "husband not giving money for children",
      "पोटगी",
      "पोटगी कशी मागायची",
      "मुलांचा खर्च देत नाही",
      "नवरा सोडून गेला",
      "गुज़ारा भत्ता",
      "भरण पोषण",
      "बच्चों का खर्च नहीं देता",
      "potgi",
      "gujara bhatta",
      "kharcha nahi deta",
      "section 125",
      "पती खर्च देत नाही",
    ],
    understand: {
      mr: "नवरा तुमचा किंवा मुलांचा खर्च देत नसेल तर पोटगी मागण्याचा तुम्हाला कायदेशीर हक्क आहे.",
      en: "If your husband does not support you or your children, you have a legal right to claim maintenance.",
      hi: "अगर पति आपका या बच्चों का खर्च नहीं देता, तो भरण-पोषण मांगने का आपका कानूनी हक है।",
    },
    answer: [
      {
        mr: "स्वतःसाठी आणि मुलांसाठी पोटगी मागता येते; काही वेळा आई-वडीलही मागू शकतात.",
        en: "You can claim maintenance for yourself and your children; parents may also claim in some cases.",
        hi: "आप अपने और बच्चों के लिए भरण-पोषण मांग सकती हैं; कुछ मामलों में माता-पिता भी।",
      },
      {
        mr: "फौजदारी कायदा, घरगुती हिंसा कायदा आणि वैयक्तिक कायद्यांखाली अर्ज करता येतो.",
        en: "You can apply under criminal law, the Domestic Violence Act, or your personal law.",
        hi: "फौजदारी कानून, घरेलू हिंसा कानून या पर्सनल लॉ के तहत आवेदन कर सकती हैं।",
      },
      {
        mr: "केस चालू असतानाही तात्पुरती (अंतरिम) पोटगी मागता येते.",
        en: "You can ask for interim maintenance while the case is going on.",
        hi: "केस चलने के दौरान अंतरिम भरण-पोषण मांगा जा सकता है।",
      },
      {
        mr: "कोणता मार्ग योग्य ते ठरवायला मोफत कायदेशीर मदत (15100) घ्या.",
        en: "Get free legal aid (15100) to choose the right route for you.",
        hi: "सही रास्ता चुनने के लिए मुफ्त कानूनी सहायता (15100) लें।",
      },
    ],
    next: {
      mr: "15100 वर फोन करून तुमच्या परिस्थितीबद्दल सल्ला घ्यायचा आहे का?",
      en: "Would you like to call 15100 for guidance on your situation?",
      hi: "क्या आप अपनी स्थिति पर सलाह के लिए 15100 पर कॉल करेंगी?",
    },
    actions: [
      { label: { mr: "15100 मोफत कायदा मदत", en: "Call 15100 Legal Aid", hi: "15100 मुफ्त कानूनी मदद" }, href: "tel:15100" },
      { label: { mr: "योजना पाहा", en: "Ask about financial security", hi: "योजनाएं देखें" }, href: "/schemes" },
    ],
    sensitive: "legal",
  },
  {
    id: "divorce_separation",
    intent: "learn",
    title: { mr: "घटस्फोट / वेगळं राहणं", en: "Divorce & separation", hi: "तलाक / अलग रहना" },
    keywords: [
      "divorce",
      "separation",
      "want to leave husband",
      "mutual divorce",
      "घटस्फोट",
      "घटस्फोट कसा घ्यायचा",
      "वेगळं राहायचं आहे",
      "नवऱ्यापासून वेगळं",
      "तलाक",
      "तलाक कैसे लें",
      "पति से अलग रहना",
      "talaq",
      "talak kaise le",
      "ghatasphot",
      "vegla rahaycha",
      "alag rehna hai",
      "custody",
    ],
    understand: {
      mr: "घटस्फोट किंवा वेगळं राहण्याचा विचार करणं हा मोठा निर्णय आहे. तुमचे पर्याय समजून घेणं हे पहिलं पाऊल आहे.",
      en: "Thinking about divorce or separation is a big decision. Understanding your options is the first step.",
      hi: "तलाक या अलग रहने के बारे में सोचना बड़ा फैसला है। अपने विकल्प समझना पहला कदम है।",
    },
    answer: [
      {
        mr: "दोघांच्या संमतीने (mutual consent) किंवा ठराविक कारणांवर एकतर्फी घटस्फोट मागता येतो.",
        en: "Divorce can be by mutual consent, or sought by one side on specific legal grounds.",
        hi: "तलाक आपसी सहमति से, या कुछ कानूनी आधारों पर एक पक्ष द्वारा मांगा जा सकता है।",
      },
      {
        mr: "घटस्फोटाशिवायही न्यायिक विभक्ती किंवा घरगुती हिंसा कायद्याखाली संरक्षण मिळू शकते.",
        en: "Without divorce, judicial separation or protection under the DV Act are also options.",
        hi: "तलाक के बिना भी न्यायिक पृथक्करण या घरेलू हिंसा कानून के तहत सुरक्षा मिल सकती है।",
      },
      {
        mr: "पोटगी, मुलांचा ताबा आणि स्त्रीधन — याबद्दलही हक्क असतात.",
        en: "You also have rights about maintenance, child custody and streedhan.",
        hi: "भरण-पोषण, बच्चों की कस्टडी और स्त्रीधन पर भी आपके हक हैं।",
      },
      {
        mr: "नियम धर्मानुसार बदलतात, म्हणून वकील किंवा मोफत कायदेशीर मदत (15100) घ्या.",
        en: "Rules differ by personal law, so consult a lawyer or free legal aid (15100).",
        hi: "नियम पर्सनल लॉ के हिसाब से बदलते हैं, इसलिए वकील या मुफ्त कानूनी सहायता (15100) लें।",
      },
    ],
    next: {
      mr: "तुमच्यावर छळ होत आहे का? तसं असेल तर आधी सुरक्षेबद्दल बोलूया.",
      en: "Is there abuse involved? If so, let's talk about your safety first.",
      hi: "क्या कोई हिंसा हो रही है? तो पहले आपकी सुरक्षा पर बात करें।",
    },
    actions: [
      { label: { mr: "15100 मोफत कायदा मदत", en: "Call 15100 Legal Aid", hi: "15100 मुफ्त कानूनी मदद" }, href: "tel:15100" },
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
    ],
    sensitive: "legal",
  },
  {
    id: "property_rights",
    intent: "learn",
    title: { mr: "मालमत्तेत मुलीचा हक्क", en: "Property and inheritance rights", hi: "संपत्ति में बेटी का हक" },
    keywords: [
      "property rights",
      "inheritance",
      "daughter share in property",
      "ancestral property",
      "वडिलांच्या मालमत्तेत हक्क",
      "जमिनीत हिस्सा",
      "भाऊ हिस्सा देत नाहीत",
      "वारसा",
      "पिता की संपत्ति में हक",
      "बेटी का हिस्सा",
      "जमीन में हिस्सा",
      "property me hissa",
      "zaminit hissa",
      "bhau hissa det nahi",
      "saat baara",
      "7/12 naav",
      "विधवा हक्क",
    ],
    understand: {
      mr: "माहेरच्या किंवा सासरच्या मालमत्तेत तुमचा हक्क आहे का, हा प्रश्न अनेकींना पडतो. सामान्य माहिती पाहूया.",
      en: "Many women wonder whether they have a share in family property. Here is general information.",
      hi: "कई महिलाएं सोचती हैं कि क्या परिवार की संपत्ति में उनका हिस्सा है। सामान्य जानकारी देखें।",
    },
    answer: [
      {
        mr: "हिंदू वारसा (सुधारणा) कायदा 2005 नुसार वडिलोपार्जित मालमत्तेत मुलीला मुलाइतकाच हक्क आहे.",
        en: "Under the Hindu Succession (Amendment) Act 2005, daughters have equal coparcenary rights in ancestral property.",
        hi: "हिंदू उत्तराधिकार (संशोधन) अधिनियम 2005 के तहत पैतृक संपत्ति में बेटी को बेटे के बराबर हक है।",
      },
      {
        mr: "लग्न झालं तरी हा हक्क संपत नाही.",
        en: "This right does not end after marriage.",
        hi: "शादी के बाद भी यह हक खत्म नहीं होता।",
      },
      {
        mr: "मुस्लिम, ख्रिश्चन, पारशी यांचे वैयक्तिक कायदे वेगळे आहेत.",
        en: "Muslim, Christian and Parsi personal laws have different rules.",
        hi: "मुस्लिम, ईसाई और पारसी पर्सनल लॉ के नियम अलग हैं।",
      },
      {
        mr: "७/१२ वर नाव, वाटणी किंवा वादासाठी मोफत कायदेशीर मदत (15100) घ्या.",
        en: "For land records, partition or disputes, get free legal aid (15100).",
        hi: "ज़मीन के रिकॉर्ड, बंटवारे या विवाद के लिए मुफ्त कानूनी सहायता (15100) लें।",
      },
    ],
    next: {
      mr: "तुमचा प्रश्न माहेरच्या की सासरच्या मालमत्तेबद्दल आहे? 15100 वर सविस्तर सल्ला मिळेल.",
      en: "Is your question about your parents' or in-laws' property? 15100 can guide you in detail.",
      hi: "आपका सवाल मायके की या ससुराल की संपत्ति के बारे में है? 15100 पर विस्तार से सलाह मिलेगी।",
    },
    actions: [
      { label: { mr: "15100 मोफत कायदा मदत", en: "Call 15100 Legal Aid", hi: "15100 मुफ्त कानूनी मदद" }, href: "tel:15100" },
    ],
    sensitive: "legal",
  },
  {
    id: "child_marriage",
    intent: "act",
    title: { mr: "बालविवाह", en: "Child marriage", hi: "बाल विवाह" },
    keywords: [
      "child marriage",
      "underage marriage",
      "forced marriage minor",
      "बालविवाह",
      "लहान वयात लग्न",
      "18 च्या आधी लग्न",
      "माझं लग्न लावून देतायत",
      "बाल विवाह",
      "कम उम्र में शादी",
      "18 से पहले शादी",
      "baal vivah",
      "balvivah",
      "lahan vayat lagna",
      "kam umar me shaadi",
      "shaadi zabardasti",
    ],
    understand: {
      mr: "मुलीचे 18 आणि मुलाचे 21 वर्षांआधी लग्न लावणे बेकायदेशीर आहे. हे थांबवता येते.",
      en: "Marriage of a girl under 18 or a boy under 21 is illegal. It can be stopped.",
      hi: "18 साल से कम लड़की और 21 साल से कम लड़के की शादी गैरकानूनी है। इसे रोका जा सकता है।",
    },
    answer: [
      {
        mr: "बालविवाह प्रतिबंधक कायदा 2006 नुसार हा गुन्हा आहे.",
        en: "It is a crime under the Prohibition of Child Marriage Act 2006.",
        hi: "बाल विवाह प्रतिषेध अधिनियम 2006 के तहत यह अपराध है।",
      },
      {
        mr: "लग्न ठरवणारे, लावणारे आणि त्यात सहभागी होणाऱ्यांवरही कारवाई होऊ शकते.",
        en: "Action can be taken against those who arrange, perform or take part in it.",
        hi: "शादी तय करने, कराने और उसमें शामिल लोगों पर भी कार्रवाई हो सकती है।",
      },
      {
        mr: "महाराष्ट्र बालविवाहमुक्त मोहिमेत ग्रामसेवक, अंगणवाडी सेविकाही कळवू शकतात.",
        en: "Under Maharashtra's campaign, Gram Sevaks and Anganwadi workers can also report it.",
        hi: "महाराष्ट्र के अभियान में ग्राम सेवक और आंगनवाड़ी कार्यकर्ता भी सूचना दे सकते हैं।",
      },
      {
        mr: "माहिती देण्यासाठी 1098 किंवा 112 ला फोन करा; नाव गुप्त ठेवता येते.",
        en: "Call 1098 or 112 to report; your name can be kept confidential.",
        hi: "सूचना देने के लिए 1098 या 112 पर कॉल करें; नाम गुप्त रखा जा सकता है।",
      },
    ],
    next: {
      mr: "लग्नाची तारीख ठरली आहे का? तर आत्ताच 1098 ला फोन करा.",
      en: "Has a wedding date been fixed? Then call 1098 now.",
      hi: "क्या शादी की तारीख तय हो गई है? तो अभी 1098 पर कॉल करें।",
    },
    actions: [
      { label: { mr: "1098 बाल मदत", en: "Call 1098 Childline", hi: "1098 चाइल्डलाइन" }, href: "tel:1098" },
      { label: { mr: "112 ला कॉल करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
    ],
    sensitive: "child",
    girlNote: {
      mr: "तुझं लग्न लावून देत असतील तर शिक्षिका, विश्वासू मोठ्या व्यक्तीला सांग किंवा 1098 ला फोन कर. शिकणं तुझा हक्क आहे.",
      en: "If they are arranging your marriage, tell a teacher or trusted adult, or call 1098. Studying is your right.",
      hi: "अगर तुम्हारी शादी करवा रहे हैं, तो टीचर या भरोसेमंद बड़े को बताओ, या 1098 पर कॉल करो। पढ़ना तुम्हारा हक है।",
    },
  },
  {
    id: "marriage_rights",
    intent: "learn",
    title: { mr: "लग्नातील हक्क", en: "Rights in marriage", hi: "शादी में अधिकार" },
    keywords: [
      "marriage rights",
      "marriage registration",
      "streedhan",
      "right to residence",
      "shared household",
      "लग्नाची नोंदणी",
      "स्त्रीधन",
      "दागिने परत देत नाहीत",
      "घरातून हाकलले",
      "विवाह पंजीकरण",
      "स्त्रीधन वापस नहीं देते",
      "घर से निकाल दिया",
      "lagna nondani",
      "stridhan",
      "dagine parat det nahi",
      "ghar se nikal diya",
      "marriage certificate",
    ],
    understand: {
      mr: "लग्नानंतरही तुमचे स्वतःचे हक्क असतात — नोंदणी, स्त्रीधन आणि राहण्याचे घर याबद्दल माहिती पाहूया.",
      en: "You keep your own rights after marriage — here is information about registration, streedhan and your home.",
      hi: "शादी के बाद भी आपके अपने अधिकार हैं — पंजीकरण, स्त्रीधन और घर के बारे में जानकारी देखें।",
    },
    answer: [
      {
        mr: "लग्नाची नोंदणी ग्रामपंचायत/नगरपरिषद किंवा विवाह निबंधकाकडे करा; पुढे खूप उपयोगी पडते.",
        en: "Register your marriage at the Gram Panchayat/Municipal Council or marriage registrar; it helps later.",
        hi: "शादी का पंजीकरण ग्राम पंचायत/नगर परिषद या विवाह रजिस्ट्रार के पास कराएं; बाद में काम आता है।",
      },
      {
        mr: "स्त्रीधन — दागिने, भेटवस्तू, पैसे — पूर्णपणे तुमचे आहे; ते परत मागता येते.",
        en: "Streedhan — jewellery, gifts, money — fully belongs to you; you can ask for it back.",
        hi: "स्त्रीधन — गहने, तोहफ़े, पैसे — पूरी तरह आपका है; आप इसे वापस मांग सकती हैं।",
      },
      {
        mr: "सामायिक घरात राहण्याचा हक्क आहे; घरगुती हिंसा कायद्यानुसार बेकायदेशीरपणे बाहेर काढता येत नाही.",
        en: "You have a right to live in the shared household; the DV Act protects you from illegal eviction.",
        hi: "साझा घर में रहने का हक है; घरेलू हिंसा कानून गैरकानूनी तरीके से निकाले जाने से बचाता है।",
      },
      {
        mr: "स्त्रीधनाची यादी आणि फोटो जपून ठेवा. वादासाठी मोफत कायदेशीर मदत 15100.",
        en: "Keep a list and photos of your streedhan. For disputes, free legal aid 15100.",
        hi: "स्त्रीधन की सूची और फोटो संभालें। विवाद हो तो मुफ्त कानूनी सहायता 15100।",
      },
    ],
    next: {
      mr: "तुम्हाला घरातून काढलं आहे की स्त्रीधन परत मिळत नाही? 15100 वर सल्ला घ्या.",
      en: "Have you been thrown out, or is your streedhan being held back? Call 15100 for guidance.",
      hi: "क्या आपको घर से निकाला गया है या स्त्रीधन नहीं लौटाया जा रहा? 15100 पर सलाह लें।",
    },
    actions: [
      { label: { mr: "15100 मोफत कायदा मदत", en: "Call 15100 Legal Aid", hi: "15100 मुफ्त कानूनी मदद" }, href: "tel:15100" },
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
    ],
    sensitive: "legal",
  },
];

export const mindTopics: Topic[] = [
  {
    id: "overwhelmed",
    intent: "check",
    title: { mr: "सगळं खूप जड वाटतंय", en: "I feel overwhelmed", hi: "सब बहुत भारी लग रहा है" },
    keywords: [
      "overwhelmed",
      "too much",
      "can't cope",
      "breaking down",
      "सगळं जड वाटतंय",
      "सहन होत नाही",
      "डोकं फुटेल",
      "काही सुचत नाही",
      "सब बहुत भारी है",
      "संभल नहीं रहा",
      "कुछ समझ नहीं आ रहा",
      "sab bahut bhari hai",
      "sahan hot nahi",
      "kahi suchat nahi",
      "thak gayi hoon",
      "थकले आहे",
    ],
    understand: {
      mr: "सगळ्या जबाबदाऱ्या एकदम अंगावर आल्यासारखं वाटणं खूप थकवणारं असतं. असं वाटणं कमजोरी नाही.",
      en: "When everything piles up at once, it is exhausting. Feeling this way is not weakness.",
      hi: "जब सारी ज़िम्मेदारियां एक साथ आ जाएं, तो बहुत थकान होती है। ऐसा महसूस करना कमज़ोरी नहीं है।",
    },
    answer: [
      {
        mr: "आत्ता फक्त एक श्वास: 4 मोजत श्वास घ्या, 4 थांबा, 6 मोजत सोडा.",
        en: "Right now, just one breath: in for 4, hold for 4, out for 6.",
        hi: "अभी बस एक सांस: 4 गिनकर लें, 4 रोकें, 6 गिनकर छोड़ें।",
      },
      {
        mr: "सगळं एकदम नको — आजचं फक्त एक छोटं काम निवडा.",
        en: "Not everything at once — pick just one small task for today.",
        hi: "सब एक साथ नहीं — आज बस एक छोटा काम चुनें।",
      },
      {
        mr: "एखादं काम घरातल्या कोणाला तरी वाटून द्या; मदत मागणं ठीक आहे.",
        en: "Share one task with someone at home; asking for help is okay.",
        hi: "कोई एक काम घर के किसी और को दें; मदद मांगना ठीक है।",
      },
      {
        mr: "असं रोज वाटत असेल तर Tele-MANAS 14416 वर मोफत बोला (24x7).",
        en: "If you feel this every day, talk free to Tele-MANAS 14416 (24x7).",
        hi: "अगर रोज़ ऐसा लगता है, तो Tele-MANAS 14416 पर मुफ्त बात करें (24x7)।",
      },
    ],
    next: {
      mr: "आत्ता सगळ्यात जास्त कशाचा ताण आहे? सांगितलंत तर आपण एक-एक पाहू.",
      en: "What is weighing on you most right now? Tell me and we'll take it one at a time.",
      hi: "अभी सबसे ज़्यादा किस बात का बोझ है? बताइए, हम एक-एक करके देखें।",
    },
    actions: [
      { label: { mr: "14416 मनाशी बोला", en: "Call Tele-MANAS 14416", hi: "14416 Tele-MANAS" }, href: "tel:14416" },
    ],
    sensitive: "crisis",
  },
  {
    id: "no_one_to_talk",
    intent: "connect",
    title: { mr: "कोणाशी बोलावंसं वाटत नाही", en: "Don't feel like talking", hi: "किसी से बात करने का मन नहीं" },
    keywords: [
      "don't feel like talking",
      "don't want to talk to anyone",
      "withdrawn",
      "कोणाशी बोलावंसं वाटत नाही",
      "बोलायची इच्छा नाही",
      "एकटंच राहावंसं वाटतं",
      "किसी से बात करने का मन नहीं",
      "अकेले रहना चाहती हूं",
      "मन नहीं करता",
      "kisi se baat karne ka mann nahi",
      "bolavasa vatat nahi",
      "mann nahi lagta",
      "chup chup rehti hoon",
      "ekta rahavasa vatta",
    ],
    understand: {
      mr: "कधी कधी कोणाशीच बोलावंसं वाटत नाही — ते ठीक आहे. मी इथे आहे, तुम्हाला हवं तितकंच सांगा.",
      en: "Sometimes you just don't want to talk to anyone — that's okay. I'm here; share only as much as you want.",
      hi: "कभी-कभी किसी से बात करने का मन नहीं करता — यह ठीक है। मैं यहां हूं; जितना चाहें उतना ही बताएं।",
    },
    answer: [
      {
        mr: "बोलायचं नसेल तर लिहून पाहा — वहीत मनातलं लिहिल्याने हलकं वाटतं.",
        en: "If talking is hard, try writing — putting thoughts on paper can lighten them.",
        hi: "बोलना मुश्किल हो तो लिखकर देखें — मन की बात कागज़ पर लिखने से हल्का लगता है।",
      },
      {
        mr: "थोडं बाहेर चालणं, उन्हात बसणं किंवा आवडतं गाणं ऐकणं मदत करू शकतं.",
        en: "A short walk, sitting in sunlight or a favourite song can help a little.",
        hi: "थोड़ा टहलना, धूप में बैठना या पसंदीदा गाना सुनना थोड़ी मदद कर सकता है।",
      },
      {
        mr: "हे दोन आठवड्यांपेक्षा जास्त चालू असेल तर ते उदासपणाचं लक्षण असू शकतं.",
        en: "If this lasts more than two weeks, it may be a sign of depression.",
        hi: "अगर यह दो हफ्ते से ज़्यादा चले, तो यह डिप्रेशन का संकेत हो सकता है।",
      },
      {
        mr: "अनोळखी पण प्रशिक्षित व्यक्तीशी बोलणं सोपं जातं — Tele-MANAS 14416.",
        en: "Talking to a trained stranger can feel easier — Tele-MANAS 14416.",
        hi: "किसी अनजान पर प्रशिक्षित व्यक्ति से बात करना आसान लग सकता है — Tele-MANAS 14416।",
      },
    ],
    next: {
      mr: "हे किती दिवसांपासून वाटतंय? तुम्हाला हवं तर मी फक्त ऐकते.",
      en: "How long have you been feeling this way? If you like, I'll just listen.",
      hi: "यह कब से महसूस हो रहा है? चाहें तो मैं बस सुनूंगी।",
    },
    actions: [
      { label: { mr: "14416 मनाशी बोला", en: "Call Tele-MANAS 14416", hi: "14416 Tele-MANAS" }, href: "tel:14416" },
    ],
    sensitive: "crisis",
  },
  {
    id: "anxious",
    intent: "check",
    title: { mr: "सतत काळजी वाटते", en: "I feel anxious all the time", hi: "हर समय घबराहट होती है" },
    keywords: [
      "anxiety",
      "anxious",
      "panic",
      "worried all the time",
      "heart racing",
      "सतत काळजी वाटते",
      "भीती वाटते",
      "छातीत धडधड",
      "अस्वस्थ वाटतं",
      "घबराहट",
      "हर समय चिंता",
      "दिल की धड़कन तेज़",
      "ghabrahat hoti hai",
      "chinta hoti hai",
      "kalji vatte",
      "dhadhad hote",
      "tension",
    ],
    understand: {
      mr: "सतत काळजी, छातीत धडधड किंवा अस्वस्थपणा — याला चिंता (anxiety) म्हणतात. हे खूप सामान्य आहे आणि यावर मदत मिळते.",
      en: "Constant worry, a racing heart or restlessness may be anxiety. It is very common and help is available.",
      hi: "लगातार चिंता, दिल की तेज़ धड़कन या बेचैनी एंग्ज़ायटी हो सकती है। यह बहुत आम है और इसमें मदद मिलती है।",
    },
    answer: [
      {
        mr: "4-4-6 श्वास: 4 मोजत घ्या, 4 थांबा, 6 मोजत सोडा — 5 वेळा.",
        en: "4-4-6 breathing: in for 4, hold 4, out for 6 — five times.",
        hi: "4-4-6 सांस: 4 गिनकर लें, 4 रोकें, 6 गिनकर छोड़ें — पांच बार।",
      },
      {
        mr: "आजूबाजूच्या 5 गोष्टी पाहा, 4 ऐका, 3 ला स्पर्श करा — मन 'आत्ता'त येतं.",
        en: "Notice 5 things you see, 4 you hear, 3 you can touch — it brings you to now.",
        hi: "5 चीज़ें देखें, 4 सुनें, 3 छुएं — मन 'अभी' में लौटता है।",
      },
      {
        mr: "चहा-कॉफी कमी करा, झोप नियमित ठेवा आणि रोज थोडं चाला.",
        en: "Cut down on tea/coffee, keep regular sleep and walk a little daily.",
        hi: "चाय-कॉफी कम करें, नींद नियमित रखें और रोज़ थोड़ा टहलें।",
      },
      {
        mr: "रोजच्या कामावर परिणाम होत असेल तर Tele-MANAS 14416 किंवा डॉक्टरांशी बोला.",
        en: "If it affects daily life, talk to Tele-MANAS 14416 or a doctor.",
        hi: "अगर रोज़मर्रा पर असर हो रहा है, तो Tele-MANAS 14416 या डॉक्टर से बात करें।",
      },
    ],
    next: {
      mr: "आत्ता एकदा 4-4-6 श्वास घेऊन पाहूया का?",
      en: "Shall we try one round of 4-4-6 breathing right now?",
      hi: "क्या अभी एक बार 4-4-6 सांस लेकर देखें?",
    },
    actions: [
      { label: { mr: "14416 मनाशी बोला", en: "Call Tele-MANAS 14416", hi: "14416 Tele-MANAS" }, href: "tel:14416" },
      { label: { mr: "रोजची काळजी", en: "Everyday wellbeing", hi: "रोज़मर्रा की देखभाल" }, href: "/everyday" },
    ],
  },
  {
    id: "postpartum_struggle",
    intent: "check",
    title: { mr: "बाळंतपणानंतर त्रास", en: "Struggling after childbirth", hi: "डिलीवरी के बाद परेशानी" },
    keywords: [
      "postpartum depression",
      "after delivery sad",
      "baby blues",
      "struggling after childbirth",
      "बाळंतपणानंतर रडू येतं",
      "बाळाकडे बघावंसं वाटत नाही",
      "डिलिव्हरीनंतर उदास",
      "डिलीवरी के बाद उदासी",
      "बच्चे के बाद रोना आता है",
      "प्रसव के बाद डिप्रेशन",
      "delivery ke baad udaas",
      "balantpananantar",
      "bacche ke baad rona",
      "new mother stress",
      "mom guilt",
      "नवीन आई",
    ],
    understand: {
      mr: "बाळंतपणानंतर उदास वाटणं, रडू येणं किंवा बाळाशी नातं जाणवत नसणं — हे अनेक मातांना होतं. तुम्ही वाईट आई नाही.",
      en: "Feeling sad, tearful or disconnected from your baby after childbirth happens to many mothers. You are not a bad mother.",
      hi: "डिलीवरी के बाद उदासी, रोना या बच्चे से जुड़ाव न लगना कई माताओं के साथ होता है। आप बुरी मां नहीं हैं।",
    },
    answer: [
      {
        mr: "पहिले 2 आठवडे 'बेबी ब्लूज' सामान्य आहेत; जास्त काळ राहिलं तर प्रसूतीनंतरचं नैराश्य असू शकतो.",
        en: "'Baby blues' in the first 2 weeks are common; if it lasts longer, it may be postpartum depression.",
        hi: "पहले 2 हफ्ते 'बेबी ब्लूज़' आम है; ज़्यादा चले तो पोस्टपार्टम डिप्रेशन हो सकता है।",
      },
      {
        mr: "प्रसूतीनंतरचं नैराश्य सामान्य आहे आणि उपचाराने पूर्ण बरं होतं.",
        en: "Postpartum depression is common and fully treatable.",
        hi: "पोस्टपार्टम डिप्रेशन आम है और इलाज से पूरी तरह ठीक होता है।",
      },
      {
        mr: "झोप मिळावी म्हणून रात्री बाळाची जबाबदारी घरच्यांसोबत वाटा.",
        en: "Share night-time baby care with family so you can sleep.",
        hi: "रात में बच्चे की देखभाल घरवालों के साथ बांटें ताकि आप सो सकें।",
      },
      {
        mr: "आशा ताई, PHC डॉक्टर किंवा Tele-MANAS 14416 शी बोला.",
        en: "Talk to your ASHA worker, PHC doctor or Tele-MANAS 14416.",
        hi: "आशा दीदी, PHC डॉक्टर या Tele-MANAS 14416 से बात करें।",
      },
      {
        mr: "स्वतःला किंवा बाळाला इजा करण्याचे विचार आले तर लगेच 14416 किंवा 112.",
        en: "If you have thoughts of harming yourself or the baby, call 14416 or 112 right away.",
        hi: "अगर खुद को या बच्चे को नुकसान पहुंचाने के विचार आएं, तो तुरंत 14416 या 112 पर कॉल करें।",
      },
    ],
    next: {
      mr: "हे किती दिवसांपासून वाटतंय? घरात कोणी तुमची मदत करतंय का?",
      en: "How long have you felt this way? Is anyone at home helping you?",
      hi: "यह कब से महसूस हो रहा है? क्या घर में कोई आपकी मदद कर रहा है?",
    },
    actions: [
      { label: { mr: "14416 मनाशी बोला", en: "Call Tele-MANAS 14416", hi: "14416 Tele-MANAS" }, href: "tel:14416" },
      { label: { mr: "रोजची काळजी", en: "Everyday wellbeing", hi: "रोज़मर्रा की देखभाल" }, href: "/everyday" },
    ],
    sensitive: "crisis",
    ages: ["18", "30", "40"],
  },
  {
    id: "grieving",
    intent: "check",
    title: { mr: "कोणी गेल्याचं दुःख", en: "I am grieving", hi: "किसी के जाने का दुख" },
    keywords: [
      "grief",
      "grieving",
      "someone died",
      "lost my husband",
      "lost my mother",
      "miscarriage",
      "दुःख",
      "कोणी गेलं",
      "आई गेली",
      "नवरा गेला",
      "किसी की मौत",
      "मां चली गई",
      "गर्भपात हो गया",
      "koi chala gaya",
      "dukh hai",
      "ai geli",
      "bereavement",
    ],
    understand: {
      mr: "जवळची व्यक्ती गेल्याचं दुःख खूप खोल असतं. दुःख करण्याची कोणतीही 'बरोबर' पद्धत किंवा वेळ नसते.",
      en: "Losing someone close is a deep pain. There is no 'right' way or timeline to grieve.",
      hi: "किसी करीबी को खोने का दुख बहुत गहरा होता है। दुख मनाने का कोई 'सही' तरीका या समय नहीं होता।",
    },
    answer: [
      {
        mr: "रडू येणं, राग, थकवा, सुन्नपणा — सगळं दुःखात साहजिक आहे.",
        en: "Tears, anger, tiredness, numbness — all are natural in grief.",
        hi: "रोना, गुस्सा, थकान, सुन्नपन — दुख में सब स्वाभाविक है।",
      },
      {
        mr: "त्या व्यक्तीच्या आठवणी कोणासोबत तरी बोला; मन मोकळं होतं.",
        en: "Share memories of that person with someone; it eases the heart.",
        hi: "उस व्यक्ति की यादें किसी के साथ बांटें; मन हल्का होता है।",
      },
      {
        mr: "जेवण, पाणी आणि झोप — स्वतःची किमान काळजी घ्या.",
        en: "Food, water and sleep — take at least basic care of yourself.",
        hi: "खाना, पानी और नींद — अपना कम से कम ध्यान रखें।",
      },
      {
        mr: "दुःख खूप दिवस जड वाटत असेल तर Tele-MANAS 14416 वर बोला.",
        en: "If the grief stays very heavy for long, talk to Tele-MANAS 14416.",
        hi: "अगर दुख बहुत दिनों तक भारी रहे, तो Tele-MANAS 14416 पर बात करें।",
      },
    ],
    next: {
      mr: "तुम्हाला त्यांच्याबद्दल काही सांगायचं आहे का? मी ऐकते.",
      en: "Would you like to tell me about them? I'm listening.",
      hi: "क्या आप उनके बारे में कुछ बताना चाहेंगी? मैं सुन रही हूं।",
    },
    actions: [
      { label: { mr: "14416 मनाशी बोला", en: "Call Tele-MANAS 14416", hi: "14416 Tele-MANAS" }, href: "tel:14416" },
    ],
    sensitive: "crisis",
    girlNote: {
      mr: "दुःख खूप जड वाटत असेल तर विश्वासू मोठ्या व्यक्तीशी बोल किंवा 1098 ला फोन कर.",
      en: "If the sadness feels too heavy, talk to a trusted adult or call 1098.",
      hi: "अगर दुख बहुत भारी लगे, तो किसी भरोसेमंद बड़े से बात करो या 1098 पर कॉल करो।",
    },
  },
  {
    id: "family_pressure",
    intent: "check",
    title: { mr: "घरच्यांचा दबाव", en: "Family pressure", hi: "परिवार का दबाव" },
    keywords: [
      "family pressure",
      "pressure to marry",
      "pressure to have baby",
      "not allowed to work",
      "लग्नासाठी दबाव",
      "मूल कधी म्हणून विचारतात",
      "नोकरी करू देत नाहीत",
      "घरचे ऐकत नाहीत",
      "शादी का दबाव",
      "बच्चे का दबाव",
      "नौकरी नहीं करने देते",
      "shaadi ka pressure",
      "lagnasathi dabav",
      "baby kab",
      "career chhodna pada",
      "ghar wale nahi maante",
    ],
    understand: {
      mr: "लग्न, नोकरी किंवा मूल याबद्दल घरच्यांचा दबाव खूप थकवणारा असतो. तुमच्या इच्छांनाही महत्त्व आहे.",
      en: "Family pressure about marriage, career or children can be exhausting. Your wishes matter too.",
      hi: "शादी, करियर या बच्चे को लेकर परिवार का दबाव बहुत थकाने वाला होता है। आपकी इच्छाएं भी मायने रखती हैं।",
    },
    answer: [
      {
        mr: "तुम्हाला काय हवं आहे ते आधी स्वतःसाठी स्पष्ट लिहून काढा.",
        en: "First write down clearly, for yourself, what you want.",
        hi: "पहले अपने लिए साफ़ लिखें कि आप क्या चाहती हैं।",
      },
      {
        mr: "घरातल्या एखाद्या समजूतदार व्यक्तीला तुमच्या बाजूने बोलायला सांगा.",
        en: "Ask one understanding family member to speak up for you.",
        hi: "घर के किसी समझदार सदस्य से अपनी बात रखने को कहें।",
      },
      {
        mr: "शांत वेळी, 'मला असं वाटतं' अशा शब्दांत बोला — भांडणाऐवजी संवाद.",
        en: "Talk at a calm time using 'I feel' words — conversation, not a fight.",
        hi: "शांत समय पर 'मुझे ऐसा लगता है' कहकर बात करें — झगड़ा नहीं, बातचीत।",
      },
      {
        mr: "जबरदस्ती लग्न किंवा धमकी असेल तर 181 किंवा 112 वर मदत मिळते.",
        en: "If there is forced marriage or threats, 181 or 112 can help.",
        hi: "अगर ज़बरदस्ती शादी या धमकी हो, तो 181 या 112 से मदद मिलती है।",
      },
    ],
    next: {
      mr: "दबाव कशाबद्दल आहे — लग्न, नोकरी की मूल? सांगा, आपण पुढे पाहू.",
      en: "What is the pressure about — marriage, career or children? Tell me and we'll look further.",
      hi: "दबाव किस बारे में है — शादी, करियर या बच्चे? बताइए, आगे देखते हैं।",
    },
    actions: [
      { label: { mr: "14416 मनाशी बोला", en: "Call Tele-MANAS 14416", hi: "14416 Tele-MANAS" }, href: "tel:14416" },
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
    ],
    girlNote: {
      mr: "18 वर्षांखाली लग्नासाठी दबाव असेल तर 1098 ला फोन कर — हे बेकायदेशीर आहे.",
      en: "If you're under 18 and pressured to marry, call 1098 — it is illegal.",
      hi: "अगर 18 से कम उम्र में शादी का दबाव है, तो 1098 पर कॉल करो — यह गैरकानूनी है।",
    },
  },
  {
    id: "lonely",
    intent: "check",
    title: { mr: "एकटं वाटतंय", en: "I feel lonely", hi: "अकेलापन लगता है" },
    keywords: [
      "lonely",
      "loneliness",
      "no friends",
      "alone",
      "एकटं वाटतं",
      "कोणी नाही माझं",
      "मैत्रिणी नाहीत",
      "सासरी एकटी पडले",
      "अकेलापन",
      "कोई नहीं है मेरा",
      "अकेली हूं",
      "akelapan",
      "akeli hoon",
      "ekta vatta",
      "koni nahi maza",
      "नवरा बाहेरगावी",
    ],
    understand: {
      mr: "आजूबाजूला लोक असूनही एकटं वाटू शकतं — विशेषतः लग्नानंतर नव्या गावात. हे खूप जणींना जाणवतं.",
      en: "You can feel lonely even with people around — especially after moving for marriage. Many women feel this.",
      hi: "लोगों के बीच रहकर भी अकेलापन लग सकता है — खासकर शादी के बाद नई जगह पर। कई महिलाएं ऐसा महसूस करती हैं।",
    },
    answer: [
      {
        mr: "आठवड्यात एकदा तरी जुन्या मैत्रिणीला किंवा माहेरी फोन करा.",
        en: "Call an old friend or your parents at least once a week.",
        hi: "हफ्ते में कम से कम एक बार पुरानी सहेली या मायके फोन करें।",
      },
      {
        mr: "बचत गट, महिला मंडळ किंवा भजनी मंडळात सामील व्हा — नवीन ओळखी होतात.",
        en: "Join a self-help group, mahila mandal or bhajan group — you'll meet people.",
        hi: "स्वयं सहायता समूह, महिला मंडल या भजन मंडली से जुड़ें — नए लोग मिलेंगे।",
      },
      {
        mr: "रोज स्वतःसाठी 10 मिनिटं — आवडतं काम, गाणं किंवा चालणं.",
        en: "Take 10 minutes daily for yourself — a hobby, a song or a walk.",
        hi: "रोज़ 10 मिनट अपने लिए — कोई शौक, गाना या टहलना।",
      },
      {
        mr: "एकटेपणा खूप जड वाटत असेल तर Tele-MANAS 14416 वर बोला.",
        en: "If loneliness feels very heavy, talk to Tele-MANAS 14416.",
        hi: "अगर अकेलापन बहुत भारी लगे, तो Tele-MANAS 14416 पर बात करें।",
      },
    ],
    next: {
      mr: "तुमच्या गावात बचत गट किंवा महिला मंडळ आहे का? योजना पाहूया का?",
      en: "Is there a self-help group or mahila mandal near you? Shall we look at schemes?",
      hi: "क्या आपके पास कोई स्वयं सहायता समूह या महिला मंडल है? क्या योजनाएं देखें?",
    },
    actions: [
      { label: { mr: "14416 मनाशी बोला", en: "Call Tele-MANAS 14416", hi: "14416 Tele-MANAS" }, href: "tel:14416" },
      { label: { mr: "योजना पाहा", en: "Ask about financial security", hi: "योजनाएं देखें" }, href: "/schemes" },
    ],
  },
  {
    id: "stress",
    intent: "learn",
    title: { mr: "ताण कसा कमी करायचा", en: "Handling emotional stress", hi: "तनाव कैसे कम करें" },
    keywords: [
      "stress",
      "stressed",
      "tension",
      "how to relax",
      "breathing exercise",
      "ताण",
      "टेन्शन आलंय",
      "मन शांत कसं करायचं",
      "झोप येत नाही",
      "तनाव",
      "मन शांत कैसे करें",
      "नींद नहीं आती",
      "tension hai",
      "man shant kasa karaycha",
      "neend nahi aati",
      "zop yet nahi",
      "relax",
    ],
    understand: {
      mr: "घर, काम, पैसे, मुलं — या सगळ्यांचा ताण येणं साहजिक आहे. काही सोप्या गोष्टी मदत करू शकतात.",
      en: "Stress from home, work, money and children is natural. A few simple things can help.",
      hi: "घर, काम, पैसे, बच्चे — इन सबका तनाव होना स्वाभाविक है। कुछ आसान बातें मदद कर सकती हैं।",
    },
    answer: [
      {
        mr: "4-4-6 श्वास: 4 मोजत घ्या, 4 थांबा, 6 मोजत हळू सोडा. 5 वेळा करा.",
        en: "4-4-6 breathing: in for 4, hold 4, slowly out for 6. Repeat 5 times.",
        hi: "4-4-6 सांस: 4 गिनकर लें, 4 रोकें, 6 गिनकर धीरे छोड़ें। 5 बार करें।",
      },
      {
        mr: "रोज ठराविक वेळी झोपा; झोपण्याआधी अर्धा तास फोन बाजूला ठेवा.",
        en: "Sleep at a fixed time; keep the phone away for half an hour before bed.",
        hi: "रोज़ तय समय पर सोएं; सोने से आधा घंटा पहले फोन दूर रखें।",
      },
      {
        mr: "रोज 15-20 मिनिटं चाला — किनाऱ्यावर किंवा अंगणात.",
        en: "Walk 15–20 minutes a day — on the beach or in the courtyard.",
        hi: "रोज़ 15-20 मिनट टहलें — समुद्र किनारे या आंगन में।",
      },
      {
        mr: "मनातलं कोणाशी तरी बोला; गरज वाटल्यास Tele-MANAS 14416.",
        en: "Talk to someone about what's on your mind; if needed, Tele-MANAS 14416.",
        hi: "मन की बात किसी से कहें; ज़रूरत हो तो Tele-MANAS 14416।",
      },
    ],
    next: {
      mr: "आत्ता एकदा 4-4-6 श्वास घेऊन पाहाल का?",
      en: "Would you try one round of 4-4-6 breathing right now?",
      hi: "क्या आप अभी एक बार 4-4-6 सांस लेकर देखेंगी?",
    },
    actions: [
      { label: { mr: "रोजची काळजी", en: "Everyday wellbeing", hi: "रोज़मर्रा की देखभाल" }, href: "/everyday" },
      { label: { mr: "14416 मनाशी बोला", en: "Call Tele-MANAS 14416", hi: "14416 Tele-MANAS" }, href: "tel:14416" },
    ],
  },
  {
    id: "counsellor",
    intent: "connect",
    title: { mr: "समुपदेशकाशी बोलायचं आहे", en: "Talk to a counsellor", hi: "काउंसलर से बात करनी है" },
    keywords: [
      "counsellor",
      "counselor",
      "therapist",
      "talk to someone",
      "mental health help",
      "tele manas",
      "14416",
      "समुपदेशक",
      "मानसिक आरोग्य",
      "कोणाशी तरी बोलायचं आहे",
      "काउंसलर",
      "मानसिक स्वास्थ्य",
      "किसी से बात करनी है",
      "counsellor chahiye",
      "kisi se baat karni hai",
      "konashi tari bolaycha",
      "psychologist",
    ],
    understand: {
      mr: "कोणाशी तरी बोलायचं ठरवणं हे धैर्याचं पाऊल आहे. मोफत आणि गोपनीय मदत उपलब्ध आहे.",
      en: "Deciding to talk to someone is a brave step. Free and confidential help is available.",
      hi: "किसी से बात करने का फैसला हिम्मत का कदम है। मुफ्त और गोपनीय मदद उपलब्ध है।",
    },
    answer: [
      {
        mr: "Tele-MANAS 14416 — मोफत, 24x7, मराठी आणि हिंदीत प्रशिक्षित समुपदेशक.",
        en: "Tele-MANAS 14416 — free, 24x7, trained counsellors in Marathi and Hindi.",
        hi: "Tele-MANAS 14416 — मुफ्त, 24x7, मराठी और हिंदी में प्रशिक्षित काउंसलर।",
      },
      {
        mr: "छळ किंवा हिंसेशी संबंधित असेल तर 181 वन स्टॉप सेंटरमध्येही समुपदेशन मिळते.",
        en: "If it relates to abuse or violence, 181 One Stop Centre also offers counselling.",
        hi: "अगर बात हिंसा से जुड़ी है, तो 181 वन स्टॉप सेंटर में भी काउंसलिंग मिलती है।",
      },
      {
        mr: "जिल्हा रुग्णालयात (अलिबाग) मानसिक आरोग्य OPD असते.",
        en: "The district hospital (Alibag) has a mental health OPD.",
        hi: "जिला अस्पताल (अलीबाग) में मानसिक स्वास्थ्य OPD होती है।",
      },
      {
        mr: "तुम्ही जे सांगाल ते गोपनीय राहते.",
        en: "What you share stays confidential.",
        hi: "आप जो बताएंगी वह गोपनीय रहेगा।",
      },
    ],
    next: {
      mr: "आत्ता 14416 ला फोन लावूया का?",
      en: "Shall we call 14416 now?",
      hi: "क्या अभी 14416 पर कॉल करें?",
    },
    actions: [
      { label: { mr: "14416 मनाशी बोला", en: "Call Tele-MANAS 14416", hi: "14416 Tele-MANAS" }, href: "tel:14416" },
      { label: { mr: "181 महिला मदत", en: "Call 181", hi: "181 पर कॉल करें" }, href: "tel:181" },
    ],
    girlNote: {
      mr: "तू 14416 किंवा 1098 ला फोन करू शकतेस, किंवा शाळेतल्या विश्वासू शिक्षिकेशी बोल.",
      en: "You can call 14416 or 1098, or talk to a trusted teacher at school.",
      hi: "तुम 14416 या 1098 पर कॉल कर सकती हो, या स्कूल की भरोसेमंद टीचर से बात करो।",
    },
  },
  {
    id: "self_harm",
    intent: "act",
    title: { mr: "जगावंसं वाटत नाही", en: "I don't want to live", hi: "जीने का मन नहीं" },
    keywords: [
      "जगायचं नाही",
      "मरायचं आहे",
      "jeena nahi",
      "suicide",
      "khud ko khatam",
      "kill myself",
      "end my life",
      "self harm",
      "want to die",
      "जीना नहीं है",
      "मरना चाहती हूं",
      "खुद को खत्म",
      "आत्महत्या",
      "jagaycha nahi",
      "marayacha aahe",
      "marna hai",
      "cutting myself",
      "जीव द्यावासा वाटतो",
    ],
    understand: {
      mr: "तुम्ही हे सांगितलंत याचा मला आनंद आहे. तुम्ही खूप वेदनेत आहात, आणि तुम्ही महत्त्वाच्या आहात. तुम्ही एकट्या नाही.",
      en: "I'm really glad you told me. You are in a lot of pain, and you matter. You are not alone.",
      hi: "मुझे खुशी है कि आपने मुझे बताया। आप बहुत दर्द में हैं, और आप मायने रखती हैं। आप अकेली नहीं हैं।",
    },
    answer: [
      {
        mr: "आत्ताच Tele-MANAS 14416 ला फोन करा — मोफत, 24 तास, कोणीतरी ऐकायला आहे.",
        en: "Call Tele-MANAS 14416 now — free, 24x7, someone is there to listen.",
        hi: "अभी Tele-MANAS 14416 पर कॉल करें — मुफ्त, 24x7, कोई सुनने के लिए है।",
      },
      {
        mr: "स्वतःला इजा होण्याचा धोका आत्ता असेल तर 112 ला फोन करा.",
        en: "If you might hurt yourself right now, call 112.",
        hi: "अगर अभी खुद को नुकसान पहुंचने का खतरा है, तो 112 पर कॉल करें।",
      },
      {
        mr: "एकटं राहू नका — घरातल्या किंवा शेजारच्या कोणाला तरी जवळ बोलवा.",
        en: "Don't stay alone — call someone from home or next door to be with you.",
        hi: "अकेली न रहें — घर या पड़ोस से किसी को अपने पास बुलाएं।",
      },
      {
        mr: "औषधं, धारदार वस्तू किंवा हानिकारक गोष्टी स्वतःपासून दूर ठेवा.",
        en: "Keep medicines, sharp objects or anything harmful away from you.",
        hi: "दवाइयां, धारदार चीज़ें या नुकसानदेह चीज़ें खुद से दूर रखें।",
      },
      {
        mr: "ही भावना कायम राहत नाही. मदत घेतल्याने खरंच बरं वाटू शकतं.",
        en: "This feeling does not last forever. With help, things really can get better.",
        hi: "यह भावना हमेशा नहीं रहती। मदद से सच में बेहतर हो सकता है।",
      },
    ],
    next: {
      mr: "आत्ता तुमच्यासोबत कोणी आहे का? कृपया आत्ताच 14416 ला फोन करा — मी इथेच आहे.",
      en: "Is anyone with you right now? Please call 14416 now — I'm right here.",
      hi: "क्या अभी आपके साथ कोई है? कृपया अभी 14416 पर कॉल करें — मैं यहीं हूं।",
    },
    actions: [
      { label: { mr: "14416 ला आत्ता कॉल करा", en: "Call 14416 now", hi: "अभी 14416 पर कॉल करें" }, href: "tel:14416" },
      { label: { mr: "112 आपत्कालीन", en: "Call 112", hi: "112 आपातकाल" }, href: "tel:112" },
    ],
    sensitive: "crisis",
    emergency: true,
    girlNote: {
      mr: "तू खूप महत्त्वाची आहेस. आत्ताच विश्वासू मोठ्या व्यक्तीला सांग किंवा 1098 / 14416 ला फोन कर.",
      en: "You matter so much. Tell a trusted adult right now, or call 1098 or 14416.",
      hi: "तुम बहुत मायने रखती हो। अभी किसी भरोसेमंद बड़े को बताओ, या 1098 / 14416 पर कॉल करो।",
    },
  },
];
