import type { Topic } from "./types";

// Personal safety, emergency and cyber-safety topics for AADHI TI AI.

export const safetyTopics: Topic[] = [
  // ───────────── PERSONAL SAFETY & EMERGENCY ─────────────
  {
    id: "following_me",
    intent: "act",
    emergency: true,
    sensitive: "crisis",
    title: {
      mr: "कोणीतरी माझा पाठलाग करतोय",
      en: "Someone is following me",
      hi: "कोई मेरा पीछा कर रहा है",
    },
    keywords: [
      "someone following me",
      "being followed",
      "stalker",
      "कोणीतरी माझ्या मागे येतोय",
      "पाठलाग",
      "मागे मागे येतो",
      "कोणी मागे लागलाय",
      "कोई पीछा कर रहा है",
      "पीछा कर रहा",
      "koi peecha kar raha",
      "koi piche aa raha",
      "koni maage yetoy",
      "pathlag",
      "follow karto",
      "follow kar raha hai",
      "डर लग रहा है",
    ],
    understand: {
      mr: "कोणी तुमच्या मागे येत असेल तर भीती वाटणं साहजिक आहे. तुमची भावना बरोबर आहे — आधी सुरक्षित होऊया.",
      en: "It is natural to feel frightened if someone is following you. Trust your instincts. Let's get you safe first.",
      hi: "कोई पीछा कर रहा हो तो डर लगना स्वाभाविक है। आपकी भावना सही है — पहले सुरक्षित होते हैं।",
    },
    answer: [
      {
        mr: "धोका वाटत असेल तर आत्ताच 112 ला फोन करा. तुमचं ठिकाण सांगा.",
        en: "If you feel in danger, call 112 right now and tell them where you are.",
        hi: "खतरा लगे तो अभी 112 पर कॉल करें और अपनी जगह बताएँ।",
      },
      {
        mr: "गर्दीच्या, उजेडाच्या ठिकाणी जा — दुकान, मेडिकल, ST स्टँड, मंदिर.",
        en: "Move to a crowded, well-lit place — a shop, chemist, ST stand or temple.",
        hi: "भीड़ वाली, रोशनी वाली जगह जाएँ — दुकान, मेडिकल, बस स्टैंड या मंदिर।",
      },
      {
        mr: "घरी सरळ जाऊ नका; आधी ओळखीच्या व्यक्तीला फोन करून सोबत बोलवा.",
        en: "Don't lead them to your home; call someone you know and ask them to come to you.",
        hi: "सीधे घर न जाएँ; किसी जानकार को फोन करके अपने पास बुलाएँ।",
      },
      {
        mr: "फोनवर बोलत असल्याचं दाखवा — 'Fake call' वापरून तिथून निघा.",
        en: "Act like you are on a call — use a fake call to give yourself a reason to leave.",
        hi: "फोन पर बात करने का दिखावा करें — फेक कॉल से वहाँ से निकलें।",
      },
      {
        mr: "जमल्यास त्याचं वर्णन, गाडी नंबर लक्षात ठेवा. हे पोलिसांना उपयोगी पडतं.",
        en: "If safe, note his appearance or vehicle number. This helps the police.",
        hi: "सुरक्षित हो तो उसका हुलिया या गाड़ी नंबर याद रखें। पुलिस के काम आएगा।",
      },
    ],
    next: {
      mr: "तुम्ही आत्ता सुरक्षित ठिकाणी आहात का? नसाल तर लगेच 112 दाबा.",
      en: "Are you somewhere safe right now? If not, press 112 immediately.",
      hi: "क्या आप अभी सुरक्षित जगह पर हैं? नहीं तो तुरंत 112 दबाएँ।",
    },
    actions: [
      { label: { mr: "112 ला फोन करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
      { label: { mr: "Fake call लावा", en: "Start a fake call", hi: "फेक कॉल शुरू करें" }, href: "/call?mode=fake" },
      { label: { mr: "AI सुरक्षा कॉल", en: "AI safety call", hi: "AI सुरक्षा कॉल" }, href: "/call" },
    ],
    girlNote: {
      mr: "शाळेच्या वाटेवर असं होत असेल तर घरच्यांना किंवा शिक्षकांना नक्की सांगा. 1098 वर फोन करू शकता.",
      en: "If this happens on your way to school, tell a parent or teacher. You can also call 1098.",
      hi: "स्कूल के रास्ते में ऐसा हो तो माता-पिता या टीचर को ज़रूर बताएँ। 1098 पर कॉल कर सकती हो।",
    },
  },
  {
    id: "immediate_danger",
    intent: "act",
    emergency: true,
    sensitive: "crisis",
    title: {
      mr: "मी आत्ता धोक्यात आहे",
      en: "I am in immediate danger",
      hi: "मैं अभी खतरे में हूँ",
    },
    keywords: [
      "danger",
      "help me",
      "emergency",
      "save me",
      "मदत करा",
      "धोका आहे",
      "मला वाचवा",
      "मी धोक्यात आहे",
      "बचाओ",
      "मदद करो",
      "मैं खतरे में हूँ",
      "bachao",
      "madat kara",
      "mala vachva",
      "khatra hai",
      "sos",
      "attack",
      "मारहाण होतेय",
    ],
    understand: {
      mr: "तुम्ही धोक्यात असाल तर तुमची सुरक्षितता सगळ्यात महत्त्वाची आहे. मी तुमच्यासोबत आहे.",
      en: "If you are in danger, your safety comes first. You are not alone.",
      hi: "अगर आप खतरे में हैं तो आपकी सुरक्षा सबसे ज़रूरी है। आप अकेली नहीं हैं।",
    },
    answer: [
      {
        mr: "आत्ताच 112 ला फोन करा. बोलता येत नसेल तरी फोन चालू ठेवा.",
        en: "Call 112 now. Even if you can't speak, keep the line open.",
        hi: "अभी 112 पर कॉल करें। बोल न पाएँ तो भी लाइन चालू रखें।",
      },
      {
        mr: "Android वर power बटण 5 वेळा दाबल्यास SOS जातो (फोनमध्ये सेटिंग असल्यास).",
        en: "On many phones, pressing the power button 5 times sends an SOS, if it's set up.",
        hi: "कई फोन में पावर बटन 5 बार दबाने से SOS जाता है, अगर सेट हो।",
      },
      {
        mr: "जमल्यास बाहेर पडा, दार बंद करा, किंवा लोकांजवळ जा. मोठ्याने ओरडा.",
        en: "If you can, get out, lock a door between you, or go near people. Shout loudly.",
        hi: "हो सके तो बाहर निकलें, दरवाज़ा बंद करें या लोगों के पास जाएँ। ज़ोर से चिल्लाएँ।",
      },
      {
        mr: "ओळखीच्या एका व्यक्तीला तुमचं location पाठवा.",
        en: "Send your live location to one person you trust.",
        hi: "किसी भरोसेमंद व्यक्ति को अपनी लाइव लोकेशन भेजें।",
      },
      {
        mr: "जखम असेल तर 108 ला ॲम्ब्युलन्ससाठी फोन करा.",
        en: "If you are hurt, call 108 for an ambulance.",
        hi: "चोट लगी हो तो एम्बुलेंस के लिए 108 पर कॉल करें।",
      },
    ],
    next: {
      mr: "आधी 112 दाबा. नंतर मला सांगा — तुम्ही आत्ता कुठे आहात?",
      en: "Press 112 first. Then tell me — where are you right now?",
      hi: "पहले 112 दबाएँ। फिर बताइए — आप अभी कहाँ हैं?",
    },
    actions: [
      { label: { mr: "112 ला फोन करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
      { label: { mr: "महिला हेल्पलाइन 1091", en: "Women's Helpline 1091", hi: "महिला हेल्पलाइन 1091" }, href: "tel:1091" },
      { label: { mr: "108 ॲम्ब्युलन्स", en: "Ambulance 108", hi: "एम्बुलेंस 108" }, href: "tel:108" },
    ],
    girlNote: {
      mr: "तू 18 पेक्षा लहान असशील तर 1098 वरही फोन करू शकतेस. जवळच्या मोठ्या व्यक्तीला सांग.",
      en: "If you are under 18, you can also call 1098. Tell a trusted adult nearby.",
      hi: "अगर तुम 18 से कम हो तो 1098 पर भी कॉल कर सकती हो। पास के किसी बड़े को बताओ।",
    },
  },
  {
    id: "unsafe_travel",
    intent: "check",
    title: {
      mr: "एकटीने प्रवास करताना भीती",
      en: "Unsafe travelling alone",
      hi: "अकेले सफ़र में डर",
    },
    keywords: [
      "travelling alone",
      "alone at night",
      "unsafe travel",
      "late night travel",
      "रात्री एकटी",
      "एकटी प्रवास",
      "रात्री घरी जायचंय",
      "भीती वाटते",
      "रात को अकेले",
      "अकेले सफ़र",
      "raat ko akele",
      "ratri ekti",
      "ekti jaychay",
      "late ho gaya",
      "unsafe feel",
      "sunsaan rasta",
    ],
    understand: {
      mr: "एकटीने किंवा रात्री प्रवास करताना अस्वस्थ वाटणं अगदी साहजिक आहे. थोडी तयारी खूप मदत करते.",
      en: "Feeling uneasy while travelling alone or at night is very normal. A little planning helps a lot.",
      hi: "अकेले या रात में सफ़र करते हुए बेचैनी होना स्वाभाविक है। थोड़ी तैयारी बहुत मदद करती है।",
    },
    answer: [
      {
        mr: "आत्ताच धोका वाटत असेल तर 112 ला फोन करा.",
        en: "If you feel in danger right now, call 112.",
        hi: "अभी खतरा लगे तो 112 पर कॉल करें।",
      },
      {
        mr: "निघण्याआधी घरच्यांना मार्ग आणि पोहोचण्याची वेळ सांगा; live location share करा.",
        en: "Before leaving, tell family your route and arrival time; share live location.",
        hi: "निकलने से पहले घरवालों को रास्ता और पहुँचने का समय बताएँ; लाइव लोकेशन शेयर करें।",
      },
      {
        mr: "उजेडाचा, गर्दीचा रस्ता निवडा — शॉर्टकट टाळा.",
        en: "Choose lit, busy roads — avoid shortcuts through empty areas.",
        hi: "रोशनी और भीड़ वाला रास्ता चुनें — सुनसान शॉर्टकट से बचें।",
      },
      {
        mr: "फोन चार्ज ठेवा आणि एक नंबर speed dial वर ठेवा.",
        en: "Keep your phone charged and one trusted number on speed dial.",
        hi: "फोन चार्ज रखें और एक भरोसेमंद नंबर स्पीड डायल पर रखें।",
      },
      {
        mr: "अस्वस्थ वाटलं तर 'Fake call' वापरा किंवा AI सुरक्षा कॉल सुरू ठेवा.",
        en: "If you feel uneasy, use a fake call or keep an AI safety call running.",
        hi: "बेचैनी हो तो फेक कॉल करें या AI सुरक्षा कॉल चालू रखें।",
      },
    ],
    next: {
      mr: "तुम्ही आत्ता प्रवासात आहात का, की पुढच्या प्रवासाची तयारी करताय?",
      en: "Are you travelling right now, or planning ahead for a trip?",
      hi: "क्या आप अभी सफ़र में हैं, या आगे की तैयारी कर रही हैं?",
    },
    actions: [
      { label: { mr: "AI सुरक्षा कॉल", en: "AI safety call", hi: "AI सुरक्षा कॉल" }, href: "/call" },
      { label: { mr: "Fake call लावा", en: "Start a fake call", hi: "फेक कॉल शुरू करें" }, href: "/call?mode=fake" },
      { label: { mr: "112 ला फोन करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
    ],
    girlNote: {
      mr: "क्लास किंवा शाळेतून उशिरा येणार असशील तर घरच्यांना आधी सांग आणि मैत्रिणींसोबत ये.",
      en: "If you'll be late from class or school, tell your family first and travel with friends.",
      hi: "क्लास या स्कूल से देर हो तो घरवालों को पहले बताओ और सहेलियों के साथ आओ।",
    },
  },
  {
    id: "night_carry",
    intent: "learn",
    title: {
      mr: "रात्री प्रवासात काय ठेवावं",
      en: "What to carry at night",
      hi: "रात के सफ़र में क्या रखें",
    },
    keywords: [
      "what to carry",
      "night travel bag",
      "safety kit",
      "pepper spray",
      "torch",
      "power bank",
      "रात्री काय ठेवू",
      "बॅगेत काय ठेवावं",
      "सोबत काय न्यावं",
      "रात को क्या रखें",
      "बैग में क्या रखें",
      "kya saath rakhe",
      "kay sobat thevu",
      "safety saman",
    ],
    understand: {
      mr: "रात्री प्रवासासाठी काही साध्या वस्तू सोबत असल्या तर आत्मविश्वास वाढतो.",
      en: "Carrying a few simple things at night can make you feel more prepared and confident.",
      hi: "रात के सफ़र में कुछ आसान चीज़ें साथ हों तो आत्मविश्वास बढ़ता है।",
    },
    answer: [
      {
        mr: "पूर्ण चार्ज फोन आणि छोटा power bank.",
        en: "A fully charged phone and a small power bank.",
        hi: "पूरा चार्ज फोन और एक छोटा पावर बैंक।",
      },
      {
        mr: "थोडे सुट्टे पैसे आणि घरचे 2 नंबर कागदावर लिहून — फोन बंद पडला तर.",
        en: "Some cash and two family numbers written on paper, in case your phone dies.",
        hi: "कुछ नकद पैसे और घर के 2 नंबर कागज़ पर लिखे हुए — फोन बंद हो जाए तो।",
      },
      {
        mr: "छोटी torch, शिट्टी, आणि कायदेशीर असलेला pepper spray.",
        en: "A small torch, a whistle, and a legal pepper spray if you're comfortable with it.",
        hi: "छोटी टॉर्च, सीटी, और अगर सहज हों तो पेपर स्प्रे।",
      },
      {
        mr: "ओळखपत्र आणि गरज असल्यास औषधं.",
        en: "An ID card and any medicines you need.",
        hi: "पहचान पत्र और ज़रूरी दवाइयाँ।",
      },
      {
        mr: "फोनमध्ये 112 आणि 1091 save करा; SOS सेटिंग चालू करा.",
        en: "Save 112 and 1091 in your phone and turn on the SOS setting.",
        hi: "फोन में 112 और 1091 सेव करें और SOS सेटिंग चालू करें।",
      },
    ],
    next: {
      mr: "तुम्हाला एक सोपी आपत्कालीन सुरक्षा योजना बनवायला मदत करू का?",
      en: "Would you like help making a simple emergency safety plan too?",
      hi: "क्या आप एक आसान इमरजेंसी सेफ़्टी प्लान भी बनाना चाहेंगी?",
    },
    actions: [
      { label: { mr: "AI सुरक्षा कॉल", en: "AI safety call", hi: "AI सुरक्षा कॉल" }, href: "/call" },
    ],
  },
  {
    id: "public_harassment",
    intent: "act",
    sensitive: "legal",
    title: {
      mr: "बाहेर छेडछाड होतेय",
      en: "Harassed in public",
      hi: "सार्वजनिक जगह पर छेड़छाड़",
    },
    keywords: [
      "eve teasing",
      "harassment in bus",
      "unwanted touching",
      "groping",
      "catcalling",
      "छेडछाड",
      "बसमध्ये हात लावला",
      "st मध्ये धक्का देतो",
      "बाजारात त्रास देतो",
      "शिट्ट्या मारतो",
      "छेड़छाड़",
      "बस में गलत तरीके से छुआ",
      "ched chad",
      "chhedkhani",
      "bus mein chhua",
      "tras deto",
      "comment karto",
      "गलत नज़र से देखता है",
    ],
    understand: {
      mr: "न विचारता हात लावणं, शेरेबाजी करणं ही छेडछाड आहे — यात तुमची काहीही चूक नाही.",
      en: "Unwanted touching, comments or gestures are harassment. It is never your fault.",
      hi: "बिना मर्ज़ी छूना, कमेंट या इशारे करना छेड़छाड़ है। इसमें आपकी कोई गलती नहीं।",
    },
    answer: [
      {
        mr: "धोका वाटत असेल तर लगेच 112 ला फोन करा.",
        en: "If you feel unsafe, call 112 right away.",
        hi: "असुरक्षित लगे तो तुरंत 112 पर कॉल करें।",
      },
      {
        mr: "मोठ्याने आणि ठामपणे बोला: 'हात लावू नका!' — आजूबाजूचे लोक लक्ष देतात.",
        en: "Speak loudly and firmly: 'Don't touch me!' — it draws attention from others.",
        hi: "ज़ोर से और साफ़ बोलें: 'हाथ मत लगाओ!' — आसपास के लोग ध्यान देते हैं।",
      },
      {
        mr: "बसमध्ये कंडक्टर किंवा ड्रायव्हरला सांगा; महिलांच्या सीटजवळ जा.",
        en: "In a bus, tell the conductor or driver and move near other women.",
        hi: "बस में कंडक्टर या ड्राइवर को बताएँ और महिलाओं के पास जाएँ।",
      },
      {
        mr: "जमल्यास वेळ, ठिकाण, बस नंबर लक्षात ठेवा. सुरक्षित असल्यास फोटो घ्या.",
        en: "If safe, note the time, place and bus number, or take a photo.",
        hi: "सुरक्षित हो तो समय, जगह, बस नंबर याद रखें या फोटो लें।",
      },
      {
        mr: "छेडछाड हा BNS कायद्याखाली गुन्हा आहे. 1091 किंवा पोलिसांकडे तक्रार करता येते.",
        en: "Sexual harassment is a crime under the BNS. You can complain via 1091 or the police.",
        hi: "यौन उत्पीड़न BNS के तहत अपराध है। 1091 या पुलिस से शिकायत कर सकती हैं।",
      },
    ],
    next: {
      mr: "हे आत्ता घडतंय का, की आधी घडलं आणि तक्रार करायची आहे?",
      en: "Is this happening right now, or did it happen earlier and you want to report it?",
      hi: "क्या यह अभी हो रहा है, या पहले हुआ और आप शिकायत करना चाहती हैं?",
    },
    actions: [
      { label: { mr: "112 ला फोन करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
      { label: { mr: "महिला हेल्पलाइन 1091", en: "Women's Helpline 1091", hi: "महिला हेल्पलाइन 1091" }, href: "tel:1091" },
    ],
    girlNote: {
      mr: "असं झालं तर आई-बाबांना किंवा शिक्षकांना सांग. तू 1098 वरही फोन करू शकतेस.",
      en: "If this happens, tell a parent or teacher. You can also call 1098.",
      hi: "ऐसा हो तो माता-पिता या टीचर को बताओ। तुम 1098 पर भी कॉल कर सकती हो।",
    },
  },
  {
    id: "safety_plan",
    intent: "learn",
    title: {
      mr: "आपत्कालीन सुरक्षा योजना",
      en: "Make a safety plan",
      hi: "इमरजेंसी सेफ़्टी प्लान",
    },
    keywords: [
      "safety plan",
      "emergency plan",
      "be prepared",
      "सुरक्षा योजना",
      "आधीच तयारी",
      "संकटात काय करायचं",
      "सेफ़्टी प्लान",
      "इमरजेंसी में क्या करें",
      "safety plan kasa banvaycha",
      "emergency mein kya kare",
      "tayari",
      "code word",
    ],
    understand: {
      mr: "आधी ठरवलेली योजना असेल तर संकटात पटकन निर्णय घेता येतो.",
      en: "A plan made in calm times helps you act quickly if something goes wrong.",
      hi: "शांत समय में बना प्लान मुश्किल वक्त में जल्दी कदम उठाने में मदद करता है।",
    },
    answer: [
      {
        mr: "2–3 विश्वासाच्या व्यक्ती ठरवा आणि त्यांच्यासोबत एक 'code word' ठरवा.",
        en: "Pick 2–3 trusted people and agree on a code word that means 'I need help'.",
        hi: "2–3 भरोसेमंद लोग चुनें और 'मदद चाहिए' के लिए एक कोड वर्ड तय करें।",
      },
      {
        mr: "जवळची सुरक्षित ठिकाणं ओळखा — पोलीस चौकी, दवाखाना, शेजारी.",
        en: "Know nearby safe places — police chowki, hospital, a trusted neighbour.",
        hi: "पास की सुरक्षित जगहें जानें — पुलिस चौकी, अस्पताल, भरोसेमंद पड़ोसी।",
      },
      {
        mr: "आधार, पैसे, औषधं, चार्जर एका छोट्या बॅगेत तयार ठेवा.",
        en: "Keep ID, some cash, medicines and a charger ready in a small bag.",
        hi: "आधार, कुछ पैसे, दवाइयाँ और चार्जर एक छोटे बैग में तैयार रखें।",
      },
      {
        mr: "112, 1091, 181 हे नंबर फोनमध्ये आणि कागदावर लिहून ठेवा.",
        en: "Save 112, 1091 and 181 in your phone and on paper.",
        hi: "112, 1091 और 181 फोन में और कागज़ पर लिखकर रखें।",
      },
      {
        mr: "फोनमध्ये SOS आणि live location sharing चालू करून ठेवा.",
        en: "Turn on SOS and live location sharing on your phone in advance.",
        hi: "फोन में SOS और लाइव लोकेशन शेयरिंग पहले से चालू रखें।",
      },
    ],
    next: {
      mr: "तुमच्या योजनेत कोणत्या 2 व्यक्ती असतील, हे आत्ताच ठरवूया का?",
      en: "Shall we decide right now which two people will be in your plan?",
      hi: "क्या अभी तय करें कि आपके प्लान में कौन से दो लोग होंगे?",
    },
    actions: [
      { label: { mr: "महिला हेल्पलाइन 181", en: "Women helpline 181", hi: "महिला हेल्पलाइन 181" }, href: "tel:181" },
      { label: { mr: "AI सुरक्षा कॉल", en: "AI safety call", hi: "AI सुरक्षा कॉल" }, href: "/call" },
    ],
    girlNote: {
      mr: "तुझ्या योजनेत एक शिक्षक किंवा घरचा मोठा माणूस नक्की ठेव. 1098 लक्षात ठेव.",
      en: "Include a teacher or an adult at home in your plan. Remember 1098.",
      hi: "अपने प्लान में एक टीचर या घर का कोई बड़ा ज़रूर रखो। 1098 याद रखो।",
    },
  },
  {
    id: "help_info_ready",
    intent: "find",
    title: {
      mr: "मदत मागताना काय सांगावं",
      en: "Info to keep ready for help",
      hi: "मदद माँगते समय क्या बताएँ",
    },
    keywords: [
      "how to call police",
      "police number",
      "what to tell police",
      "police la kasa call karaycha",
      "पोलिसांना फोन",
      "पोलिसांना काय सांगू",
      "पोलीस नंबर",
      "पुलिस को कैसे बुलाएँ",
      "पुलिस को क्या बताएँ",
      "police ko kaise bulaye",
      "police number kya hai",
      "complaint kashi karaychi",
      "helpline number",
      "112 kya hai",
    ],
    understand: {
      mr: "मदत मागताना नेमकी माहिती दिली तर मदत लवकर पोहोचते. पोलिसांपर्यंत पोहोचण्याचे सोपे मार्ग आहेत.",
      en: "Clear information helps help reach you faster. There are simple ways to reach the police.",
      hi: "साफ़ जानकारी देने से मदद जल्दी पहुँचती है। पुलिस तक पहुँचने के आसान तरीके हैं।",
    },
    answer: [
      {
        mr: "आपत्कालीन स्थितीत 112 — पोलीस, ॲम्ब्युलन्स, अग्निशमन सगळ्यांसाठी एकच नंबर.",
        en: "In an emergency, dial 112 — one number for police, ambulance and fire.",
        hi: "इमरजेंसी में 112 डायल करें — पुलिस, एम्बुलेंस, फायर सबके लिए एक नंबर।",
      },
      {
        mr: "सांगा: तुमचं नाव, नेमकं ठिकाण (जवळची खूण), काय घडतंय, कोणी जखमी आहे का.",
        en: "Say: your name, exact place (a nearby landmark), what is happening, if anyone is hurt.",
        hi: "बताएँ: आपका नाम, सही जगह (पास का निशान), क्या हो रहा है, कोई घायल है क्या।",
      },
      {
        mr: "त्रास देणाऱ्याचं वर्णन, गाडी नंबर, दिशा — जे माहिती असेल ते सांगा.",
        en: "Share what you know of the person — description, vehicle number, which way they went.",
        hi: "जो पता हो बताएँ — व्यक्ति का हुलिया, गाड़ी नंबर, किस तरफ़ गया।",
      },
      {
        mr: "महिलांसाठी 1091 आणि 181 (One Stop Centre) हेही आहेत. ऑनलाइन फसवणुकीसाठी 1930.",
        en: "For women: 1091 and 181 (One Stop Centre). For online fraud: 1930.",
        hi: "महिलाओं के लिए 1091 और 181 (वन स्टॉप सेंटर)। ऑनलाइन धोखाधड़ी के लिए 1930।",
      },
      {
        mr: "तक्रार नोंदवल्यावर FIR/तक्रार नंबर मागून घ्या.",
        en: "After reporting, ask for the FIR or complaint number.",
        hi: "शिकायत के बाद FIR या शिकायत नंबर ज़रूर माँगें।",
      },
    ],
    next: {
      mr: "तुम्हाला आत्ता मदत हवी आहे, की फक्त माहिती ठेवायची आहे?",
      en: "Do you need help right now, or are you keeping this information ready?",
      hi: "क्या आपको अभी मदद चाहिए, या आप जानकारी तैयार रख रही हैं?",
    },
    actions: [
      { label: { mr: "112 ला फोन करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
      { label: { mr: "महिला हेल्पलाइन 1091", en: "Women's Helpline 1091", hi: "महिला हेल्पलाइन 1091" }, href: "tel:1091" },
      { label: { mr: "One Stop Centre 181", en: "One Stop Centre 181", hi: "वन स्टॉप सेंटर 181" }, href: "tel:181" },
    ],
    girlNote: {
      mr: "18 वर्षांखालील मुलींसाठी 1098 हा खास नंबर आहे.",
      en: "For anyone under 18, 1098 is a special helpline.",
      hi: "18 साल से कम उम्र वालों के लिए 1098 खास हेल्पलाइन है।",
    },
  },
  {
    id: "unsafe_transport",
    intent: "act",
    emergency: true,
    title: {
      mr: "रिक्षा, कॅब किंवा बसमध्ये असुरक्षित वाटत आहे.",
      en: "Feeling unsafe in an auto, cab or bus",
      hi: "ऑटो/कैब/बस में असुरक्षित",
    },
    keywords: [
      "auto driver",
      "cab unsafe",
      "wrong route",
      "driver misbehaving",
      "st bus",
      "रिक्षावाला",
      "रिक्षा दुसऱ्या रस्त्याने",
      "ड्रायव्हर विचित्र वागतोय",
      "ऑटो वाला गलत रास्ते",
      "ड्राइवर परेशान कर रहा",
      "rickshaw wala",
      "auto wala galat raste",
      "driver ghurta hai",
      "gadi thambvat nahi",
      "cab unsafe hai",
      "बस में डर",
    ],
    understand: {
      mr: "वाहन चुकीच्या मार्गाने जात असेल किंवा एखादी व्यक्ती विचित्र वागत असेल, तर तुम्हाला अस्वस्थ वाटणे स्वाभाविक आहे.",
      en: "If a vehicle takes the wrong route or someone behaves strangely, your concern is valid.",
      hi: "अगर गाड़ी गलत रास्ते जाए या कोई अजीब बर्ताव करे, तो आपकी चिंता सही है।",
    },
    answer: [
      {
        mr: "धोका वाटत असेल तर लगेच 112 ला फोन करा आणि गाडी नंबर सांगा.",
        en: "If you feel in danger, call 112 now and give the vehicle number.",
        hi: "खतरा लगे तो तुरंत 112 पर कॉल करें और गाड़ी नंबर बताएँ।",
      },
      {
        mr: "मोठ्याने फोनवर बोला: 'मी गाडी नंबर पाठवलाय, 5 मिनिटांत पोहोचते.'",
        en: "Speak loudly on the phone: 'I've sent the vehicle number, reaching in 5 minutes.'",
        hi: "फोन पर ज़ोर से बोलें: 'गाड़ी नंबर भेज दिया है, 5 मिनट में पहुँच रही हूँ।'",
      },
      {
        mr: "गर्दीच्या ठिकाणी गाडी थांबवायला सांगा आणि उतरा.",
        en: "Ask to stop at a busy spot and get out.",
        hi: "भीड़ वाली जगह पर गाड़ी रुकवाएँ और उतर जाएँ।",
      },
      {
        mr: "App cab मध्ये SOS बटण आणि 'trip share' वापरा.",
        en: "In app cabs, use the in-app SOS button and 'share trip'.",
        hi: "ऐप कैब में SOS बटन और 'ट्रिप शेयर' इस्तेमाल करें।",
      },
      {
        mr: "ST मध्ये कंडक्टरला सांगा; पुढच्या स्टँडवर पोलिसांना कळवता येतं.",
        en: "In an ST bus, tell the conductor; police can be alerted at the next stand.",
        hi: "ST बस में कंडक्टर को बताएँ; अगले स्टैंड पर पुलिस को खबर दी जा सकती है।",
      },
    ],
    next: {
      mr: "तुम्ही आत्ता गाडीत आहात का? असाल तर 112 दाबा किंवा Fake call लावा.",
      en: "Are you in the vehicle now? If yes, press 112 or start a fake call.",
      hi: "क्या आप अभी गाड़ी में हैं? हाँ तो 112 दबाएँ या फेक कॉल शुरू करें।",
    },
    actions: [
      { label: { mr: "112 ला फोन करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
      { label: { mr: "Fake call लावा", en: "Start a fake call", hi: "फेक कॉल शुरू करें" }, href: "/call?mode=fake" },
      { label: { mr: "AI सुरक्षा कॉल", en: "AI safety call", hi: "AI सुरक्षा कॉल" }, href: "/call" },
    ],
  },
  {
    id: "solo_travel",
    intent: "learn",
    ages: ["18", "30", "40", "50"],
    title: {
      mr: "एकटीने फिरताना काळजी",
      en: "Solo travel precautions",
      hi: "अकेले घूमने की सावधानियाँ",
    },
    keywords: [
      "solo travel",
      "solo trip",
      "beach safety",
      "konkan trip",
      "shrivardhan beach",
      "harihareshwar",
      "एकटी फिरायला",
      "होमस्टे सुरक्षित आहे का",
      "समुद्रकिनारी एकटी",
      "अकेले घूमना",
      "अकेले ट्रिप",
      "akele ghumne jana",
      "ekti trip",
      "homestay safe hai kya",
    ],
    understand: {
      mr: "एकटीने कोकण फिरणं छान अनुभव असू शकतो. थोडी काळजी घेतली तर प्रवास सुरक्षित राहतो.",
      en: "Travelling solo in the Konkan can be wonderful. A few precautions keep it safe.",
      hi: "कोंकण में अकेले घूमना अच्छा अनुभव हो सकता है। थोड़ी सावधानी से सफ़र सुरक्षित रहता है।",
    },
    answer: [
      {
        mr: "Reviews चांगले असलेला, कुटुंब चालवतं असा होमस्टे निवडा; पत्ता घरच्यांना पाठवा.",
        en: "Pick a well-reviewed, family-run homestay and send its address to family.",
        hi: "अच्छे रिव्यू वाला, परिवार का चलाया होमस्टे चुनें और पता घरवालों को भेजें।",
      },
      {
        mr: "खोलीचं दार आणि खिडकी नीट लागते का ते तपासा; रात्री दार लॉक करा.",
        en: "Check the room door and window lock properly; lock up at night.",
        hi: "कमरे का दरवाज़ा और खिड़की ठीक से बंद होती है, जाँचें; रात को लॉक करें।",
      },
      {
        mr: "अंधार पडल्यावर सुनसान किनाऱ्यावर एकटी जाऊ नका; भरती-ओहोटीची वेळ विचारा.",
        en: "Avoid empty beaches after dark, and ask locals about tide timings.",
        hi: "अँधेरे में सुनसान बीच पर अकेले न जाएँ; ज्वार-भाटे का समय पूछें।",
      },
      {
        mr: "आपण एकट्या आहोत हे अनोळखी लोकांना सांगू नका.",
        en: "Don't tell strangers that you are travelling alone.",
        hi: "अनजान लोगों को न बताएँ कि आप अकेली हैं।",
      },
      {
        mr: "रोज ठरलेल्या वेळी घरी फोन करा; ठिकाण बदललं तर कळवा.",
        en: "Check in with family at a fixed time daily and tell them if plans change.",
        hi: "रोज़ तय समय पर घर फोन करें; प्लान बदले तो बताएँ।",
      },
    ],
    next: {
      mr: "तुम्ही कुठे फिरायला जाताय? मी त्यानुसार अजून टिप्स देऊ शकते.",
      en: "Where are you planning to go? I can share more tips for that place.",
      hi: "आप कहाँ जाने वाली हैं? मैं उस हिसाब से और टिप्स दे सकती हूँ।",
    },
    actions: [
      { label: { mr: "AI सुरक्षा कॉल", en: "AI safety call", hi: "AI सुरक्षा कॉल" }, href: "/call" },
      { label: { mr: "112 ला फोन करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
    ],
  },
  {
    id: "report_unsafe_place",
    intent: "act",
    title: {
      mr: "असुरक्षित जागेची तक्रार",
      en: "Report an unsafe place",
      hi: "असुरक्षित जगह की शिकायत",
    },
    keywords: [
      "unsafe place",
      "no street light",
      "dark road",
      "isolated area",
      "report location",
      "लाईट नाही",
      "अंधार रस्ता",
      "सुनसान जागा",
      "रस्त्यावर दिवे बंद",
      "अंधेरा रास्ता",
      "सुनसान जगह",
      "street light band hai",
      "andhar ahe",
      "sunsan jagah",
      "unsafe jaga",
      "दारुडे बसतात",
    ],
    understand: {
      mr: "अंधार, बंद दिवे किंवा सुनसान जागा सगळ्यांसाठीच धोकादायक असतात. तुम्ही कळवल्याने इतर महिलांनाही मदत होते.",
      en: "Dark roads, broken lights or isolated spots put everyone at risk. Reporting them helps other women too.",
      hi: "अँधेरे रास्ते, बंद लाइटें या सुनसान जगहें सबके लिए खतरा हैं। आपकी शिकायत दूसरों की भी मदद करती है।",
    },
    answer: [
      {
        mr: "ही तातडीची परिस्थिती नाही; पण आत्ता धोका वाटत असेल तर 112 ला फोन करा.",
        en: "This is not an emergency report — but if you feel in danger now, call 112.",
        hi: "यह इमरजेंसी नहीं है — पर अभी खतरा लगे तो 112 पर कॉल करें।",
      },
      {
        mr: "'Safe Shrivardhan' मध्ये जागा, वेळ आणि काय समस्या आहे ते नोंदवा.",
        en: "On 'Safe Shrivardhan', note the place, time and the problem.",
        hi: "'Safe Shrivardhan' पर जगह, समय और समस्या दर्ज करें।",
      },
      {
        mr: "दिवे बंद असल्यास नगर परिषद किंवा ग्रामपंचायतीकडे लेखी तक्रार करा.",
        en: "For broken street lights, give a written complaint to the Nagar Parishad or Gram Panchayat.",
        hi: "बंद लाइट के लिए नगर परिषद या ग्राम पंचायत को लिखित शिकायत दें।",
      },
      {
        mr: "नेहमी त्रास होणारी जागा असेल तर जवळच्या पोलीस स्टेशनला गस्त वाढवायला सांगा.",
        en: "If harassment happens there often, ask the local police station to increase patrols.",
        hi: "वहाँ अक्सर परेशानी हो तो पास के थाने से गश्त बढ़ाने को कहें।",
      },
    ],
    next: {
      mr: "कोणत्या जागेबद्दल सांगायचं आहे? 'Safe Shrivardhan' वर नोंदवूया.",
      en: "Which place do you want to report? Let's add it on 'Safe Shrivardhan'.",
      hi: "किस जगह के बारे में बताना है? 'Safe Shrivardhan' पर दर्ज करें।",
    },
    actions: [
      {
        label: { mr: "Safe Shrivardhan वर नोंदवा", en: "Report on Safe Shrivardhan", hi: "Safe Shrivardhan पर दर्ज करें" },
        href: "/safe-shrivardhan",
      },
    ],
  },

  // ───────────── CYBER SAFETY ─────────────
  {
    id: "photo_threat",
    intent: "act",
    sensitive: "crisis",
    title: {
      mr: "खाजगी फोटोवरून धमकी",
      en: "Threats over private photos",
      hi: "प्राइवेट फोटो से धमकी",
    },
    keywords: [
      "sextortion",
      "private photos",
      "nude photos threat",
      "morphed photo",
      "blackmail",
      "फोटो viral करेन म्हणतो",
      "फोटो टाकेन म्हणतो",
      "पैसे मागतोय फोटोसाठी",
      "फोटो वायरल कर दूँगा",
      "ब्लैकमेल",
      "photo viral karega",
      "video leak kar dunga",
      "photo takto mhanto",
      "video call record kela",
      "पैसे दे नाहीतर",
      "ब्लॅकमेल",
    ],
    understand: {
      mr: "खाजगी फोटो/व्हिडिओवरून धमकी देणं हा गंभीर गुन्हा आहे. यात तुमची काहीही चूक नाही, आणि यातून मार्ग आहे.",
      en: "Threatening to share someone's private photos or videos is a serious crime. It is not your fault, and there is a way through this.",
      hi: "प्राइवेट फोटो/वीडियो से धमकाना गंभीर अपराध है। इसमें आपकी कोई गलती नहीं, और रास्ता है।",
    },
    answer: [
      {
        mr: "पैसे देऊ नका — दिल्यावर मागण्या वाढतच जातात.",
        en: "Do not pay — paying almost always leads to more demands.",
        hi: "पैसे मत दीजिए — देने पर माँगें बढ़ती ही जाती हैं।",
      },
      {
        mr: "चॅट, प्रोफाइल, नंबर, पेमेंट मागणीचे screenshots घ्या. काहीही delete करू नका.",
        en: "Screenshot chats, profile, number and payment demands. Don't delete anything.",
        hi: "चैट, प्रोफ़ाइल, नंबर और पैसे की माँग के स्क्रीनशॉट लें। कुछ डिलीट न करें।",
      },
      {
        mr: "त्याला उत्तर देऊ नका, वाद घालू नका; screenshots नंतर block करा.",
        en: "Stop replying and don't argue; block after saving evidence.",
        hi: "जवाब देना बंद करें, बहस न करें; सबूत सेव करके ब्लॉक करें।",
      },
      {
        mr: "लगेच 1930 वर फोन करा किंवा cybercrime.gov.in वर तक्रार करा.",
        en: "Call 1930 right away or report at cybercrime.gov.in.",
        hi: "तुरंत 1930 पर कॉल करें या cybercrime.gov.in पर शिकायत करें।",
      },
      {
        mr: "IT Act आणि BNS नुसार खाजगी फोटो पसरवणं/धमकी देणं गुन्हा आहे. विश्वासातल्या व्यक्तीला सांगा.",
        en: "Sharing or threatening to share intimate images is a crime under the IT Act and BNS. Tell someone you trust.",
        hi: "IT Act और BNS के तहत निजी फोटो फैलाना/धमकाना अपराध है। किसी भरोसेमंद को बताएँ।",
      },
    ],
    next: {
      mr: "तो तुम्हाला प्रत्यक्ष भेटून त्रास देऊ शकतो का? तसा धोका असेल तर लगेच 112 ला फोन करा.",
      en: "Could this person reach you physically? If you are in any physical danger, call 112 now.",
      hi: "क्या वह आपको सामने आकर नुकसान पहुँचा सकता है? कोई शारीरिक खतरा हो तो अभी 112 पर कॉल करें।",
    },
    actions: [
      { label: { mr: "सायबर हेल्पलाइन 1930", en: "Cyber helpline 1930", hi: "साइबर हेल्पलाइन 1930" }, href: "tel:1930" },
      { label: { mr: "ऑनलाइन तक्रार करा", en: "Report online", hi: "ऑनलाइन शिकायत करें" }, href: "https://cybercrime.gov.in" },
      { label: { mr: "112 ला फोन करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
    ],
    girlNote: {
      mr: "घाबरू नकोस, तुझी चूक नाही. आई-बाबा, शिक्षक किंवा 1098 वर लगेच सांग.",
      en: "Don't be scared — it's not your fault. Tell a parent, teacher, or call 1098 right away.",
      hi: "डरो मत, तुम्हारी गलती नहीं है। माता-पिता, टीचर को बताओ या तुरंत 1098 पर कॉल करो।",
    },
  },
  {
    id: "instagram_threat",
    intent: "act",
    sensitive: "crisis",
    title: {
      mr: "Instagram/WhatsApp वर धमकी",
      en: "Threats on Instagram/WhatsApp",
      hi: "Instagram/WhatsApp पर धमकी",
    },
    keywords: [
      "instagram threat",
      "whatsapp threat",
      "abusive messages",
      "online abuse",
      "cyber bullying",
      "instagram वर धमकी",
      "whatsapp वर शिव्या",
      "मेसेज करून त्रास देतो",
      "इंस्टाग्राम पर धमकी",
      "गाली वाले मैसेज",
      "insta pe dhamki",
      "whatsapp var tras",
      "gandi messages",
      "dm madhe tras",
      "dhamki de raha hai",
      "troll",
    ],
    understand: {
      mr: "मेसेजमधून धमकी देणं, शिव्या देणं किंवा सतत त्रास देणं हा ऑनलाइन छळ आहे — आणि तो गुन्हा आहे. तुमची चूक नाही.",
      en: "Threats, abuse or repeated harassing messages are online harassment — and a crime. This is not your fault.",
      hi: "धमकी, गालियाँ या बार-बार परेशान करने वाले मैसेज ऑनलाइन उत्पीड़न हैं — और अपराध हैं। आपकी गलती नहीं।",
    },
    answer: [
      {
        mr: "त्याला उत्तर देऊ नका, वाद घालू नका — तेच त्याला हवं असतं.",
        en: "Don't reply or argue — that is usually what they want.",
        hi: "जवाब न दें, बहस न करें — अक्सर वही तो वे चाहते हैं।",
      },
      {
        mr: "मेसेज, profile link, username, तारीख-वेळ यांचे screenshots घ्या.",
        en: "Screenshot the messages, profile link, username, and date and time.",
        hi: "मैसेज, प्रोफ़ाइल लिंक, यूज़रनेम और तारीख-समय के स्क्रीनशॉट लें।",
      },
      {
        mr: "मग Instagram/WhatsApp मध्ये 'Report' आणि 'Block' करा.",
        en: "Then use 'Report' and 'Block' inside Instagram or WhatsApp.",
        hi: "फिर Instagram/WhatsApp में 'Report' और 'Block' करें।",
      },
      {
        mr: "cybercrime.gov.in वर किंवा 1930 वर तक्रार करा; पोलीस स्टेशनलाही जाऊ शकता.",
        en: "Report at cybercrime.gov.in or call 1930; you can also go to the police station.",
        hi: "cybercrime.gov.in या 1930 पर शिकायत करें; थाने भी जा सकती हैं।",
      },
    ],
    next: {
      mr: "तो तुम्हाला ओळखतो किंवा घर माहीत आहे का? प्रत्यक्ष धोका वाटत असेल तर 112 ला फोन करा.",
      en: "Does this person know you or where you live? If you feel in physical danger, call 112.",
      hi: "क्या वह आपको जानता है या घर का पता है? शारीरिक खतरा लगे तो 112 पर कॉल करें।",
    },
    actions: [
      { label: { mr: "ऑनलाइन तक्रार करा", en: "Report online", hi: "ऑनलाइन शिकायत करें" }, href: "https://cybercrime.gov.in" },
      { label: { mr: "सायबर हेल्पलाइन 1930", en: "Cyber helpline 1930", hi: "साइबर हेल्पलाइन 1930" }, href: "tel:1930" },
      { label: { mr: "112 ला फोन करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
    ],
    girlNote: {
      mr: "असे मेसेज येत असतील तर घरच्यांना किंवा शिक्षकांना दाखव. 1098 वर मदत मिळेल.",
      en: "If you get messages like this, show a parent or teacher. 1098 can help.",
      hi: "ऐसे मैसेज आएँ तो माता-पिता या टीचर को दिखाओ। 1098 मदद करेगा।",
    },
  },
  {
    id: "fake_profile",
    intent: "act",
    title: {
      mr: "माझ्या नावाने खोटं अकाउंट",
      en: "Fake profile using my photos",
      hi: "मेरे नाम से फ़र्ज़ी अकाउंट",
    },
    keywords: [
      "fake profile",
      "fake account",
      "impersonation",
      "my photos used",
      "माझ्या नावाने अकाउंट",
      "माझे फोटो वापरले",
      "खोटं प्रोफाइल",
      "मेरे नाम से फेक आईडी",
      "मेरी फोटो लगाई",
      "fake id banayi",
      "maze photo vaparle",
      "duplicate account",
      "koi meri photo use kar raha",
      "फ़र्ज़ी प्रोफ़ाइल",
    ],
    understand: {
      mr: "कोणी तुमच्या नावाने किंवा फोटोने खोटं अकाउंट बनवलं असेल तर राग आणि भीती वाटणं साहजिक आहे. हे काढून टाकता येतं.",
      en: "Someone making a fake account with your name or photos is upsetting. It can be reported and removed.",
      hi: "कोई आपके नाम या फोटो से फ़र्ज़ी अकाउंट बनाए तो गुस्सा और डर स्वाभाविक है। इसे हटवाया जा सकता है।",
    },
    answer: [
      {
        mr: "खोट्या profile चा link, username आणि posts चे screenshots घ्या.",
        en: "Save the fake profile's link, username and screenshots of its posts.",
        hi: "फ़र्ज़ी प्रोफ़ाइल का लिंक, यूज़रनेम और पोस्ट के स्क्रीनशॉट सेव करें।",
      },
      {
        mr: "App मध्ये 'Report → Pretending to be me / Impersonation' निवडा.",
        en: "In the app, choose 'Report → Pretending to be me / Impersonation'.",
        hi: "ऐप में 'Report → Pretending to be me / Impersonation' चुनें।",
      },
      {
        mr: "मित्रमैत्रिणींना सांगा — त्या अकाउंटला उत्तर देऊ नका, report करा.",
        en: "Tell friends not to respond to that account and to report it too.",
        hi: "दोस्तों को बताएँ कि उस अकाउंट को जवाब न दें और रिपोर्ट करें।",
      },
      {
        mr: "पैसे मागितले किंवा फोटो चुकीचे वापरले तर cybercrime.gov.in किंवा 1930 वर तक्रार करा.",
        en: "If it asks for money or misuses photos, report at cybercrime.gov.in or 1930.",
        hi: "अगर पैसे माँगे या फोटो गलत इस्तेमाल हों, तो cybercrime.gov.in या 1930 पर शिकायत करें।",
      },
    ],
    next: {
      mr: "हे अकाउंट कोणत्या app वर आहे — Instagram, Facebook की WhatsApp?",
      en: "Which app is the fake account on — Instagram, Facebook or WhatsApp?",
      hi: "फ़र्ज़ी अकाउंट किस ऐप पर है — Instagram, Facebook या WhatsApp?",
    },
    actions: [
      { label: { mr: "ऑनलाइन तक्रार करा", en: "Report online", hi: "ऑनलाइन शिकायत करें" }, href: "https://cybercrime.gov.in" },
      { label: { mr: "सायबर हेल्पलाइन 1930", en: "Cyber helpline 1930", hi: "साइबर हेल्पलाइन 1930" }, href: "tel:1930" },
    ],
    girlNote: {
      mr: "तुझ्या फोटोचा गैरवापर झाला तर लगेच घरच्यांना किंवा शिक्षकांना सांग. 1098 मदत करेल.",
      en: "If your photos are misused, tell a parent or teacher at once. 1098 can help.",
      hi: "तुम्हारी फोटो का गलत इस्तेमाल हो तो तुरंत माता-पिता या टीचर को बताओ। 1098 मदद करेगा।",
    },
  },
  {
    id: "hacked_account",
    intent: "act",
    title: {
      mr: "माझं अकाउंट हॅक झालं",
      en: "My account was hacked",
      hi: "मेरा अकाउंट हैक हो गया",
    },
    keywords: [
      "hacked",
      "account hacked",
      "can't login",
      "password changed",
      "अकाउंट हॅक झालं",
      "लॉगिन होत नाही",
      "पासवर्ड बदलला",
      "अकाउंट हैक हो गया",
      "लॉगिन नहीं हो रहा",
      "account hack ho gaya",
      "whatsapp hack",
      "insta hack zala",
      "maza account koni dusra chalvtoy",
      "मेरे अकाउंट से मैसेज जा रहे",
    ],
    understand: {
      mr: "अकाउंट हॅक होणं कोणासोबतही होऊ शकतं. लवकर पावलं उचलली तर ते परत मिळवता येतं.",
      en: "Account hacking can happen to anyone. Acting quickly usually helps you get it back.",
      hi: "अकाउंट हैक होना किसी के साथ भी हो सकता है। जल्दी कदम उठाने से वापस मिल सकता है।",
    },
    answer: [
      {
        mr: "App मधल्या 'Forgot password' / 'Need more help' ने अकाउंट परत मिळवा.",
        en: "Use 'Forgot password' or 'Need more help' in the app to recover it.",
        hi: "ऐप में 'Forgot password' या 'Need more help' से अकाउंट वापस लें।",
      },
      {
        mr: "Email चा आणि इतर अकाउंट्सचा पासवर्डही लगेच बदला.",
        en: "Change your email password and other account passwords straight away.",
        hi: "ईमेल और दूसरे अकाउंट के पासवर्ड भी तुरंत बदलें।",
      },
      {
        mr: "Two-step verification (2FA) चालू करा. WhatsApp साठी 6 अंकी PIN ठेवा.",
        en: "Turn on two-step verification. For WhatsApp, set a 6-digit PIN.",
        hi: "टू-स्टेप वेरिफ़िकेशन चालू करें। WhatsApp के लिए 6 अंकों का PIN रखें।",
      },
      {
        mr: "मित्रांना सांगा: माझ्या अकाउंटवरून पैसे मागितले तर देऊ नका.",
        en: "Warn friends: don't send money if 'you' ask for it from that account.",
        hi: "दोस्तों को बताएँ: उस अकाउंट से पैसे माँगे जाएँ तो न दें।",
      },
      {
        mr: "परत न मिळाल्यास किंवा गैरवापर झाल्यास 1930 / cybercrime.gov.in वर तक्रार करा.",
        en: "If you can't recover it or it's misused, report to 1930 or cybercrime.gov.in.",
        hi: "वापस न मिले या गलत इस्तेमाल हो, तो 1930 या cybercrime.gov.in पर शिकायत करें।",
      },
    ],
    next: {
      mr: "कोणतं अकाउंट हॅक झालंय? मी त्या app साठी पायऱ्या सांगते.",
      en: "Which account was hacked? I'll share the steps for that app.",
      hi: "कौन सा अकाउंट हैक हुआ है? मैं उस ऐप के लिए स्टेप्स बताती हूँ।",
    },
    actions: [
      { label: { mr: "सायबर हेल्पलाइन 1930", en: "Cyber helpline 1930", hi: "साइबर हेल्पलाइन 1930" }, href: "tel:1930" },
      { label: { mr: "ऑनलाइन तक्रार करा", en: "Report online", hi: "ऑनलाइन शिकायत करें" }, href: "https://cybercrime.gov.in" },
    ],
  },
  {
    id: "otp_scam",
    intent: "check",
    title: {
      mr: "कोणी माझा OTP मागत आहे.",
      en: "Someone asking for my OTP",
      hi: "कोई OTP माँग रहा है",
    },
    keywords: [
      "otp",
      "kyc call",
      "bank call",
      "otp scam",
      "kyc update",
      "otp mangitla",
      "otp maang raha",
      "बँकेतून फोन आला",
      "otp सांगा म्हणाला",
      "kyc नाही केलं तर खाते बंद",
      "बैंक से फोन आया",
      "otp बताओ",
      "account band ho jayega",
      "lottery lagli",
      "link var click kara",
      "gas connection kyc",
    ],
    understand: {
      mr: "बँक, KYC, लॉटरी किंवा बिलांच्या नावाने OTP मागणारे कॉल फसवणुकीचे असू शकतात.",
      en: "Calls asking for your OTP in the name of your bank, KYC, a lottery or a bill are almost always scams. You were right to check.",
      hi: "बैंक, KYC, लॉटरी या बिल के नाम पर OTP माँगना ज़्यादातर धोखा होता है। आपने पूछा — बिल्कुल सही किया।",
    },
    answer: [
      {
        mr: "OTP, PIN, CVV कधीच कोणालाही सांगू नका — बँक कधीच विचारत नाही.",
        en: "Never share OTP, PIN or CVV with anyone — banks never ask for them.",
        hi: "OTP, PIN, CVV कभी किसी को न बताएँ — बैंक कभी नहीं पूछता।",
      },
      {
        mr: "फोन लगेच ठेवा. 'खातं बंद होईल' ही घाई म्हणजे फसवणुकीचं लक्षण.",
        en: "Hang up. Pressure like 'your account will be blocked' is a scam sign.",
        hi: "फोन काट दें। 'अकाउंट बंद हो जाएगा' जैसी जल्दबाज़ी धोखे का निशान है।",
      },
      {
        mr: "अनोळखी link उघडू नका आणि screen-share app (AnyDesk वगैरे) install करू नका.",
        en: "Don't open unknown links or install screen-sharing apps like AnyDesk.",
        hi: "अनजान लिंक न खोलें और AnyDesk जैसे स्क्रीन-शेयर ऐप इंस्टॉल न करें।",
      },
      {
        mr: "शंका असल्यास कार्डमागच्या नंबरवर स्वतः बँकेला फोन करा.",
        en: "If unsure, call your bank yourself on the number on your card or passbook.",
        hi: "शक हो तो कार्ड या पासबुक पर लिखे नंबर पर खुद बैंक को फोन करें।",
      },
      {
        mr: "OTP आधीच दिला असेल तर लगेच 1930 वर फोन करा आणि बँकेला कळवा.",
        en: "If you already shared the OTP, call 1930 immediately and inform your bank.",
        hi: "अगर OTP दे दिया है तो तुरंत 1930 पर कॉल करें और बैंक को बताएँ।",
      },
    ],
    next: {
      mr: "तुम्ही OTP आधीच सांगितला आहे का, की फक्त फोन आला होता?",
      en: "Have you already shared the OTP, or did you only get the call?",
      hi: "क्या आपने OTP बता दिया है, या सिर्फ़ फोन आया था?",
    },
    actions: [
      { label: { mr: "सायबर हेल्पलाइन 1930", en: "Cyber helpline 1930", hi: "साइबर हेल्पलाइन 1930" }, href: "tel:1930" },
      { label: { mr: "ऑनलाइन तक्रार करा", en: "Report online", hi: "ऑनलाइन शिकायत करें" }, href: "https://cybercrime.gov.in" },
    ],
  },
  {
    id: "money_to_scammer",
    intent: "act",
    title: {
      mr: "फसवणुकीत पैसे गेले",
      en: "I sent money to a scammer",
      hi: "धोखे में पैसे चले गए",
    },
    keywords: [
      "money lost",
      "sent money to scammer",
      "upi fraud",
      "online fraud",
      "paise gele",
      "paise chale gaye",
      "पैसे गेले",
      "फसवणूक झाली",
      "खात्यातून पैसे कापले",
      "पैसे चले गए",
      "धोखा हो गया",
      "ठगी",
      "upi scam",
      "account se paise kat gaye",
      "fraud zala",
      "galat payment",
    ],
    understand: {
      mr: "फसवणूक कोणासोबतही होऊ शकते — स्वतःला दोष देऊ नका. लगेच हालचाल केली तर पैसे अडवता येऊ शकतात.",
      en: "Fraud can happen to anyone — please don't blame yourself. Acting fast can help freeze the money.",
      hi: "धोखा किसी के साथ भी हो सकता है — खुद को दोष न दें। जल्दी कदम उठाने से पैसे रोके जा सकते हैं।",
    },
    answer: [
      {
        mr: "आत्ताच 1930 ला फोन करा — पहिल्या काही तासांत (golden hour) पैसे थांबवण्याची शक्यता जास्त असते.",
        en: "Call 1930 right now — in the first hours (the golden hour) money is most likely to be frozen.",
        hi: "अभी 1930 पर कॉल करें — पहले कुछ घंटों (गोल्डन आवर) में पैसे रुकने की संभावना सबसे ज़्यादा है।",
      },
      {
        mr: "बँकेच्या हेल्पलाइनला फोन करून कार्ड/UPI लगेच block करा.",
        en: "Call your bank's helpline and block your card or UPI immediately.",
        hi: "बैंक हेल्पलाइन पर कॉल करके कार्ड/UPI तुरंत ब्लॉक करें।",
      },
      {
        mr: "Transaction ID, UPI ID, नंबर, चॅटचे screenshots जपून ठेवा.",
        en: "Save the transaction ID, UPI ID, phone number and chat screenshots.",
        hi: "ट्रांज़ैक्शन ID, UPI ID, नंबर और चैट के स्क्रीनशॉट सँभालकर रखें।",
      },
      {
        mr: "cybercrime.gov.in वर तक्रार नोंदवा आणि acknowledgement नंबर जपा.",
        en: "File a complaint at cybercrime.gov.in and keep the acknowledgement number.",
        hi: "cybercrime.gov.in पर शिकायत करें और एक्नॉलेजमेंट नंबर रखें।",
      },
      {
        mr: "'पैसे परत मिळवून देतो' म्हणणाऱ्या दुसऱ्या फोनवरही विश्वास ठेवू नका.",
        en: "Don't trust anyone who later calls offering to 'recover' your money for a fee.",
        hi: "बाद में 'पैसे वापस दिला देंगे' कहने वाले किसी पर भरोसा न करें।",
      },
    ],
    next: {
      mr: "पैसे किती वेळापूर्वी गेले? अजून 1930 ला फोन केला नसेल तर आत्ताच करा.",
      en: "How long ago was the money sent? If you haven't called 1930 yet, do it now.",
      hi: "पैसे कितनी देर पहले गए? अभी तक 1930 पर कॉल नहीं किया तो अभी करें।",
    },
    actions: [
      { label: { mr: "आत्ताच 1930 ला फोन करा", en: "Call 1930 now", hi: "अभी 1930 पर कॉल करें" }, href: "tel:1930" },
      { label: { mr: "ऑनलाइन तक्रार करा", en: "Report online", hi: "ऑनलाइन शिकायत करें" }, href: "https://cybercrime.gov.in" },
    ],
  },
  {
    id: "online_stalking",
    intent: "act",
    sensitive: "legal",
    title: {
      mr: "कोणी ऑनलाइन पाळत ठेवतोय",
      en: "Someone stalking me online",
      hi: "कोई ऑनलाइन पीछा कर रहा है",
    },
    keywords: [
      "online stalking",
      "cyber stalking",
      "keeps messaging",
      "new accounts after block",
      "tracking me",
      "block केलं तरी मेसेज करतो",
      "सतत मेसेज करतो",
      "माझ्यावर लक्ष ठेवतो",
      "ब्लॉक करने पर भी मैसेज",
      "ऑनलाइन पीछा",
      "baar baar message karta hai",
      "navin account banvun message",
      "location kasa kalla",
      "har jagah follow karta hai",
      "मेरी हर पोस्ट देखता है",
    ],
    understand: {
      mr: "Block केल्यावरही नवीन अकाउंट्सवरून मेसेज करणं, सतत लक्ष ठेवणं हा ऑनलाइन पाठलाग आहे. BNS नुसार पाठलाग गुन्हा आहे.",
      en: "Messaging from new accounts after being blocked or constantly watching you is cyber stalking. Stalking is a crime under the BNS.",
      hi: "ब्लॉक के बाद भी नए अकाउंट से मैसेज करना या लगातार नज़र रखना साइबर स्टॉकिंग है। BNS के तहत पीछा करना अपराध है।",
    },
    answer: [
      {
        mr: "उत्तर देऊ नका. प्रत्येक मेसेज, अकाउंटचे screenshots तारखेसह जपा.",
        en: "Don't respond. Save screenshots of every message and account, with dates.",
        hi: "जवाब न दें। हर मैसेज और अकाउंट के स्क्रीनशॉट तारीख के साथ सेव करें।",
      },
      {
        mr: "Profile private करा; location, check-in, story मधलं ठिकाण बंद करा.",
        en: "Make your profile private; turn off location, check-ins and location tags.",
        hi: "प्रोफ़ाइल प्राइवेट करें; लोकेशन, चेक-इन और लोकेशन टैग बंद करें।",
      },
      {
        mr: "फोनमध्ये अनोळखी app किंवा location sharing चालू आहे का ते तपासा.",
        en: "Check your phone for unknown apps or location sharing you didn't turn on.",
        hi: "फोन में अनजान ऐप या आपकी जानकारी के बिना लोकेशन शेयरिंग तो नहीं, जाँचें।",
      },
      {
        mr: "cybercrime.gov.in वर किंवा 1930 वर तक्रार करा; महिला हेल्पलाइन 1091 मदत करेल.",
        en: "Report at cybercrime.gov.in or 1930; women helpline 1091 can also help.",
        hi: "cybercrime.gov.in या 1930 पर शिकायत करें; महिला हेल्पलाइन 1091 भी मदद करेगी।",
      },
    ],
    next: {
      mr: "तो प्रत्यक्ष तुमच्या घराजवळ किंवा कामाजवळ दिसला आहे का? असेल तर 112 ला फोन करा.",
      en: "Has this person shown up near your home or work? If so, call 112.",
      hi: "क्या वह आपके घर या काम की जगह के पास दिखा है? तो 112 पर कॉल करें।",
    },
    actions: [
      { label: { mr: "ऑनलाइन तक्रार करा", en: "Report online", hi: "ऑनलाइन शिकायत करें" }, href: "https://cybercrime.gov.in" },
      { label: { mr: "महिला हेल्पलाइन 1091", en: "Women's Helpline 1091", hi: "महिला हेल्पलाइन 1091" }, href: "tel:1091" },
      { label: { mr: "112 ला फोन करा", en: "Call 112", hi: "112 पर कॉल करें" }, href: "tel:112" },
    ],
    girlNote: {
      mr: "कोणी सतत ऑनलाइन त्रास देत असेल तर घरच्यांना किंवा शिक्षकांना सांग. 1098 वर फोन कर.",
      en: "If someone keeps bothering you online, tell a parent or teacher. Call 1098.",
      hi: "कोई लगातार ऑनलाइन परेशान करे तो माता-पिता या टीचर को बताओ। 1098 पर कॉल करो।",
    },
  },
  {
    id: "secure_whatsapp",
    intent: "learn",
    title: {
      mr: "WhatsApp/Instagram सुरक्षित करा",
      en: "Secure WhatsApp & Instagram",
      hi: "WhatsApp/Instagram सुरक्षित करें",
    },
    keywords: [
      "privacy settings",
      "secure whatsapp",
      "instagram privacy",
      "private account",
      "two step verification",
      "whatsapp सेटिंग",
      "प्रोफाइल फोटो लपवायचा",
      "अनोळखी ग्रुपमध्ये add करतात",
      "प्राइवेसी सेटिंग",
      "प्रोफाइल फोटो छुपाना",
      "dp kasa lapvaycha",
      "account private kaise kare",
      "last seen band",
      "group me add na kare",
    ],
    understand: {
      mr: "काही सोप्या settings बदलल्या तर अनोळखी लोक तुमची माहिती पाहू शकत नाहीत.",
      en: "A few simple settings keep strangers from seeing your details.",
      hi: "कुछ आसान सेटिंग्स से अनजान लोग आपकी जानकारी नहीं देख पाते।",
    },
    answer: [
      {
        mr: "WhatsApp: Settings → Privacy मध्ये Profile photo, Last seen, About 'My contacts' करा.",
        en: "WhatsApp: Settings → Privacy → set Profile photo, Last seen and About to 'My contacts'.",
        hi: "WhatsApp: Settings → Privacy में Profile photo, Last seen, About को 'My contacts' करें।",
      },
      {
        mr: "Groups → 'My contacts' करा, म्हणजे अनोळखी लोक group मध्ये add करू शकणार नाहीत.",
        en: "Set Groups to 'My contacts' so strangers can't add you to groups.",
        hi: "Groups को 'My contacts' करें ताकि अनजान लोग ग्रुप में न जोड़ें।",
      },
      {
        mr: "WhatsApp मध्ये Two-step verification PIN आणि 'Silence unknown callers' चालू करा.",
        en: "Turn on WhatsApp two-step verification PIN and 'Silence unknown callers'.",
        hi: "WhatsApp में टू-स्टेप वेरिफ़िकेशन PIN और 'Silence unknown callers' चालू करें।",
      },
      {
        mr: "Instagram: 'Private account' करा; Messages आणि Comments controls मध्ये अनोळखींना बंद करा.",
        en: "Instagram: switch to 'Private account' and limit messages and comments from strangers.",
        hi: "Instagram: 'Private account' करें और अनजानों के मैसेज व कमेंट सीमित करें।",
      },
      {
        mr: "Posts मध्ये घराचं ठिकाण, शाळा/ऑफिस, live location टाकणं टाळा.",
        en: "Avoid posting your home location, school or office, or live location.",
        hi: "पोस्ट में घर का पता, स्कूल/ऑफ़िस या लाइव लोकेशन डालने से बचें।",
      },
    ],
    next: {
      mr: "आधी कोणतं app सुरक्षित करूया — WhatsApp की Instagram?",
      en: "Which app shall we secure first — WhatsApp or Instagram?",
      hi: "पहले कौन सा ऐप सुरक्षित करें — WhatsApp या Instagram?",
    },
    actions: [
      { label: { mr: "सायबर हेल्पलाइन 1930", en: "Cyber helpline 1930", hi: "साइबर हेल्पलाइन 1930" }, href: "tel:1930" },
    ],
    girlNote: {
      mr: "अनोळखी लोकांच्या friend request स्वीकारू नकोस. काही विचित्र वाटलं तर घरच्यांना सांग.",
      en: "Don't accept requests from strangers. If something feels off, tell a trusted adult.",
      hi: "अनजान लोगों की रिक्वेस्ट मत लो। कुछ अजीब लगे तो किसी बड़े को बताओ।",
    },
  },
  {
    id: "evidence_screenshot",
    intent: "learn",
    title: {
      mr: "पुरावा कसा जपावा",
      en: "Saving evidence & screenshots",
      hi: "सबूत कैसे सँभालें",
    },
    keywords: [
      "evidence",
      "screenshot",
      "proof",
      "save chats",
      "पुरावा",
      "screenshot कसा घ्यायचा",
      "पुरावा कसा ठेवू",
      "सबूत",
      "सबूत कैसे रखें",
      "saboot kaise rakhe",
      "purava",
      "chat delete karu ka",
      "proof kay dakhvu",
      "call recording",
    ],
    understand: {
      mr: "तक्रार करताना पुरावा खूप महत्त्वाचा असतो. आत्ताच जपून ठेवलं तर नंतर मदत होते.",
      en: "Evidence makes a complaint much stronger. Saving it now helps later.",
      hi: "शिकायत में सबूत बहुत काम आता है। अभी सँभालकर रखें तो बाद में मदद मिलेगी।",
    },
    answer: [
      {
        mr: "मेसेजचे screenshots घ्या — त्यात नाव/नंबर, तारीख आणि वेळ दिसली पाहिजे.",
        en: "Screenshot messages so the name or number, date and time are visible.",
        hi: "मैसेज के स्क्रीनशॉट लें — नाम/नंबर, तारीख और समय दिखना चाहिए।",
      },
      {
        mr: "Profile चा link/URL आणि username कॉपी करून ठेवा — नाव बदलता येतं, link नाही.",
        en: "Copy the profile link and username — display names change, links usually don't.",
        hi: "प्रोफ़ाइल लिंक और यूज़रनेम कॉपी करें — नाम बदलता है, लिंक नहीं।",
      },
      {
        mr: "चॅट delete करू नका; WhatsApp मध्ये 'Export chat' करून ठेवा.",
        en: "Don't delete chats; in WhatsApp use 'Export chat' to save a copy.",
        hi: "चैट डिलीट न करें; WhatsApp में 'Export chat' से कॉपी सेव करें।",
      },
      {
        mr: "पैशांच्या बाबतीत transaction ID, UPI ID, बँक SMS जपा.",
        en: "For money fraud, keep the transaction ID, UPI ID and bank SMS.",
        hi: "पैसों के मामले में ट्रांज़ैक्शन ID, UPI ID और बैंक SMS रखें।",
      },
      {
        mr: "सगळं एका folder मध्ये किंवा विश्वासातल्या व्यक्तीकडे copy ठेवा.",
        en: "Keep everything in one folder, and a copy with someone you trust.",
        hi: "सब एक फ़ोल्डर में रखें, और एक कॉपी किसी भरोसेमंद के पास।",
      },
    ],
    next: {
      mr: "पुरावा जमा झाला की cybercrime.gov.in वर तक्रार कशी करायची ते सांगू का?",
      en: "Once you've saved it, shall I explain how to report at cybercrime.gov.in?",
      hi: "सबूत सेव हो जाए तो क्या cybercrime.gov.in पर शिकायत का तरीका बताऊँ?",
    },
    actions: [
      { label: { mr: "ऑनलाइन तक्रार करा", en: "Report online", hi: "ऑनलाइन शिकायत करें" }, href: "https://cybercrime.gov.in" },
      { label: { mr: "सायबर हेल्पलाइन 1930", en: "Cyber helpline 1930", hi: "साइबर हेल्पलाइन 1930" }, href: "tel:1930" },
    ],
  },
];
