const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const ts=require('typescript');
function fixture(){
 const docs=new Map(),jar=new Map();
 function match(d,q){return Object.entries(q).every(([k,v])=>{if(v&&typeof v==='object'&&!(v instanceof Date)){return Object.entries(v).every(([op,x])=>op==='$gt'?d[k]>x:op==='$lte'?d[k]<=x:op==='$lt'?d[k]<x:false);}return d[k]===v;});}
 const db={collection(name){if(!docs.has(name))docs.set(name,new Map());const m=docs.get(name);return {createIndex:async()=>{},findOne:async q=>[...m.values()].find(d=>match(d,q))||null,findOneAndUpdate:async(q,u,opt={})=>{let d=[...m.values()].find(d=>match(d,q));if(!d){if(!opt.upsert)return null;if(m.has(q._id)){const e=Error('duplicate');e.code=11000;throw e;}d={_id:q._id,...u.$setOnInsert};m.set(q._id,d);}Object.assign(d,u.$set);for(const [k,n] of Object.entries(u.$inc||{}))d[k]=(d[k]||0)+n;return {...d};},updateOne:async(q,u,opt)=>db.collection(name).findOneAndUpdate(q,u,opt),findOneAndDelete:async q=>{const d=[...m.values()].find(d=>match(d,q));if(d)m.delete(d._id);return d||null;},deleteOne:async q=>db.collection(name).findOneAndDelete(q),insertOne:async d=>{m.set(d._id,d);}};}};
 const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/server/auth.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:n=>n==='next/headers'?{cookies:async()=>({get:k=>jar.has(k)?{value:jar.get(k)}:undefined,set:(k,v)=>jar.set(k,v),delete:k=>jar.delete(k)})}:n==='./mongo'?{mongoDb:async()=>db}:require(n),process:{env:{AUTH_SECRET:'test-secret-'.repeat(5),NODE_ENV:'test'}},Response,URL,Date,console});return {auth:module.exports,docs,jar};
}
test('OTP normalization, single use, session rotation and logout',async()=>{const {auth,jar}=fixture();assert.equal(auth.normalizePhone('98765 43210'),'919876543210');assert.throws(()=>auth.normalizePhone({phone:'123'}));let code;let result=await auth.startOtp('919876543210','test-ip',async(p,c)=>{code=c;return true;});assert.equal(result.status,200);assert.equal(await auth.verifyOtp(code,'test-ip'),true);const s=await auth.currentSession();assert.ok(s.customerId.startsWith('account:'));assert.equal(s.last4,'3210');assert.equal(await auth.verifyOtp(code,'test-ip'),false);await auth.signOut();assert.equal(await auth.currentSession(),null);assert.equal(jar.has('aadhi-session'),false);});
test('Wrong code locks after five attempts; cooldown and expiry are enforced',async()=>{const {auth,docs}=fixture();let code;await auth.startOtp('919876543210','ip',async(p,c)=>{code=c;return true;});assert.equal((await auth.startOtp('919876543210','ip',async()=>true)).status,429);const wrong=code==='111111'?'222222':'111111';for(let i=0;i<5;i++)assert.equal(await auth.verifyOtp(wrong,'ip'),false);assert.equal(await auth.verifyOtp(code,'ip'),false);const f=fixture();await f.auth.startOtp('919876543211','ip2',async(p,c)=>{code=c;return true;});for(const d of f.docs.get('auth_challenges').values())d.expiresAt=new Date(0);assert.equal(await f.auth.verifyOtp(code,'ip2'),false);});
test('Failed delivery never enables a challenge and unauthenticated APIs deny access',async()=>{const {auth,docs}=fixture();assert.equal((await auth.startOtp('919876543212','ip3',async()=>false)).status,503);assert.equal(docs.get('auth_challenges').size,0);assert.equal((await auth.requireAuth()).status,401);assert.equal(auth.sameOrigin(new Request('https://a.test/api',{headers:{origin:'https://b.test'}})),false);});
