"use client";
import {useEffect,useState,type ReactNode} from 'react';
import Link from 'next/link';
import {emptyProfile} from '@/lib/profile';
import {useLang} from '@/lib/i18n';
export default function AuthGate({children}:{children:ReactNode}){
 const {t,setAge}=useLang();const [loaded,setLoaded]=useState(false),[authenticated,setAuthenticated]=useState(false),[configured,setConfigured]=useState(false),[last4,setLast4]=useState('');
 const [phone,setPhone]=useState(''),[code,setCode]=useState(''),[consent,setConsent]=useState(false),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[cooldown,setCooldown]=useState(0);
 async function session(){try{const r=await fetch('/api/auth/session',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();setAuthenticated(d.authenticated);setConfigured(d.configured);setLast4(d.last4||'');setLoaded(true);}catch{setAuthenticated(false);setLoaded(true);setNotice(t({en:'Sign-in service is temporarily unavailable. Emergency help remains available below.',mr:'लॉगिन सेवा सध्या उपलब्ध नाही. आपत्कालीन मदत खाली उपलब्ध आहे.',hi:'लॉगिन सेवा अभी उपलब्ध नहीं है। आपातकालीन मदद नीचे उपलब्ध है।'}));}}
 useEffect(()=>{void session();const refresh=()=>{if(document.visibilityState==='visible')void session();};document.addEventListener('visibilitychange',refresh);window.addEventListener('aadhi-auth-required',refresh);return()=>{document.removeEventListener('visibilitychange',refresh);window.removeEventListener('aadhi-auth-required',refresh);};},[]);
 useEffect(()=>{if(!cooldown)return;const timer=setTimeout(()=>setCooldown(c=>c-1),1000);return()=>clearTimeout(timer);},[cooldown]);
 async function send(){setBusy(true);setNotice('');try{const r=await fetch('/api/auth/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,consent})});const d=await r.json();if(!r.ok){setNotice(d.error==='LIMIT'?t({en:'Too many requests. Wait before trying again.',mr:'खूप विनंत्या झाल्या. थोड्या वेळाने प्रयत्न करा.',hi:'बहुत अनुरोध हुए। थोड़ी देर बाद कोशिश करें।'}):d.error==='PHONE'?t({en:'Enter a valid mobile number with country code.',mr:'देशाच्या कोडसह योग्य मोबाइल नंबर द्या.',hi:'देश के कोड सहित सही मोबाइल नंबर डालें।'}):t({en:'The code could not be sent. Please try again later.',mr:'कोड पाठवता आला नाही. नंतर प्रयत्न करा.',hi:'कोड नहीं भेज सके। बाद में कोशिश करें।'}));return;}setSent(true);setCode('');setCooldown(60);setNotice(t({en:'Code submitted to SMS. Check your messages; delivery may take a moment. It expires in five minutes.',mr:'कोड SMS वर पाठवण्यासाठी दिला आहे. मेसेज तपासा. कोड पाच मिनिटांत संपेल.',hi:'कोड SMS पर भेजने के लिए दिया है। संदेश देखें। कोड पाँच मिनट में समाप्त होगा।'}));}catch{setNotice(t({en:'Connection failed. Try again.',mr:'कनेक्शन झाले नाही. पुन्हा प्रयत्न करा.',hi:'कनेक्शन नहीं हुआ। फिर कोशिश करें।'}));}finally{setBusy(false);}}
 async function verify(){setBusy(true);try{const r=await fetch('/api/auth/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});if(!r.ok){setNotice(t({en:'Invalid or expired code. Check it or request a new one.',mr:'कोड चुकीचा आहे किंवा संपला आहे. तपासा किंवा नवीन कोड मागवा.',hi:'कोड गलत है या समाप्त हो गया। जाँचें या नया कोड माँगें।'}));return;}
 // A verified account must not inherit another person's local transcript.
 try{localStorage.removeItem('aadhi-chat');localStorage.removeItem('aadhi-profile');}catch{}
 try{const saved=await fetch('/api/customer',{cache:'no-store'}).then(r=>r.json());if(saved.customer?.profile){localStorage.setItem('aadhi-profile',JSON.stringify({...emptyProfile,...saved.customer.profile,onboarded:true}));setAge(saved.customer.profile.age);}}catch{}
 setNotice('');setSent(false);setCode('');await session();
 }catch{setNotice(t({en:'Could not verify. Try again.',mr:'पडताळणी झाली नाही. पुन्हा प्रयत्न करा.',hi:'सत्यापन नहीं हुआ। फिर कोशिश करें।'}));}finally{setBusy(false);}}
 async function logout(){setBusy(true);try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw Error();try{localStorage.removeItem('aadhi-chat');localStorage.removeItem('aadhi-profile');}catch{}setAuthenticated(false);setSent(false);setConsent(false);setCode('');setPhone('');}catch{setNotice(t({en:'Sign-out failed. Please try again.',mr:'लॉगआउट झाले नाही. पुन्हा प्रयत्न करा.',hi:'लॉगआउट नहीं हुआ। फिर कोशिश करें।'}));}finally{setBusy(false);}}
 if(!loaded)return <p className="py-8" role="status">{t({en:'Checking sign-in…',mr:'लॉगिन तपासत आहे…',hi:'लॉगिन जाँच रहे हैं…'})}</p>;
 if(authenticated)return <><div className="flex items-center justify-between gap-3 py-2 text-xs text-kokum-700"><span>SMS · •••• {last4}</span><button disabled={busy} onClick={logout} className="min-h-11 underline">{t({en:'Sign out',mr:'लॉगआउट',hi:'लॉगआउट'})}</button></div>{notice&&<p role="status">{notice}</p>}{children}</>;
 return <section className="mx-auto my-6 max-w-lg rounded-3xl border border-kokum-100 bg-white p-5 sm:p-8">
 <h1 className="font-display text-2xl font-bold text-kokum-900">{t({en:'Sign in with SMS',mr:'SMS द्वारे लॉगिन करा',hi:'SMS से लॉगिन करें'})}</h1>
 <p className="mt-3 text-sm leading-relaxed">{t({en:'Verify your number to talk to the AI assistant. We use it for sign-in, not marketing. Saving your profile and conversations requires separate consent in My saved data.',mr:'AI सहाय्यकाशी बोलण्यासाठी नंबर पडताळा. नंबर फक्त लॉगिनसाठी वापरतो, जाहिरातींसाठी नाही. माहिती व संभाषणे जतन करण्यासाठी माझी माहिती विभागात स्वतंत्र संमती आवश्यक आहे.',hi:'AI सहायक से बात करने के लिए नंबर सत्यापित करें। नंबर लॉगिन के लिए है, प्रचार के लिए नहीं। जानकारी और बातचीत सहेजने के लिए मेरी जानकारी में अलग सहमति ज़रूरी है।'})}</p>
 {!configured&&<p className="mt-4 rounded-xl bg-kokum-50 p-3 text-sm">{t({en:'SMS sign-in setup is pending. Safety information is available without login.',mr:'SMS लॉगिनची जोडणी बाकी आहे. सुरक्षेची माहिती लॉगिनशिवाय उपलब्ध आहे.',hi:'SMS लॉगिन की तैयारी बाकी है। सुरक्षा की जानकारी बिना लॉगिन उपलब्ध है।'})}</p>}
 <form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();void(sent?verify():send());}}>
 <label className="block text-sm font-semibold">{t({en:'Mobile number',mr:'मोबाइल नंबर',hi:'मोबाइल नंबर'})}<input type="tel" autoComplete="tel" inputMode="tel" value={phone} disabled={sent||busy} maxLength={22} onChange={e=>setPhone(e.target.value)} placeholder="+91 98765 43210" className="mt-2 w-full rounded-xl border border-kokum-200 px-4 py-3" required/></label>
 {!sent&&<label className="flex gap-3 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 size-5 shrink-0"/>{t({en:'Send me a verification code on SMS. My number is shared with Twilio to deliver it; AADHI TI stores a protected identifier and the last four digits for sign-in.',mr:'SMS वर पडताळणी कोड पाठवा. कोड देण्यासाठी नंबर Twilio कडे जातो; आधी ती लॉगिनसाठी सुरक्षित ओळख व शेवटचे चार अंक साठवते.',hi:'SMS पर सत्यापन कोड भेजें। कोड पहुँचाने के लिए नंबर Twilio को जाता है; आधी ती लॉगिन के लिए सुरक्षित पहचान और अंतिम चार अंक रखती है।'})}</label>}
 {sent&&<label className="block text-sm font-semibold">{t({en:'Six-digit code',mr:'सहा अंकी कोड',hi:'छह अंकों का कोड'})}<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} className="mt-2 w-full rounded-xl border border-kokum-200 px-4 py-3 text-xl tracking-widest" required/></label>}
 <button disabled={!configured||busy||(!sent&&!consent)} className="min-h-12 w-full rounded-full bg-kokum-700 px-5 py-3 font-semibold text-white disabled:opacity-40">{busy?t({en:'Please wait…',mr:'थांबा…',hi:'कृपया रुकें…'}):sent?t({en:'Verify and continue',mr:'पडताळून पुढे जा',hi:'सत्यापित करके आगे बढ़ें'}):t({en:'Send code',mr:'कोड पाठवा',hi:'कोड भेजें'})}</button>
 {sent&&<div className="flex justify-between text-sm"><button type="button" disabled={busy||cooldown>0} onClick={send} className="min-h-11 underline disabled:opacity-40">{t({en:'Resend',mr:'पुन्हा पाठवा',hi:'दोबारा भेजें'})} {cooldown>0&&`(${cooldown}s)`}</button><button type="button" disabled={busy} onClick={()=>{setSent(false);setCode('');}} className="min-h-11 underline">{t({en:'Change number',mr:'नंबर बदला',hi:'नंबर बदलें'})}</button></div>}
 </form><p role="status" className="mt-3 text-sm">{notice}</p>
 <div className="mt-6 border-t border-kokum-100 pt-4"><p className="font-semibold">{t({en:'Need help now? No login required.',mr:'आत्ता मदत हवी? लॉगिन आवश्यक नाही.',hi:'अभी मदद चाहिए? लॉगिन ज़रूरी नहीं।'})}</p><div className="mt-3 flex flex-wrap gap-3"><a href="tel:112" className="rounded-full bg-kokum-50 px-4 py-3 font-semibold">112</a><a href="tel:181" className="rounded-full bg-kokum-50 px-4 py-3 font-semibold">181</a><Link href="/safe-shrivardhan" className="py-3 text-kokum-700 underline">{t({en:'Safety information',mr:'सुरक्षेची माहिती',hi:'सुरक्षा की जानकारी'})}</Link></div></div>
 </section>;
}
