"use client";
import JourneyChat from "@/components/JourneyChat";
import Link from 'next/link';
import { ArrowLeft, ArrowRight, ArrowUpRight, Plus, Phone } from 'lucide-react';
import { useLang } from '@/lib/i18n';
import { tr } from '@/lib/homeJourneys';
import type { journeyPages } from '@/lib/journeyPages';
import type { Topic, L } from '@/lib/kb';
import type { Scheme } from '@/lib/schemes';
import type { helplines } from '@/lib/data';
export default function JourneyDetail({journey:j,topics,schemes,numbers,navigation}:{journey:(typeof journeyPages)[number];topics:Topic[];schemes:Scheme[];numbers:typeof helplines;navigation:{slug:string;name:L;index:number}[]}){
 const {t}=useLang();

 return <div className="pb-10">
  <Link href="/#nine-pathways" className="my-5 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-kokum-700"><ArrowLeft size={16}/>{t(tr('All nine pathways','सर्व नऊ मार्ग','सभी नौ रास्ते'))}</Link>
  <section className="grid overflow-hidden rounded-[1.75rem] border border-kokum-100 bg-[#fbefed] md:grid-cols-2">
   <div role="img" aria-label={t(j.title)} className="journey-art aspect-square max-h-[390px] w-full md:max-h-none" style={{backgroundImage:'url(/illustrations/nine-journeys-v2.webp)',backgroundSize:'300% 300%',backgroundPosition:`${(j.index%3)*50}% ${Math.floor(j.index/3)*50}%`}}/>
   <div className="self-center p-6 sm:p-9"><p className="campaign-kicker">0{j.index+1} / {t(j.name)}</p><h1 className="mt-3 font-serif text-4xl leading-tight text-kokum-800 lg:text-5xl">{t(j.title)}</h1><p className="mt-4 text-lg leading-relaxed text-ink-soft">{t(j.body)}</p><div className="mt-6 flex flex-wrap gap-3"><Link href={j.tools[0].href} className="campaign-primary">{t(j.tools[0].label)}<ArrowUpRight size={17}/></Link><Link href="#ask-ai" className="campaign-secondary">{t(tr('Ask a question','प्रश्न विचारा','सवाल पूछें'))}</Link></div></div>
  </section>
  <nav aria-label={t(tr('On this page','या पानावर','इस पेज पर'))} className="my-6 flex flex-wrap gap-2">
   {[["ask-ai",tr("Ask AI","AI ला विचारा","AI से पूछें")],["guidance",tr('Guidance','मार्गदर्शन','मार्गदर्शन')],["resources",tr('Tools & resources','साधनं आणि माहिती','साधन और जानकारी')],...(numbers.length?[["support",tr('Support numbers','मदतीचे नंबर','सहायता नंबर')]]:[])].map(([id,label])=><a key={id as string} href={`#${id}`} className="soft-chip min-h-11">{t(label as L)}</a>)}
  </nav>
  <JourneyChat key={j.slug} slug={j.slug} title={j.title} suggestions={topics.slice(0,3).map(topic=>topic.title)}/>
  <section className="my-9 max-w-3xl"><h2 className="font-serif text-3xl text-kokum-800">{t(tr('A place to begin','सुरुवात इथून','यहाँ से शुरुआत'))}</h2><p className="mt-4 text-lg leading-relaxed text-ink-soft">{t(j.intro)}</p></section>
  <section id="guidance" className="scroll-mt-32"><h2 className="campaign-heading">{t(tr('What would you like help with?','कशासाठी मदत हवी आहे?','किस बारे में मदद चाहिए?'))}</h2><p className="mt-3 text-ink-soft">{t(tr('Open a topic to read the guidance here. Ask the assistant if you have a follow-up question.','इथेच मार्गदर्शन वाचण्यासाठी विषय उघडा. आणखी प्रश्न असल्यास सहाय्यकाला विचारा.','यहीं मार्गदर्शन पढ़ने के लिए विषय खोलें। आगे सवाल हो तो सहायक से पूछें।'))}</p>
   <div className="mt-6 space-y-3">{topics.map(topic=><details key={topic.id} className="group rounded-2xl border border-kokum-100 bg-white open:bg-[#fffaf6]"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 p-5 font-bold text-kokum-800 [&::-webkit-details-marker]:hidden">{t(topic.title)}<Plus size={18} className="shrink-0 transition group-open:rotate-45"/></summary><div className="px-5 pb-6 sm:px-7"><p className="max-w-3xl leading-relaxed text-ink-soft">{t(topic.understand)}</p><ul className="mt-4 max-w-3xl list-disc space-y-3 pl-5 text-ink">{topic.answer.map((a,i)=><li key={i}>{t(a)}</li>)}</ul><div className="mt-5 rounded-xl bg-kokum-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-kokum-600">{t(tr('Your next step','तुमचं पुढचं पाऊल','आपका अगला कदम'))}</p><p className="mt-1 text-kokum-800">{t(topic.next)}</p></div>{topic.girlNote && j.slug==='shailputri' && <p className="mt-4 text-sm text-ink-soft">{t(topic.girlNote)}</p>}<Link href={`/chat?topic=${topic.id}`} className="mt-5 inline-flex min-h-11 items-center gap-2 font-bold text-kokum-700">{t(tr('Continue with AADHI TI','AADHI TI सोबत पुढे बोला','AADHI TI के साथ आगे बात करें'))}<ArrowRight size={17}/></Link></div></details>)}</div>
  </section>
  <section id="resources" className="mt-12 scroll-mt-32"><h2 className="campaign-heading">{t(tr('Tools for your next step','पुढच्या पावलासाठी साधनं','अगले कदम के लिए साधन'))}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{j.tools.map(tool=><Link href={tool.href} key={tool.href} className="flex min-h-24 items-center justify-between gap-4 rounded-2xl bg-kokum-700 p-6 text-lg font-bold text-white">{t(tool.label)}<ArrowUpRight size={22} className="shrink-0"/></Link>)}</div>
  {schemes.length>0 && <div className="mt-8"><h3 className="font-serif text-2xl text-kokum-800">{t(tr('Related schemes and programmes','संबंधित योजना आणि कार्यक्रम','संबंधित योजनाएँ और कार्यक्रम'))}</h3><p className="mt-2 text-sm text-ink-soft">{t(tr('Explore eligibility and application guidance. Confirm current details with the relevant office before applying.','पात्रता आणि अर्जाबद्दल माहिती पाहा. अर्ज करण्यापूर्वी संबंधित कार्यालयात सध्याची माहिती तपासा.','पात्रता और आवेदन की जानकारी देखें। आवेदन से पहले संबंधित कार्यालय से वर्तमान विवरण की पुष्टि करें।'))}</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{schemes.map(s=><Link href={`/schemes#${s.id}`} key={s.id} className="rounded-2xl border border-kokum-100 p-5"><h4 className="font-bold text-kokum-800">{t(s.name)} ↗</h4><p className="mt-2 text-sm leading-relaxed text-ink-soft">{t(s.what)}</p></Link>)}</div></div>}
  </section>
  {numbers.length>0 && <section id="support" className="mt-12 scroll-mt-32 rounded-2xl bg-kokum-50 p-6"><h2 className="font-serif text-3xl text-kokum-800">{t(tr('Connect with support','मदतीशी संपर्क साधा','सहायता से जुड़ें'))}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{numbers.map(h=><a key={h.number} href={`tel:${h.number}`} className="flex items-center justify-between gap-3 rounded-xl bg-white p-4"><div><p className="font-semibold text-kokum-800">{t(h.name)}</p><p className="text-sm text-ink-soft">{t(h.desc)}</p></div><span className="inline-flex shrink-0 items-center gap-2 font-bold text-kokum-700"><Phone size={15}/>{h.number}</span></a>)}</div></section>}
  <nav aria-label={t(tr('Other pathways','इतर मार्ग','अन्य रास्ते'))} className="mt-12 border-t border-kokum-100 pt-6"><h2 className="font-serif text-2xl text-kokum-800">{t(tr('Explore another part of your journey','तुमच्या आयुष्यातील आणखी एक टप्पा','अपने सफ़र का एक और पड़ाव'))}</h2><div className="mt-4 flex flex-wrap gap-2">{navigation.filter(n=>n.slug!==j.slug).map(n=><Link href={`/journeys/${n.slug}`} key={n.slug} className="soft-chip min-h-11">0{n.index+1} · {t(n.name)}</Link>)}</div></nav>
 </div>;
}
