import type { L } from './kb';
export const tr = (en:string, mr:string, hi:string): L => ({en,mr,hi});
export const journeys = [
 {name:tr('Shailputri','शैलपुत्री','शैलपुत्री'), title:tr('A confident beginning','तिच्या अस्तित्वासाठी','उसके आत्मविश्वास के लिए'), body:tr('Growing, learning and finding her voice. Support for girls and mother–daughter conversations.','वाढ, शिक्षण आणि स्वतःचं मत मांडण्याचा आत्मविश्वास. मुलींसाठी आणि आई–मुलीच्या संवादासाठी मदत.','बढ़ना, सीखना और अपनी बात कहना। लड़कियों और माँ–बेटी के संवाद के लिए मार्गदर्शन।'), href:'/chat?cat=g_safety', link:tr('Guidance for girls','मुलींसाठी मार्गदर्शन','लड़कियों के लिए मार्गदर्शन')},
 {name:tr('Brahmacharini','ब्रह्मचारिणी','ब्रह्मचारिणी'),title:tr('Her next chapter','तिच्या शिक्षणासाठी','उसकी शिक्षा के लिए'),body:tr('Education, digital skills and career pathways. Find a practical next step for your ambitions.','शिक्षण, डिजिटल कौशल्ये आणि करिअरच्या संधी. तुमच्या स्वप्नांसाठी पुढचं पाऊल शोधा.','शिक्षा, डिजिटल कौशल और करियर के रास्ते। अपने सपनों की ओर अगला कदम खोजें।'),href:'/chat?cat=career',link:tr('Explore education & skills','शिक्षण आणि कौशल्ये','शिक्षा और कौशल')},
 {name:tr('Chandraghanta','चंद्रघंटा','चंद्रघंटा'),title:tr('Confidence to stay safe','तिच्या सुरक्षिततेसाठी','उसकी सुरक्षा के लिए'),body:tr('Everyday safety, online awareness and help when a situation feels wrong.','रोजची सुरक्षितता, ऑनलाइन जागरूकता आणि असुरक्षित वाटल्यास योग्य मदत.','रोज़मर्रा की सुरक्षा, ऑनलाइन जागरूकता और असुरक्षित महसूस होने पर मदद।'),href:'/chat?cat=safety',link:tr('Find safety guidance','सुरक्षेचं मार्गदर्शन','सुरक्षा मार्गदर्शन')},
 {name:tr('Kushmanda','कुष्मांडा','कूष्मांडा'),title:tr('Health at every age','तिच्या आरोग्यासाठी','उसके स्वास्थ्य के लिए'),body:tr('Understand your changing health needs, nutritious food and when to seek medical care.','बदलत्या आरोग्याच्या गरजा, पौष्टिक आहार आणि डॉक्टरांची मदत कधी घ्यावी हे समजून घ्या.','बदलती स्वास्थ्य ज़रूरतों, पौष्टिक भोजन और डॉक्टर की सलाह कब लें, यह समझें।'),href:'/poshan',link:tr('Explore health & nutrition','आरोग्य आणि पोषण','स्वास्थ्य और पोषण')},
 {name:tr('Skandamata','स्कंदमाता','स्कंदमाता'),title:tr('Care for the caregiver','तिच्या मातृत्वासाठी','उसके मातृत्व के लिए'),body:tr('Parenting and family support that makes room for your own wellbeing and aspirations too.','पालकत्व आणि कुटुंबासाठी मदत; तुमच्या स्वतःच्या आरोग्याला आणि स्वप्नांनाही जागा.','पालन-पोषण और परिवार का सहयोग, जिसमें आपके अपने स्वास्थ्य और सपनों के लिए भी जगह हो।'),href:'/chat?cat=family',link:tr('Find family support','कुटुंबासाठी मदत','परिवार के लिए सहयोग')},
 {name:tr('Katyayani','कात्यायनी','कात्यायनी'),title:tr('Know your rights','तिच्या न्यायहक्कांसाठी','उसके अधिकारों के लिए'),body:tr('Clear information about your rights, legal aid and the services you can approach.','तुमचे हक्क, कायदेशीर मदत आणि संपर्क करता येणाऱ्या सेवांबद्दल सोपी माहिती.','आपके अधिकारों, कानूनी सहायता और उपलब्ध सेवाओं के बारे में सरल जानकारी।'),href:'/chat?cat=rights',link:tr('Understand your rights','तुमचे हक्क जाणून घ्या','अपने अधिकार जानें')},
 {name:tr('Kalaratri','कालरात्री','कालरात्रि'),title:tr('Safer places, together','तिच्या संरक्षणासाठी','उसके संरक्षण के लिए'),body:tr('Explore the Safe Shrivardhan prototype for concerns about lighting, roads and public spaces.','रस्ते, प्रकाशव्यवस्था आणि सार्वजनिक ठिकाणांबद्दलच्या समस्यांसाठी सुरक्षित श्रीवर्धन प्रोटोटाइप पाहा.','सड़कों, रोशनी और सार्वजनिक स्थानों की समस्याओं के लिए सुरक्षित श्रीवर्धन प्रोटोटाइप देखें।'),href:'/safe-shrivardhan',link:tr('Explore Safe Shrivardhan','सुरक्षित श्रीवर्धन पाहा','सुरक्षित श्रीवर्धन देखें')},
 {name:tr('Mahagauri','महागौरी','महागौरी'),title:tr('Space to be heard','तिच्या मनःस्वास्थ्यासाठी','उसके मन की देखभाल'),body:tr('A place to ask about stress, relationships and emotional wellbeing, without judgement.','ताण, नातेसंबंध आणि मनःस्वास्थ्याबद्दल निःसंकोचपणे विचारण्याची जागा.','तनाव, रिश्तों और भावनात्मक स्वास्थ्य पर बिना झिझक बात करने की जगह।'),href:'/chat?cat=mind',link:tr('Talk about wellbeing','मनःस्वास्थ्याबद्दल बोला','मन की बात करें')},
 {name:tr('Siddhidatri','सिद्धिदात्री','सिद्धिदात्री'),title:tr('A future of her own','तिच्या सक्षम भविष्यासाठी','उसके सक्षम भविष्य के लिए'),body:tr('Self-help groups, schemes and local business ideas. Turn your skills into possibilities.','बचत गट, योजना आणि स्थानिक व्यवसायाच्या कल्पना. तुमच्या कौशल्यांतून संधी निर्माण करा.','स्वयं सहायता समूह, योजनाएँ और स्थानीय व्यवसाय के विचार। अपने कौशल से नए अवसर खोजें।'),href:'/schemes#income-finder',link:tr('Explore income opportunities','उत्पन्नाच्या संधी शोधा','आय के अवसर खोजें')},
];
