import { journeys, tr } from './homeJourneys';
import type { L } from './kb';
export type JourneyPage = {
 slug: string; intro: L; topics: string[]; schemes: string[]; numbers: string[];
 tools: {href:string; label:L}[];
};
const details: JourneyPage[] = [
 {slug:'shailputri', intro:tr('Aai–Mulgi Circle begins with listening. Explore growing up, personal boundaries and conversations that help a girl feel heard. Girls and caregivers can read together, or choose a question to ask the assistant.','आई–मुलगी संवादाची सुरुवात ऐकून घेण्यापासून होते. वाढत्या वयातील बदल, वैयक्तिक मर्यादा आणि मुलींना मनमोकळं बोलता येण्यासाठी मार्गदर्शन. मुली आणि पालक एकत्र वाचू शकतात किंवा सहाय्यकाला प्रश्न विचारू शकतात.','माँ–बेटी संवाद की शुरुआत सुनने से होती है। बढ़ती उम्र, निजी सीमाओं और खुलकर बात करने के बारे में जानें। लड़कियाँ और अभिभावक साथ पढ़ सकते हैं या सहायक से सवाल पूछ सकते हैं।'),topics:['g_trusted_adults','g_touch','g_say_no','g_puberty','g_nutrition','daughter_silent'],schemes:['lekladki','sukanya','icds'],numbers:['1098'],tools:[{href:'/chat?cat=g_safety',label:tr('Ask in the girls’ section','मुलींच्या विभागात विचारा','लड़कियों के विभाग में पूछें')},{href:'/poshan',label:tr('Explore nutrition','पोषणाबद्दल जाणून घ्या','पोषण के बारे में जानें')}]},
 {slug:'brahmacharini',intro:tr('My Next Step is a place to explore what comes after school, a break in education or a change in career. Start with your interests and qualifications, then explore courses, scholarships and job preparation.','शाळेनंतर, शिक्षणातील खंडानंतर किंवा करिअर बदलताना पुढचं पाऊल शोधा. तुमची आवड आणि शिक्षण लक्षात घेऊन अभ्यासक्रम, शिष्यवृत्ती आणि नोकरीची तयारी जाणून घ्या.','स्कूल के बाद, पढ़ाई में विराम के बाद या करियर बदलते समय अगला कदम खोजें। अपनी रुचियों और योग्यता के आधार पर पाठ्यक्रम, छात्रवृत्ति और नौकरी की तैयारी समझें।'),topics:['after_10_12','iti_courses','scholarships','return_to_education','write_cv','interview_prep'],schemes:['freeedu','pmkvy','ahilya'],numbers:[],tools:[{href:'/chat?cat=career',label:tr('Discuss my next step','माझं पुढचं पाऊल ठरवूया','मेरे अगले कदम पर बात करें')},{href:'/schemes#scheme-finder',label:tr('Find relevant schemes','योग्य योजना शोधा','संबंधित योजनाएँ खोजें')}]},
 {slug:'chandraghanta',intro:tr('Practical awareness for travel, public places and your phone. Learn about situations that concern you and prepare a safety plan before you need it. If there is immediate danger, use emergency help first.','प्रवासात, सार्वजनिक ठिकाणी आणि फोन वापरताना उपयुक्त जागरूकता. काळजी वाटणाऱ्या परिस्थितींबद्दल जाणून घ्या आणि आधीच सुरक्षा योजना तयार ठेवा. तातडीचा धोका असल्यास प्रथम आपत्कालीन मदत घ्या.','यात्रा, सार्वजनिक स्थानों और फ़ोन के इस्तेमाल में उपयोगी जागरूकता। चिंता वाली परिस्थितियों को समझें और पहले से सुरक्षा योजना बनाएँ। तुरंत खतरा हो तो पहले आपातकालीन मदद लें।'),topics:['following_me','unsafe_travel','public_harassment','photo_threat','otp_scam','secure_whatsapp'],schemes:[],numbers:['112','1091','1930'],tools:[{href:'/call',label:tr('Open safety call','सुरक्षा कॉल उघडा','सुरक्षा कॉल खोलें')},{href:'/#safety-plan',label:tr('Make my safety plan','माझी सुरक्षा योजना','मेरी सुरक्षा योजना')}]},
 {slug:'kushmanda',intro:tr('Your health needs change through life. Explore information about periods, anaemia, PCOS, thyroid health and nutrition, and prepare questions for a qualified healthcare professional. This is health education, not a diagnosis.','आयुष्याच्या टप्प्यांनुसार आरोग्याच्या गरजा बदलतात. पाळी, रक्तक्षय, PCOS, थायरॉईड आणि पोषणाबद्दल माहिती मिळवा; डॉक्टरांना विचारायचे प्रश्न तयार करा. हे आरोग्य शिक्षण आहे, निदान नाही.','जीवन के साथ स्वास्थ्य की ज़रूरतें बदलती हैं। माहवारी, एनीमिया, PCOS, थायरॉइड और पोषण के बारे में जानें और डॉक्टर से पूछने के लिए सवाल तैयार करें। यह स्वास्थ्य शिक्षा है, निदान नहीं।'),topics:['anaemia','irregular_periods','pcos','thyroid','gyn_questions','menopause'],schemes:['amb','icds'],numbers:['108'],tools:[{href:'/poshan',label:tr('Open nutrition guide','पोषण मार्गदर्शक','पोषण मार्गदर्शिका')},{href:'/chat?cat=health',label:tr('Ask a health question','आरोग्याबद्दल विचारा','स्वास्थ्य पर सवाल पूछें')}]},
 {slug:'skandamata',intro:tr('Support for mothers as caregivers and as individuals. Explore pregnancy, caring for a new baby and recovery, while making room for your own questions, rest and wellbeing.','आई म्हणून आणि स्वतंत्र व्यक्ती म्हणून तुमच्यासाठी आधार. गर्भधारणा, बाळाची काळजी आणि प्रसूतीनंतरची काळजी जाणून घ्या; तुमच्या प्रश्नांना, विश्रांतीला आणि मनःस्वास्थ्यालाही महत्त्व द्या.','माँ और एक स्वतंत्र व्यक्ति के रूप में आपके लिए सहयोग। गर्भावस्था, नवजात की देखभाल और प्रसव के बाद की जानकारी पाएँ, साथ ही अपने सवालों, आराम और मन की देखभाल को जगह दें।'),topics:['pregnancy_checkups','pregnancy_nutrition','delivery_prep','postpartum_recovery','breastfeeding','postpartum_struggle'],schemes:['pmmvy','jssk','icds'],numbers:['108','14416'],tools:[{href:'/poshan',label:tr('Nutrition for mother and child','आई आणि बाळासाठी पोषण','माँ और बच्चे का पोषण')},{href:'/chat?cat=family',label:tr('Ask about family support','कुटुंबासाठी मदत विचारा','परिवार के सहयोग पर पूछें')}]},
 {slug:'katyayani',intro:tr('Knowing your rights can help you choose your next step. Read about legal aid, workplace concerns, family matters and documenting abuse. The assistant offers information; a qualified legal professional can advise on your situation.','तुमचे हक्क समजल्यावर पुढचं पाऊल निवडणं सोपं होऊ शकतं. कायदेशीर मदत, कामाच्या ठिकाणचे प्रश्न, कौटुंबिक बाबी आणि छळाची नोंद याबद्दल वाचा. सहाय्यक माहिती देतो; तुमच्या प्रकरणासाठी वकिलांचा सल्ला घ्या.','अपने अधिकार जानकर अगला कदम चुनना आसान हो सकता है। कानूनी सहायता, कार्यस्थल, पारिवारिक मामलों और उत्पीड़न का विवरण रखने के बारे में पढ़ें। सहायक जानकारी देता है; अपने मामले के लिए योग्य कानूनी सलाह लें।'),topics:['legal_aid','workplace_posh','property_rights','maintenance','zero_fir','document_abuse'],schemes:[],numbers:['15100','181','112'],tools:[{href:'/chat?cat=rights',label:tr('Ask about my rights','माझ्या हक्कांबद्दल विचारा','अपने अधिकारों पर पूछें')},{href:'tel:15100',label:tr('Call legal aid · 15100','कायदेशीर मदत · 15100','कानूनी सहायता · 15100')}]},
 {slug:'kalaratri',intro:tr('Safer streets start with noticing the places that need attention: lighting gaps, isolated stops and difficult school routes. Explore the Safe Shrivardhan reporting prototype. Demo reports are not sent to authorities and cannot request emergency response.','कमी उजेडाचे रस्ते, एकाकी थांबे आणि शाळेच्या मार्गातील अडचणी ओळखणं ही सुरक्षित परिसराची सुरुवात. सुरक्षित श्रीवर्धन अहवाल प्रोटोटाइप पाहा. डेमो अहवाल प्रशासनाला पाठवले जात नाहीत; त्यातून आपत्कालीन मदत मागता येत नाही.','कम रोशनी वाली सड़कें, सुनसान ठहराव और स्कूल के रास्ते की समस्याएँ पहचानना सुरक्षित समुदाय की शुरुआत है। सुरक्षित श्रीवर्धन रिपोर्टिंग प्रोटोटाइप देखें। डेमो रिपोर्ट अधिकारियों को नहीं भेजी जाती और आपातकालीन सहायता नहीं बुलाती।'),topics:['report_unsafe_place','unsafe_transport','solo_travel','night_carry','help_info_ready'],schemes:[],numbers:['112','1091'],tools:[{href:'/safe-shrivardhan',label:tr('Explore the reporting demo','अहवाल डेमो पाहा','रिपोर्टिंग डेमो देखें')},{href:'/#safety-plan',label:tr('Prepare a safety plan','सुरक्षा योजना तयार करा','सुरक्षा योजना बनाएँ')}]},
 {slug:'mahagauri',intro:tr('You deserve time and space for yourself. Explore questions about stress, loneliness, relationships and postpartum wellbeing. Read at your own pace, talk to the assistant, or connect with a qualified counsellor when you need more support.','स्वतःसाठी वेळ आणि जागा मिळणंही महत्त्वाचं आहे. ताण, एकटेपणा, नातेसंबंध आणि प्रसूतीनंतरच्या मनःस्वास्थ्याबद्दल जाणून घ्या. तुमच्या गतीने वाचा, सहाय्यकाशी बोला किंवा गरजेनुसार पात्र समुपदेशकांची मदत घ्या.','अपने लिए समय और जगह मिलना भी ज़रूरी है। तनाव, अकेलेपन, रिश्तों और प्रसव के बाद के भावनात्मक स्वास्थ्य के बारे में जानें। अपनी गति से पढ़ें, सहायक से बात करें या ज़रूरत पर योग्य परामर्शदाता की मदद लें।'),topics:['overwhelmed','stress','lonely','family_pressure','postpartum_struggle','counsellor'],schemes:[],numbers:['14416','112'],tools:[{href:'/chat?cat=mind',label:tr('Talk to AADHI TI','AADHI TI शी बोला','AADHI TI से बात करें')},{href:'tel:14416',label:tr('Tele-MANAS · 14416','Tele-MANAS · 14416','Tele-MANAS · 14416')}]},
 {slug:'siddhidatri',intro:tr('Build on what you know and what you want to learn. Explore self-help groups, training and local enterprise ideas, from food businesses to homestays. Use the income finder to compare possibilities for your circumstances.','तुमच्या कौशल्यांवर आणि शिकण्याच्या इच्छेवर पुढचं पाऊल उभारा. बचत गट, प्रशिक्षण, खाद्य व्यवसाय आणि होमस्टेसारख्या स्थानिक संधी शोधा. उत्पन्न शोधकातून तुमच्या परिस्थितीला योग्य पर्याय पाहा.','अपने कौशल और सीखने की इच्छा से अगला कदम शुरू करें। स्वयं सहायता समूह, प्रशिक्षण, खाद्य व्यवसाय और होमस्टे जैसे स्थानीय अवसर खोजें। आय खोजक से अपनी परिस्थिति के अनुकूल विकल्प देखें।'),topics:['join_shg','start_business','food_business','homestay','sell_online','business_documents'],schemes:['mavim','umed','mudra','pmfme'],numbers:[],tools:[{href:'/schemes#income-finder',label:tr('Find income opportunities','उत्पन्नाच्या संधी शोधा','आय के अवसर खोजें')},{href:'/chat?cat=income',label:tr('Discuss my business idea','माझ्या व्यवसायाच्या कल्पनेवर बोला','मेरे व्यवसाय के विचार पर बात करें')}]},
];
export const journeyPages = journeys.map((journey,index)=>({...journey,...details[index],index}));
