import type { L } from '@/lib/kb';
const tr = (en: string, mr: string, hi: string): L => ({ en, mr, hi });
export const people = [
 { slug:'sunetra-pawar', image:'/brand/sunetra-pawar.png', position:'50% 25%', name:tr('Sunetra Pawar','सुनेत्रा पवार','सुनेत्रा पवार'), role:tr('Deputy Chief Minister, Maharashtra','उपमुख्यमंत्री, महाराष्ट्र','उपमुख्यमंत्री, महाराष्ट्र'),
 about:tr('Sunetra Pawar is a public representative from Maharashtra. A Press Information Bureau release dated 31 January 2026 records her taking office as Deputy Chief Minister, becoming the first woman to hold that responsibility in the state.','सुनेत्रा पवार या महाराष्ट्रातील लोकप्रतिनिधी आहेत. 31 जानेवारी 2026 च्या प्रेस इन्फॉर्मेशन ब्युरोच्या प्रसिद्धिपत्रकानुसार त्यांनी उपमुख्यमंत्रीपदाची जबाबदारी स्वीकारली. हे पद भूषवणाऱ्या त्या महाराष्ट्रातील पहिल्या महिला ठरल्या.','सुनेत्रा पवार महाराष्ट्र की जनप्रतिनिधि हैं। 31 जनवरी 2026 की प्रेस सूचना ब्यूरो की विज्ञप्ति के अनुसार उन्होंने उपमुख्यमंत्री का पदभार संभाला। वह महाराष्ट्र में यह ज़िम्मेदारी संभालने वाली पहली महिला बनीं।'),
 detail:tr('Her appointment is documented by the Government of India. The Maharashtra Medical Goods Procurement Authority also maintains a public profile under her name. These official pages are linked below for further information.','त्यांच्या नियुक्तीची नोंद भारत सरकारच्या प्रसिद्धिपत्रकात आहे. महाराष्ट्र वैद्यकीय वस्तू खरेदी प्राधिकरणाच्या संकेतस्थळावरही त्यांचे सार्वजनिक परिचयपृष्ठ उपलब्ध आहे. अधिक माहितीसाठी खालील अधिकृत स्रोत पाहा.','उनकी नियुक्ति भारत सरकार की विज्ञप्ति में दर्ज है। महाराष्ट्र चिकित्सा वस्तु खरीद प्राधिकरण की वेबसाइट पर भी उनका सार्वजनिक परिचय उपलब्ध है। अधिक जानकारी के लिए नीचे दिए आधिकारिक स्रोत देखें।'),
 sources:[{label:'Government of India · PIB, 31 January 2026',url:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2221265&lang=1&reg=3'},{label:'Government of Maharashtra · Public profile',url:'https://mmgpa.maharashtra.gov.in/en/whoswho/hon-smt-sunetra-ajit-pawar/'}]},
 {slug:'bhaskar-daji-vichare',image:'/brand/bhaskar-daji-vichare.png',position:'50% 20%',name:tr('Bhaskar Daji Vichare','भास्कर दाजी विचारे','भास्कर दाजी विचारे'),role:tr('Social work and community development','सामाजिक कार्य आणि सामुदायिक विकास','सामाजिक कार्य और सामुदायिक विकास'),
 about:tr('Bhaskar Daji Vichare’s public biography describes his social work in Mumbai and Raigad and dates the start of his political career to 1974. It lists community facilities and local development among his areas of work.','भास्कर दाजी विचारे यांच्या सार्वजनिक चरित्रात मुंबई आणि रायगडमधील सामाजिक कार्याचा उल्लेख आहे. त्यानुसार त्यांच्या राजकीय कार्याची सुरुवात 1974 मध्ये झाली. स्थानिक विकास आणि सामुदायिक सुविधा ही त्यांच्या कामाची क्षेत्रे म्हणून नमूद आहेत.','भास्कर दाजी विचारे के सार्वजनिक परिचय में मुंबई और रायगढ़ में सामाजिक कार्य का उल्लेख है। इसके अनुसार उनका राजनीतिक कार्य 1974 में शुरू हुआ। स्थानीय विकास और सामुदायिक सुविधाएँ उनके कार्यक्षेत्रों में शामिल हैं।'),
 detail:tr('His own website mentions women’s self-help groups, public sanitation, an eco-garden and a reading library for senior citizens. These are self-reported activities; the linked biography provides the original account.','त्यांच्या स्वतःच्या संकेतस्थळावर महिला बचत गट, सार्वजनिक स्वच्छतागृहे, पर्यावरण उद्यान आणि ज्येष्ठ नागरिकांसाठी वाचनालय यांचा उल्लेख आहे. ही माहिती त्यांच्या स्वतःच्या परिचयावर आधारित आहे; मूळ तपशील खालील दुव्यावर वाचा.','उनकी अपनी वेबसाइट पर महिला स्वयं सहायता समूह, सार्वजनिक शौचालय, पर्यावरण उद्यान और वरिष्ठ नागरिकों के लिए वाचनालय का उल्लेख है। ये विवरण उनके स्वयं के परिचय पर आधारित हैं; मूल जानकारी नीचे दिए लिंक पर पढ़ें।'),sources:[{label:'Bhaskar Vichare · Personal biography',url:'https://bhaskarvichare.com/bio.php'}]},
 {slug:'abhishek-bhaskar-vichare',image:'/brand/abhishek-bhaskar-vichare.png',position:'50% 25%',name:tr('Abhishek Bhaskar Vichare','अभिषेक भास्कर विचारे','अभिषेक भास्कर विचारे'),role:tr('Business and community initiatives','व्यवसाय आणि सामाजिक उपक्रम','व्यवसाय और सामाजिक पहल'),
 about:tr('Abhishek Bhaskar Vichare’s professional profile associates him with Richmond India Group. His personal website describes a background in marketing and administration, alongside engineering and communications studies.','अभिषेक भास्कर विचारे यांच्या व्यावसायिक परिचयात रिचमंड इंडिया ग्रुपशी त्यांचा संबंध नमूद आहे. त्यांच्या वैयक्तिक संकेतस्थळावर विपणन आणि प्रशासनातील अनुभव तसेच अभियांत्रिकी आणि संचार विषयातील शिक्षणाचा उल्लेख आहे.','अभिषेक भास्कर विचारे के व्यावसायिक परिचय में रिचमंड इंडिया ग्रुप से उनका संबंध दर्ज है। उनकी निजी वेबसाइट पर विपणन और प्रशासन के अनुभव तथा इंजीनियरिंग और संचार की पढ़ाई का उल्लेख है।'),
 detail:tr('His LinkedIn profile lists volunteer roles with Richmond India Foundation and Richmond Sports Association. This summary draws on his own public profiles; follow the source links for the full account and any updates.','त्यांच्या LinkedIn परिचयात रिचमंड इंडिया फाउंडेशन आणि रिचमंड स्पोर्ट्स असोसिएशनमधील स्वयंसेवी भूमिकांचा उल्लेख आहे. हा परिचय त्यांनी सार्वजनिक केलेल्या माहितीवर आधारित आहे. संपूर्ण आणि अद्ययावत माहितीसाठी मूळ दुवे पाहा.','उनके LinkedIn परिचय में रिचमंड इंडिया फाउंडेशन और रिचमंड स्पोर्ट्स एसोसिएशन में स्वयंसेवी भूमिकाएँ दर्ज हैं। यह सार उनके स्वयं के सार्वजनिक परिचय पर आधारित है। पूरी और अद्यतन जानकारी के लिए मूल लिंक देखें।'),sources:[{label:'Abhishek Vichare · Personal website',url:'https://www.abhishekvichare.com/index1.html'},{label:'Abhishek Bhaskar Vichare · Professional profile',url:'https://in.linkedin.com/in/abhishekbhaskarvichare'}]}
];
