"use client";
import AuthGate from "@/components/AuthGate";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useLang} from '@/lib/i18n';
import {useProfile} from '@/lib/profile';
export default function MyData(){return <AuthGate><DataSettings /></AuthGate>;}
function DataSettings(){
 const {t,lang}=useLang();const {profile,ready}=useProfile();
 const [configured,setConfigured]=useState(false),[loaded,setLoaded]=useState(false),[profileConsent,setProfileConsent]=useState(false),[historyConsent,setHistoryConsent]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [history,setHistory]=useState<{id:string;question:string;answer:string;savedAt:string}[]>([]);
 const [savedProfile,setSavedProfile]=useState<Record<string,unknown>|null>(null);
 async function refresh(){try{const r=await fetch('/api/customer',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();setConfigured(d.configured);setProfileConsent(d.customer?.consent.profile??false);setHistoryConsent(d.customer?.consent.history??false);setHistory(d.customer?.history??[]);setSavedProfile(d.customer?.profile??null);setLoaded(true);}catch{setNotice(t({en:'Could not load saved data. Please reload to try again.',mr:'जतन केलेली माहिती उघडता आली नाही. पुन्हा प्रयत्न करा.',hi:'सहेजी जानकारी नहीं खुल सकी। फिर कोशिश करें।'}));}}
 useEffect(()=>{void refresh();},[]);
 async function save(){setBusy(true);setNotice('');try{const r=await fetch('/api/customer',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:{name:profile.name,taluka:profile.taluka,age:profile.age,language:lang,answerMode:profile.answerMode},profileConsent,historyConsent})});if(!r.ok)throw Error();await refresh();setNotice(t({en:'Saved successfully.',mr:'माहिती जतन झाली.',hi:'जानकारी सहेजी गई।'}));}catch{setNotice(t({en:'Could not save. Nothing is confirmed saved; please try again.',mr:'माहिती जतन झाली नाही. पुन्हा प्रयत्न करा.',hi:'जानकारी सहेजी नहीं जा सकी। फिर कोशिश करें।'}));}finally{setBusy(false);}}
 async function remove(){if(!confirm(t({en:'Permanently delete your saved server profile and conversations?',mr:'सर्व्हरवरील तुमची माहिती आणि संभाषणे कायमची हटवायची?',hi:'सर्वर से आपकी जानकारी और बातचीत स्थायी रूप से मिटाएँ?'})))return;setBusy(true);try{const r=await fetch('/api/customer',{method:'DELETE'});if(!r.ok)throw Error();await refresh();setNotice(t({en:'Server data deleted. Details stored on this phone are unchanged.',mr:'सर्व्हरवरील माहिती हटवली. या फोनवरील माहिती बदललेली नाही.',hi:'सर्वर की जानकारी मिटा दी गई। इस फ़ोन की जानकारी नहीं बदली है।'}));}catch{setNotice(t({en:'Deletion failed. Your data has not been confirmed deleted.',mr:'माहिती हटवता आली नाही.',hi:'जानकारी मिटाई नहीं जा सकी।'}));}finally{setBusy(false);}}
 return <div className="mx-auto max-w-2xl space-y-6 pb-12">
 <h1 className="font-display text-3xl font-bold text-kokum-800">{t({en:'My saved data',mr:'माझी जतन केलेली माहिती',hi:'मेरी सहेजी जानकारी'})}</h1>
 <p>{t({en:'Saving is optional. You can use the assistant without saving data to our database. Saved records are linked to your verified WhatsApp sign-in, so you can access them on another device. Signing out clears local profile and chat data.',mr:'माहिती जतन करणे ऐच्छिक आहे. डेटाबेसमध्ये माहिती न साठवताही सहाय्यक वापरता येतो. जतन केलेली माहिती पडताळलेल्या WhatsApp खात्याशी जोडली जाते. दुसऱ्या उपकरणावरही लॉगिन करता येते. लॉगआउट केल्यावर फोनवरील प्रोफाइल व चॅट हटतात.',hi:'जानकारी सहेजना वैकल्पिक है। बिना डेटाबेस में जानकारी सहेजे भी सहायक इस्तेमाल कर सकती हैं। रिकॉर्ड सत्यापित WhatsApp खाते से जुड़ते हैं और दूसरे उपकरण पर भी लॉगिन करके खुलते हैं। लॉगआउट पर स्थानीय प्रोफ़ाइल और चैट मिटते हैं।'})}</p>
 {!loaded?<p>{t({en:'Loading…',mr:'उघडत आहे…',hi:'लोड हो रहा है…'})}</p>:!configured?<p className="rounded-xl bg-kokum-50 p-4">{t({en:'Database setup is pending. No customer data is being saved to MongoDB yet.',mr:'डेटाबेस जोडणे बाकी आहे. सध्या MongoDB मध्ये माहिती जतन होत नाही.',hi:'डेटाबेस जोड़ना बाकी है। अभी MongoDB में जानकारी नहीं सहेजी जा रही है।'})}</p>:null}
 <div className="rounded-2xl border border-kokum-100 p-5">
 <h2 className="font-bold">{t({en:'Details to save',mr:'जतन करायची माहिती',hi:'सहेजी जाने वाली जानकारी'})}</h2>
 <p className="mt-2">{t({en:'Name (if supplied), taluka, age group, language and answer preference. Pregnancy and children’s details are not stored in the customer profile.',mr:'नाव (दिल्यास), तालुका, वयोगट, भाषा आणि उत्तराची पसंती. गर्भधारणा व मुलांची माहिती ग्राहक प्रोफाइलमध्ये साठवली जात नाही.',hi:'नाम (यदि दिया हो), तालुका, आयु वर्ग, भाषा और जवाब की पसंद। गर्भावस्था और बच्चों की जानकारी ग्राहक प्रोफ़ाइल में नहीं सहेजी जाती।'})}</p>
 <p className="mt-3 text-sm">{profile.name || '—'} · {profile.taluka} · {profile.age || '—'} · {lang}</p>
 <Link href="/chat" className="mt-3 inline-block text-kokum-700 underline">{t({en:'Edit basic details in chat',mr:'चॅटमध्ये माहिती बदला',hi:'चैट में जानकारी बदलें'})}</Link>
 </div>
 <label className="flex items-start gap-3"><input type="checkbox" className="mt-1 size-5 shrink-0" checked={profileConsent} onChange={e=>{setProfileConsent(e.target.checked);if(!e.target.checked)setHistoryConsent(false);}}/><span>{t({en:'I agree to save my basic profile and preferences in AADHI TI’s database.',mr:'माझी मूलभूत माहिती आणि पसंती आधी तीच्या डेटाबेसमध्ये जतन करण्यास मी संमती देते.',hi:'मैं अपनी बुनियादी जानकारी और पसंद आधी ती के डेटाबेस में सहेजने की सहमति देती हूँ।'})}</span></label>
 <label className="flex items-start gap-3"><input type="checkbox" className="mt-1 size-5 shrink-0" disabled={!profileConsent} checked={historyConsent} onChange={e=>setHistoryConsent(e.target.checked)}/><span>{t({en:'Also save my future website questions and answers (up to 100 exchanges). These may contain sensitive information; authorised database administrators can access them. Existing conversations are not uploaded. Turning this off and saving deletes stored conversations.',mr:'यापुढील वेबसाइटवरील प्रश्न आणि उत्तरेही जतन करा (जास्तीत जास्त १००). यात संवेदनशील माहिती असू शकते; अधिकृत डेटाबेस प्रशासक ती पाहू शकतात. जुनी संभाषणे पाठवली जात नाहीत. हे बंद करून जतन केल्यास साठवलेली संभाषणे हटतात.',hi:'आगे की वेबसाइट बातचीत भी सहेजें (अधिकतम १०० सवाल-जवाब)। इनमें संवेदनशील जानकारी हो सकती है; अधिकृत डेटाबेस व्यवस्थापक इन्हें देख सकते हैं। पुरानी बातचीत अपलोड नहीं होगी। इसे बंद करके सहेजने पर पिछली सहेजी बातचीत मिट जाएगी।'})}</span></label>
 <div className="flex flex-wrap gap-3"><button onClick={save} disabled={!ready||!loaded||!configured||!profileConsent||busy} className="rounded-full bg-kokum-700 px-5 py-3 text-white disabled:opacity-40">{t({en:'Save preferences',mr:'पसंती जतन करा',hi:'पसंद सहेजें'})}</button><button onClick={remove} disabled={!savedProfile||busy} className="rounded-full border border-kokum-200 px-5 py-3 text-kokum-800 disabled:opacity-40">{t({en:'Delete my server data',mr:'सर्व्हरवरील माहिती हटवा',hi:'सर्वर की जानकारी मिटाएँ'})}</button></div>
 <p role="status" aria-live="polite">{notice}</p>
 {savedProfile&&<details><summary className="cursor-pointer font-semibold">{t({en:'View saved profile',mr:'जतन केलेली माहिती पाहा',hi:'सहेजी जानकारी देखें'})}</summary><pre className="mt-3 overflow-auto rounded-xl bg-kokum-50 p-4 text-sm">{JSON.stringify(savedProfile,null,2)}</pre></details>}
 <h2 className="text-xl font-bold">{t({en:'Saved conversations',mr:'जतन केलेली संभाषणे',hi:'सहेजी बातचीत'})} ({history.length})</h2>
 {history.slice().reverse().map(h=><details key={h.id} className="rounded-xl border border-kokum-100 p-4"><summary className="cursor-pointer break-words">{h.question}</summary><p className="mt-3 whitespace-pre-wrap break-words">{h.answer}</p><time className="mt-2 block text-xs text-ink-soft">{new Date(h.savedAt).toLocaleString(lang)}</time></details>)}
 </div>;
}
